### ISSUE TITLE
NJS-045 error on windows when install oracledb 

### ISSUE THREAD

**Issue by CZhangMia** [oracle/node-oracledb#1004]
1. What is your Node.js version?  Is it 64-bit or 32-bit?  
Node 10.13.0 64-bit

2. What is your node-oracledb version?
I did not specify the version as I simply run 'npm install oracledb', according to the logs, the version should be 3.0.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
npm start
I am working on a remote computer, logged in as admin and the cmd is run as admin.

4. What error(s) you are seeing?

>C:\AB_DataFetcher>npm start

> wasteedu-master@1.0.0 start C:\AB_DataFetcher
> node server.js

>C:\AB_DataFetcher\node_modules\oracledb\lib\oracledb.js:68
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^

>Error: NJS-045: cannot load the oracledb add-on binary for Node.js 10.13.0 (win3
2, x64)
Cannot load C:\AB_DataFetcher\node_modules\oracledb\build\Release\oracledb.node
\\?\C:\AB_DataFetcher\node_modules\oracledb\build\Release\oracledb.node is not a
 valid Win32 application.
\\?\C:\AB_DataFetcher\node_modules\oracledb\build\Release\oracledb.node
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

    at Object.<anonymous> (C:\AB_DataFetcher\node_modules\oracledb\lib\oracledb.js:68:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\AB_DataFetcher\node_modules\oracledb\index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

5. What OS (and version) is Node.js executing on?
windows 2012 R2 standard

6. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
I download '**instantclient-basic-windows.x64-18.3.0.0.0dbru.zip**' from oracle website. 

7. What is your Oracle Database version?
12.2.0.1.0

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
C:\Users\axxxxxxxx\AppData\Roaming\npm;C:\oracle\instantclient_12_2

9. What Oracle environment variables did you set?  How *exactly* did you set them?
I have not set any of them.

10. Do you have a small, single Node.js script that immediately runs to show us the problem?
Even a single line 'var oracledb = require('oracledb');' throws the same error.

**Comment by cjbj** [comment]
> A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

Did you install the VS 2013 Redistributable https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads  as mentioned on https://www.oracle.com/technetwork/topics/winx64soft-089540.html ?

**Comment by CZhangMia** [comment]
> > A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.
> 
> Did you install the VS 2013 Redistributable https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads as mentioned on https://www.oracle.com/technetwork/topics/winx64soft-089540.html ?

Yes, I have installed VS 2013 redistributable already.

**Comment by CZhangMia** [comment]
> Theoretically you need 2015 as well, since the node-oracledb binary was built with a different compiler than the Instant Client. Check your PATH and make sure there are no other Oracle directories before the Instant Client directory; does your PATH really only have two directories in it?

Sorry, I included the user variables but not the system one by mistake. Please find the system PATH as below:
> C:\Users\axxxxxxx\bin\Sencha\Cmd\5.1.3.61;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%ANT_HOME%\bin;C:\Ruby200-x64\bin;C:\Program Files\nodejs\;C:\oracle\instantclient_12_2

And, I notice that there is already a vs 2017 redistributed installed on the computer, which stops 2015 from installation. Should I uninstall 2017 and try 2015?

**Comment by cjbj** [comment]
@CZhangMia how are you going with this?

**Comment by CZhangMia** [comment]
@cjbj I still cannot make it work on windows. You can check my last post here with some more details. I am now switching to mac and it's all good so far, but I really hope I can make it work on windows.

**Comment by cjbj** [comment]
When running node, make sure instant client is in your path before other Oracle libraries.  Do you have other oci.dll files on your computer?  If you have problems, trying unzipping Instant Client Basic (or Basic Light) into the node_modules\oracledb\build\Release directory so the DLLs are in the same directory as oracledb.node.

**Comment by HypoXiao** [comment]
@CZhangMia I met the same problem, and finally I implemented it(see the url below) step by step in strict accordance with the following ways, and finally solved it.
https://community.oracle.com/docs/DOC-931127
![wd-node-oracle](https://user-images.githubusercontent.com/18320778/48909316-e2fd4b80-eea7-11e8-88ba-c87e7f6f4dde.png)

**Comment by HypoXiao** [comment]
> > Theoretically you need 2015 as well, since the node-oracledb binary was built with a different compiler than the Instant Client. Check your PATH and make sure there are no other Oracle directories before the Instant Client directory; does your PATH really only have two directories in it?
> 
> Sorry, I included the user variables but not the system one by mistake. Please find the system PATH as below:
> 
> > C:\Users\axxxxxxx\bin\Sencha\Cmd\5.1.3.61;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;%ANT_HOME%\bin;C:\Ruby200-x64\bin;C:\Program Files\nodejs;C:\oracle\instantclient_12_2
> 
> And, I notice that there is already a vs 2017 redistributed installed on the computer, which stops 2015 from installation. Should I uninstall 2017 and try 2015?

First I uninstall vs2017, and next install vs2013, it work for me.

**Comment by cjbj** [comment]
Closing - no activity.
