### ISSUE TITLE
Compilation issues on MacOS High Sierra

### ISSUE THREAD

**Issue by nicolaskruchten** [oracle/node-oracledb#1013]
I'm trying to just install this module on MacOS High Sierra and it's trying and failing to compile from source.

--------

1. What is your Node.js version: use `console.log(process.version)`?  Is it 64-bit or 32-bit: use `console.log(process.arch)`?

```
node --version
v10.6.0
```

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

`npm install oracledb` logged in as a generic user

4. What error(s) you are seeing?

```
nk$ npm install oracledb                                                                                                   ~p/falcon [master]

> oracledb@2.2.0 install /Users/nicolas/plotly/falcon/node_modules/oracledb
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/oracledb/src/njsCommon.o
In file included from ../src/njsCommon.cpp:52:
In file included from ../src/njsCommon.h:57:
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/njsCommon.cpp:52:
In file included from ../src/njsCommon.h:57:
../../nan/nan.h:854:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/njsCommon.cpp:52:
In file included from ../src/njsCommon.h:57:
../../nan/nan.h:869:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/njsCommon.cpp:52:
In file included from ../src/njsCommon.h:57:
../../nan/nan.h:1478:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../src/njsCommon.cpp:212:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
        v8::String::Utf8Value v8str(message->ToString());
                              ^
/Users/nicolas/.node-gyp/10.6.0/include/node/v8.h:2851:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/nicolas/.node-gyp/10.6.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/njsCommon.cpp:560:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
        v8::String::Utf8Value utf8str(jsValue->ToString());
                              ^
/Users/nicolas/.node-gyp/10.6.0/include/node/v8.h:2851:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/nicolas/.node-gyp/10.6.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/njsCommon.cpp:714:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value utf8str(args[index]->ToString());
                          ^
/Users/nicolas/.node-gyp/10.6.0/include/node/v8.h:2851:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/nicolas/.node-gyp/10.6.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/njsCommon.cpp:809:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value utfstr(value->ToString());
                          ^
/Users/nicolas/.node-gyp/10.6.0/include/node/v8.h:2851:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/nicolas/.node-gyp/10.6.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
8 warnings generated.
  CXX(target) Release/obj.target/oracledb/src/njsOracle.o
In file included from ../src/njsOracle.cpp:53:
In file included from ../src/njsOracle.h:56:
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/njsOracle.cpp:53:
In file included from ../src/njsOracle.h:56:
../../nan/nan.h:854:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/njsOracle.cpp:53:
In file included from ../src/njsOracle.h:56:
../../nan/nan.h:869:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/njsOracle.cpp:53:
In file included from ../src/njsOracle.h:56:
../../nan/nan.h:1478:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/nicolas/.node-gyp/10.6.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:138:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:191:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__mutex_base:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:60:9: error: no member named 'clock'
      in the global namespace; did you mean 'flock'?
using ::clock;
      ~~^
/usr/include/sys/fcntl.h:528:5: note: 'flock' declared here
int     flock(int, int);
        ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:138:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:191:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__mutex_base:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:61:9: error: no member named
      'difftime' in the global namespace
using ::difftime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:62:9: error: no member named 'mktime'
      in the global namespace; did you mean 'mktemp'?
using ::mktime;
      ~~^
/usr/include/stdlib.h:221:7: note: 'mktemp' declared here
char    *mktemp(char *);
         ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:138:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:191:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__mutex_base:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:63:9: error: no member named 'time' in
      the global namespace; did you mean 'tie'?
using ::time;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/tuple:1068:1: note: 'tie' declared here
tie(_Tp&... __t) _NOEXCEPT
^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:138:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:191:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__mutex_base:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:65:9: error: no member named 'asctime'
      in the global namespace
using ::asctime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:66:9: error: no member named 'ctime'
      in the global namespace
using ::ctime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:67:9: error: no member named 'gmtime'
      in the global namespace
using ::gmtime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:68:9: error: no member named
      'localtime' in the global namespace
using ::localtime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:70:9: error: no member named
      'strftime' in the global namespace
using ::strftime;
      ~~^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:138:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:191:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__mutex_base:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__threading_support:384:11: error: use of
      undeclared identifier 'nanosleep'
   while (nanosleep(&__ts, &__ts) == -1 && errno == EINTR);
          ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:2231:27: error: member access into
      incomplete type 'tm'
    __get_weekdayname(__tm->tm_wday, __b, __e, __err, __ct);
                          ^
/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:2243:25: error: member access into
      incomplete type 'tm'
    __get_monthname(__tm->tm_mon, __b, __e, __err, __ct);
                        ^
/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:2255:20: error: member access into
      incomplete type 'tm'
    __get_year(__tm->tm_year, __b, __e, __err, __ct);
                   ^
/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:2272:31: error: member access into
      incomplete type 'tm'
        __get_weekdayname(__tm->tm_wday, __b, __e, __err, __ct);
                              ^
/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:2277:29: error: member access into
      incomplete type 'tm'
        __get_monthname(__tm->tm_mon, __b, __e, __err, __ct);
                            ^
/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:2287:23: error: member access into
      incomplete type 'tm'
        __get_day(__tm->tm_mday, __b, __e, __err, __ct);
                      ^
/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:2302:24: error: member access into
      incomplete type 'tm'
        __get_hour(__tm->tm_hour, __b, __e, __err, __ct);
                       ^
/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:2305:27: error: member access into
      incomplete type 'tm'
        __get_12_hour(__tm->tm_hour, __b, __e, __err, __ct);
                          ^
/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
In file included from ../src/njsOracle.cpp:59:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:2308:32: error: member access into
      incomplete type 'tm'
        __get_day_year_num(__tm->tm_yday, __b, __e, __err, __ct);
                               ^
/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 warnings and 20 errors generated.
make: *** [Release/obj.target/oracledb/src/njsOracle.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/nicolas/.nvm/versions/node/v10.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/nicolas/.nvm/versions/node/v10.6.0/bin/node" "/Users/nicolas/.nvm/versions/node/v10.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nicolas/plotly/falcon/node_modules/oracledb
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nicolas/.npm/_logs/2018-11-29T18_55_39_371Z-debug.log
```

5. What OS (and version) is Node.js executing on: use `console.log(process.platform)`?

MacOS High Sierra 10.13.6

6. What is your Oracle client (e.g. Instant Client) version: use `console.log(oracledb.oracleClientVersionString)`?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

```
nk$ ll ~/lib                                                                                                           
total 217016
drwxr-xr-x   18 nicolas  staff   576B 29 Nov 12:48 .
drwxr-xr-x+ 151 nicolas  staff   4.7K 29 Nov 14:01 ..
-rw-r--r--@   1 nicolas  staff   410B 10 Jan  2018 BASIC_LITE_README
-rwxr-xr-x@   1 nicolas  staff   9.8K 10 Jan  2018 adrci
-rwxr-xr-x@   1 nicolas  staff    39K 10 Jan  2018 genezi
lrwxr-xr-x    1 nicolas  staff    20B 10 Jan  2018 libclntsh.dylib -> libclntsh.dylib.12.1
-rwxr-xr-x@   1 nicolas  staff    82M 10 Jan  2018 libclntsh.dylib.12.1
-rwxr-xr-x@   1 nicolas  staff   4.5M 10 Jan  2018 libclntshcore.dylib.12.1
-rwxr-xr-x@   1 nicolas  staff   7.8M 29 Jun  2017 libnnz12.dylib
lrwxr-xr-x    1 nicolas  staff    18B 10 Jan  2018 libocci.dylib -> libocci.dylib.12.1
-rwxr-xr-x@   1 nicolas  staff   1.4M 10 Jan  2018 libocci.dylib.12.1
-rwxr-xr-x@   1 nicolas  staff   6.1M 10 Jan  2018 libociicus.dylib
-rwxr-xr-x@   1 nicolas  staff   148K  8 Aug  2017 libocijdbc12.dylib
-rwxr-xr-x@   1 nicolas  staff   232K  8 Jan  2018 libons.dylib
-rwxr-xr-x@   1 nicolas  staff    83K 10 Jan  2018 liboramysql12.dylib
-rw-r--r--@   1 nicolas  staff   3.8M 13 Dec  2016 ojdbc8.jar
-rwxr-xr-x@   1 nicolas  staff   143K 10 Jan  2018 uidrvci
-rw-r--r--@   1 nicolas  staff    72K 26 Jan  2017 xstreams.jar
```

**Comment by cjbj** [comment]
Quick solution: use node-oracledb 2.3 which has prebuilt binaries for Node 10.  Better still, use node-oracledb 3.0.1 and a later (with all the security fixes) version of Node.js.

Regarding compiling, on High Sierra with XCode 10.1 I can build node-oracledb fine for Node 10.  I just get the misc, expected, deprecation warnings.

**Comment by nicolaskruchten** [comment]
I’m glad it works well on your system but it doesn’t on mine. What can I do/try to get it to compile? Downgrading is not an option I’m interested in at the moment...

Are there any undocumented dependencies or known conflicts for compilation? I just have a fairly vanilla Xcode install.

**Comment by cjbj** [comment]
You'll have to do some digging and experimentation.  I was suggesting _upgrading_, at least to 2.3.

**Comment by cjbj** [comment]
@nicolaskruchten the latest is 3.0.1.

Maybe using something like https://oracle.github.io/node-oracledb/INSTALL.html#manualextraction will help you?  You can pull all the binaries locally and create some tooling to use the correct one(s).

**Comment by cjbj** [comment]
@nicolaskruchten any luck?

**Comment by nicolaskruchten** [comment]
Nope. I still can't successfully install from source, although others in my organization are able to on a Mac. I'm stumped.

I just clone https://github.com/plotly/falcon and `yarn install` and it fails with compilation errors which I'm at a loss to diagnose.

**Comment by cjbj** [comment]
I assume you've tried things like this found via a quick Google: 

> Go into Xcode and remove the project files included in the "Headers" section from the Build phases.

https://stackoverflow.com/questions/26179298/how-to-fix-missing-time-related-no-member-in-global-namespace-errors-on-macosx

**Comment by zcbenz** [comment]
@nicolaskruchten Try checking if `/usr/local/include/time.h` exists on your system, remove it if it exists.

**Comment by nicolaskruchten** [comment]
I’ll take a look, but I don’t love deleting random files like this... why would this file be here in some systems and not others? What else will break if I delete this file? :)

**Comment by nicolaskruchten** [comment]
It’s doesnt surprise me that Homebrew would have installed it but it seems like whatever it was that Homebrew was doing with that file won’t work any more once you delete it :)

**Comment by zcbenz** [comment]
Installing `/usr/local/include/time.h` breaks compilation for almost every C/C++ file, it is a bug of Homebrew for whatever reason.

Unless you are _explicitly_ using Homebrew to install some C/C++ headers (for example libboost) for your own development, it is safe to delete the whole `/usr/local/include` directory.

**Comment by cjbj** [comment]
Closing since this appears identified as a machine configuration issue.
