### ISSUE TITLE
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 10.2.0 (win32, x64)

### ISSUE THREAD

**Issue by riteshku1992** [oracle/node-oracledb#1020]
Cannot load E:\bro_clg\project\node_modules\oracledb\build\Release\oracledb.node
A dynamic link library (DLL) initialization routine failed.
\\?\E:\bro_clg\project\node_modules\oracledb\build\Release\oracledb.node
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

    at Object.<anonymous> (E:\bro_clg\project\node_modules\oracledb\lib\oracledb.js:68:13)
    at Object.<anonymous> (E:\bro_clg\project\node_modules\oracledb\lib\oracledb.js:696:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (E:\bro_clg\project\node_modules\oracledb\index.js:1:173)

**Comment by riteshku1992** [comment]
I am getting this error while I am trying to import oracledb in electronjs however I am successfully able to access the same DB through node web application.

**Comment by cjbj** [comment]
Review previous issues about Electron.  It had some known quirks about having a different version of V8 than Node.js uses. If you are running the Electron app on a different machine, make sure it does have all the pre-requisites such as the VC Redistributable.

PS the [issue template](https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md) says: "Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code"  Use this when you post issues.

**Comment by riteshku1992** [comment]
Thanks for replay. I am running the node V10 and after setting up the path variable, I am getting below error
![image](https://user-images.githubusercontent.com/28960054/49701025-98e8c980-fc0c-11e8-9c1b-959073498f13.png)

it is possible to have a webex meeting to resolve this issue, this will help me allot

**Comment by cjbj** [comment]
Just to check, did you compile the module for Windows ia32 (as shown in the screenshot)?  We only release a pre-built binary for Windows x64.

**Comment by riteshku1992** [comment]
[image: image.png]

I am getting above issue after setting the parameters, could you please
give me some time which we can discuss over webex meeting.

Regards,
Ritesh

**Comment by cjbj** [comment]
Pro tip: cut & paste output, or use a [gist](https://gist.github.com/) for large output.  Your screen shot above isn't displaying.  I've seen some GitHub users muttering against using screen shots and I agree - it's painful to search or cut/paste when replying.

As a non-Windows, non-Electron user I can only give general advice: make sure you have node-oracledb binaries that match the target operating system, and also that match the Node internal binary interface 'ABI' number used by Electron.

We have a great 'Office Hours' system where people can ask questions directly to us.  See https://devgym.oracle.com/pls/apex/dg/office_hours/727

**Comment by cjbj** [comment]
Closing - no activity.
