### ISSUE TITLE
oracledb.maxRow setting not kicking in

### ISSUE THREAD

**Issue by chezdrz** [oracle/node-oracledb#1074]
**Problem** 
The return dataset json is probably exceeding the max number of rows so it ends up with an error 

Sample 
The end of the Json file looks like this 
…. 
 { USER_NAME: 'xxx',
    R_val: '22',
    START_DT: '21-jan-08',
    END_DT: null },
  **... 268 more items ]**

In my .js file I tried the following 

Option #1 if I try this setting 
```
var oracledb = require('oracledb');
**oracledb.maxRows = 1000;**
```
The oracledb.maxRows does not seem to have any effect 

Option #2 If I try to set maxrows within the retrieval i.e. 

```
     connection.execute(
      // The statement to execute
      `SELECT xyz… from xxx where xxx.. `,

      [args1],
     { outFormat: oracledb.OBJECT },
     { maxRows: 1000}, 
    
 function(err, result) {
        if (err) {
          console.error(err.message);
          doRelease(connection);
          return;
        }
```

Here it errors our with 
Error: NJS-009: invalid number of parameters
    at Object.assert (/orpppmd1/ppmapp/ohs11119/nodejs/node_modules/oracledb/lib/util.js:159:11)
    at Connection.execute (/orpppmd1/ppmapp/ohs11119/nodejs/node_modules/oracledb/lib/connection.js:130:12)
    at Connection.execute (/orpppmd1/ppmapp/ohs11119/nodejs/node_modules/oracledb/lib/util.js:178:19)
    at /orpppmd1/ppmapp/ohs11119/websrvr/instances/instance1/config/OHS/ohs1/cgi-bin/cemli/getresp.js:31:16
    at /orpppmd1/ppmapp/ohs11119/nodejs/node_modules/oracledb/lib/oracledb.js:255:7

**Comment by dmcghan** [comment]
@chezdrz `maxRows` should work with option 1. But your first example showed 269 rows returned, no? If so, setting the limit to 1000 would not have any effect on the result (try setting it to a value less than 269).

Option 2 is not written correctly. `connection.execute` [takes up to four parameters](https://oracle.github.io/node-oracledb/doc/api.html#-426-connectionexecute) but you are passing five. Your third and fourth parameters should be consolidated to one object with two properties. As with option one, the `maxRows` will have to be less than the entire result set to see the effect.

**Comment by chezdrz** [comment]
@dmcghan 
Thanks for responding here. 

If I pick Option 2 , I now have corrected the parameter error
  connection.execute(
      // The statement to execute
      `SELECT 
 xyz from xyz where xyz :something 
`,

      [args1],
     { outFormat: oracledb.OBJECT ,
       maxRows: 1000 }, 

      function(err, result) {
        if (err) {
          console.error(err.message);
          doRelease(connection);
          return;
        }
        //console.log(result.metaData); // [ { name: 'DEPARTMENT_ID' }, { name: 'DEPARTMENT_NAME' } ]
        console.log(result.rows);     // [ [ 180, 'Construction' ] ]
        //console.log('XXXX' + result.rows[0].object_name);
		doRelease(connection);
      });

Now the actual SQL is supposed to return 358 rows. 
But the .js page bombs our in error because the malformed ending of the .json 
i.e. 
 { USER_NAME: '502675826',
    RESPONSIBILITY_NAME: 'GEOG Global iSourcing Super User',
    START_DT: '11-jan-13',
    END_DT: null },
  ... 268 more items ]

  How do I resolve this such that I do not get an incomplete JSON formed 
  with this "..268 more items text" which breaks the syntax. 

  My understanding of maxRows : 1000 is 
  If the return dataset has > 1000 rows then it should return the top 1000 rows, and close the JSON structure properly 
  Rather than priting this ...268 more items.

**Comment by chezdrz** [comment]
Option #3 
I did some more reading and implemented the Resultset solution as explained here 
https://github.com/oracle/node-oracledb/blob/master/doc/api.md#resultsetclass

so in 
  fetchRowsFromRS(connection, resultSet, numRows);
( I am setting the numRows to 100, so the resultset pulls 100 rows at a time. )

But here is the problem. 
the .JSON also closes and opens with every 100 rows , which again breaks the rest of my code logic. 

i.e. 
[ { ROWNUM: 1,
    xxxxx },
  { ROWNUM: 2,
    xxxl },
  etc.. tilll 
  { ROWNUM: 100,
    xxxl }
] // Then this Square Bracket closing comes in the way which breaks my code. 
[ { ROWNUM: 101,
    xxxxx },
  { ROWNUM: 102,
    xxxl },
   etc.. 
 ]

**Comment by dmcghan** [comment]
@chezdrz Please see how to [correctly display code in markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code).

> But the .js page bombs our in error because the malformed ending of the .json

I'm not sure what you mean here. You're showing some code that gets data but nothing that creates a .js page. Keep in mind that the driver, as you're using it, doesn't fetch JSON - it fetches the rows as JavaScript objects. Try running the rows through a `JSON.stringify` call.

Things are a little more difficult if you're using a Result Set or Query Stream. See this issue for a description of the problem and a solution: https://github.com/oracle/node-oracledb/issues/908

**Comment by chezdrz** [comment]
Thanks will take a look at it. 
For now as a temp workaround I am using a shell script that trims out the following in the output.
Intermediate "[" removed
Intermediate "]" replaced with ","

**Comment by cjbj** [comment]
Closing - no activity.
