### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by oculushut** [oracle/node-oracledb#111]
Hi there,

Am on Linux and need to connect to a remote database.

I downloaded oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm.

Ran the following as root:

```
rpm -lvh oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
```

This seemed to install OK.

I then went to my project's folder and ran:

```
npm install oracledb
```

I get the following errors:

```
\
> oracledb@0.6.0 install /home/xxx/xxx/node_modules/oracledb
> node-gyp rebuild

make: Entering directory `/home/xxxx/xxxx/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
In file included from ../src/dpi/include/dpiConn.h:29,
                 from ../src/dpi/include/dpiPool.h:33,
                 from ../src/dpi/include/dpiEnv.h:36,
                 from ../src/dpi/include/dpi.h:35,
                 from ../src/njs/src/njsOracle.h:63,
                 from ../src/njs/src/njsOracle.cpp:53:
../src/dpi/include/dpiStmt.h:29:18: warning: oci.h: No such file or directory
../src/dpi/include/dpiStmt.h:34:2: error: #error Oracle 11.2 or later client libraries are required for building
In file included from ../src/dpi/include/dpiConn.h:29,
                 from ../src/dpi/include/dpiPool.h:33,
                 from ../src/dpi/include/dpiEnv.h:36,
                 from ../src/dpi/include/dpi.h:35,
                 from ../src/njs/src/njsOracle.h:63,
                 from ../src/njs/src/njsOracle.cpp:53:
../src/dpi/include/dpiStmt.h:135: error: ‘sb4’ has not been declared
../src/dpi/include/dpiStmt.h:136: error: ‘dvoid’ has not been declared
../src/dpi/include/dpiStmt.h:137: error: ‘dvoid’ has not been declared
../src/dpi/include/dpiStmt.h:153: error: ‘sb4’ does not name a type
../src/dpi/include/dpiStmt.h:159: error: ‘sb4’ has not been declared
../src/dpi/include/dpiStmt.h:159: error: ‘ub2’ has not been declared
../src/dpi/include/dpiStmt.h:163: error: ‘sb4’ has not been declared
../src/dpi/include/dpiStmt.h:164: error: ‘ub2’ has not been declared
../src/dpi/include/dpiStmt.h:170: error: ‘sb4’ has not been declared
../src/dpi/include/dpiStmt.h:170: error: ‘ub2’ has not been declared
../src/dpi/include/dpiStmt.h:178: error: ISO C++ forbids declaration of ‘OCIError’ with no type
../src/dpi/include/dpiStmt.h:178: error: ‘OCIError’ declared as a ‘virtual’ field
../src/dpi/include/dpiStmt.h:178: error: expected ‘;’ before ‘*’ token
In file included from ../src/dpi/include/dpi.h:35,
                 from ../src/njs/src/njsOracle.h:63,
                 from ../src/njs/src/njsOracle.cpp:53:
../src/dpi/include/dpiEnv.h:99: error: ‘getDateTimeArray’ declared as a ‘virtual’ field
../src/dpi/include/dpiEnv.h:99: error: expected ‘;’ before ‘(’ token
In file included from ../src/njs/src/njsOracle.cpp:54:
../src/njs/src/njsConnection.h:74: error: ISO C++ forbids declaration of ‘ub2’ with no type
../src/njs/src/njsConnection.h:74: error: expected ‘;’ before ‘*’ token
../src/njs/src/njsConnection.h:76: error: ‘sb4’ does not name a type
../src/njs/src/njsConnection.h: In constructor ‘Bind::Bind()’:
../src/njs/src/njsConnection.h:82: error: class ‘Bind’ does not have any field named ‘len’
../src/njs/src/njsConnection.h:83: error: class ‘Bind’ does not have any field named ‘maxSize’
../src/njs/src/njsConnection.h: At global scope:
../src/njs/src/njsConnection.h:94: error: ‘sb4’ does not name a type
../src/njs/src/njsConnection.h:97: error: ISO C++ forbids declaration of ‘ub2’ with no type
../src/njs/src/njsConnection.h:97: error: expected ‘;’ before ‘*’ token
../src/njs/src/njsConnection.h: In constructor ‘Define::Define()’:
../src/njs/src/njsConnection.h:101: error: class ‘Define’ does not have any field named ‘maxSize’
../src/njs/src/njsConnection.h:102: error: class ‘Define’ does not have any field named ‘len’
../src/njs/src/njsConnection.h: At global scope:
../src/njs/src/njsConnection.h:116: error: ‘sb4’ does not name a type
../src/njs/src/njsConnection.h: In constructor ‘eBaton::eBaton()’:
../src/njs/src/njsConnection.h:132: error: class ‘eBaton’ does not have any field named ‘rowsAffected’
../src/njs/src/njsConnection.h: In destructor ‘eBaton::~eBaton()’:
../src/njs/src/njsConnection.h:160: error: ‘struct Bind’ has no member named ‘len’
../src/njs/src/njsConnection.h:162: error: ‘struct Bind’ has no member named ‘len’
../src/njs/src/njsConnection.h:179: error: ‘struct Define’ has no member named ‘len’
../src/njs/src/njsConnection.h: At global scope:
../src/njs/src/njsConnection.h:274: error: ‘ub2’ has not been declared
../src/njs/src/njsConnection.h:275: error: ‘sb4’ has not been declared
../src/njs/src/njsConnection.h:285: error: ‘sb4’ has not been declared
../src/njs/src/njsConnection.h:288: error: ‘dvoid’ has not been declared
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
make: Leaving directory `/home/xxx/xxx/node_modules/oracledb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/xxx/xxx/node_modules/oracledb
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! oracledb@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@0.6.0 install script.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "oracledb"
npm ERR! cwd /home/xxx/xxx
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

Any tips?

**Comment by alexsantos** [comment]
Did you install oracle-instantclient12.1-devel?

**Comment by oculushut** [comment]
So... I followed link here (https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instrpm):

![image](https://cloud.githubusercontent.com/assets/10579045/8116354/919335e4-1079-11e5-9f7f-8aa92b18ee68.png)

I downloaded this (http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html):

![image](https://cloud.githubusercontent.com/assets/10579045/8116292/271f100c-1079-11e5-8ab8-0b0a334b1e23.png)

And I ran this command:

```
rpm -lvh oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
```

This seemed to install fine.

Is that what you mean?

**Comment by cjbj** [comment]
Your eye seems to have skipped over the line:
rpm -ivh oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm
in step 2.2 of https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instrpm
