### ISSUE TITLE
Error: Invalid argument on OracleDB.getConnection(params.source.dbConfig)

### ISSUE THREAD

**Issue by Louis-Riel** [oracle/node-oracledb#1131]
I have a docker running node V12 trying to get oracledb V4.0.0 to function on a docker in RHEL Maipo.

I managed to get the instaclient basic and sqlplus deployed to the docker, with the library and path variables set.

I could not get the library working initially, so I resolved myself to the following:

invoke sqlplus, from node, with the directives to suppress the fluff, and then put that through sone csvtojson contraption. It feels so wrong.... 

It does confirm though, that the insta client is all and well inside the docker and the node.

When I try to use the oracledb library, I get an error when oracledb.js invokes the natiive library, and I get an  (Error: Invalid argument).

The Getup----

Here is the Dockerfile responsible for this debacle:
```dockerfile
FROM node:11

ARG UID
ARG GID

ENV http_proxy=http://172.17.0.1:8118/
ENV https_proxy=http://172.17.0.1:8118/

RUN apt-get update
RUN apt-get install -y libaio1 netcat

EXPOSE 8009

RUN groupadd -g ${GID} docker
RUN useradd --create-home --shell /bin/false -u ${UID} -g ${GID} differ

ENV HOME /home/differ

RUN mkdir $HOME/diffconfabulator
RUN mkdir $HOME/diffconfabulator/result

WORKDIR $HOME/diffconfabulator
COPY package.json $HOME/diffconfabulator

RUN export && yarn config set proxy $http_proxy && yarn config list && yarn

COPY . $HOME/diffconfabulator

WORKDIR $HOME/diffconfabulator/oraclient

RUN pwd && ls -l
RUN unzip instantclient-basic-linux.x64-19.3.0.0.0dbru.zip
RUN unzip instantclient-sqlplus-linux.x64-19.3.0.0.0dbru.zip

ENV LD_LIBRARY_PATH=$HOME/diffconfabulator/oraclient/instantclient_19_3:$LD_LIBRARY_PATH
ENV PATH=$HOME/diffconfabulator/oraclient/instantclient_19_3:$PATH

WORKDIR $HOME/diffconfabulator

RUN chown -R differ $HOME/diffconfabulator
USER differ
ENTRYPOINT node -r esm .
```
Now with that, node can invoke the sqlplus bin, connect to a db, run the query and harvest the results, all is well with the libs.

Here is that piece of code, that works:
```javascript
            temp.open("params.source.query", (err, tmpFile) => {
                if (err) reject(err);
                var cmd = params.source.query ? "echo \"SET PAGESIZE 0\nSET LINESIZE 9999\nSET FEEDBACK OFF\nSET HEAD ON\nSET NEWPAGE 0\nSET SPACE 0\nSET ECHO OFF\nSET VERIFY OFF\nSET TERMOUT OFF\nSET SHOWMODE OFF\nwhenever sqlerror exit sql.sqlcode;\n" + params.source.query + ";\"\
                     | sqlplus -S -M 'csv on' " + params.source.dbConfig.user + "/" + params.source.dbConfig.password + "@" + params.source.dbConfig.connectString + " | egrep -v '^$' > " + tmpFile.path : "echo \"SET PAGESIZE 0\nSET LINESIZE 9999\nSET FEEDBACK OFF\nSET HEAD ON\nSET NEWPAGE 0\nSET SPACE 0\nSET ECHO OFF\nSET VERIFY OFF\nSET TERMOUT OFF\nSET SHOWMODE OFF\nwhenever sqlerror exit sql.sqlcode;\n" + params.source.query + ";\"\
                     | sqlplus -S -M 'csv on' " + params.source.dbConfig.user + "/" + params.source.dbConfig.password + "@" + params.source.dbConfig.connectString + " <" + params.source.sqlfile + " | egrep -v '^$' > " + tmpFile.path;
                proc.exec(cmd).then((res) => {
                    csvtojson().fromFile(tmpFile.path)
                        .then((json) => { resolve(json); })
                        .catch((err) => {reject(err)})
                        .finally(() => {
                            fs.exists(tmpFile.path, (exists) => {
                                if (exists) {
                                    fs.unlink(tmpFile.path,(err)=>{reject(err)});
                                }
                            });
                        });
                }).catch((err) => {err.stderr == "" && err.code == 1 ? resolve([]) : reject(err);});
            });
```
Althgough unfortunate, this code works.
If on the other hand I try a more proper
```javascript
            console.log("Connecting to db");
            console.log(params.source.dbConfig);
            console.log(process.env);
            OracleDB.getConnection(params.source.dbConfig).then((conn) => {
                console.log("Running %s",params.source.query);
                conn.execute(params.source.query).then((res)=>{
                    console.log(res);
                    resolve(res);
                }).catch((err)=>{reject(err)});
            }).catch((err)=>{reject(err)});
```
It fails on the getConnection line.
```
difftool             | Connecting to db
difftool             | { connectString: 'thesuperduperserver:1526/theinstance.thedomain.com',
difftool             |   password: '*********************************',
difftool             |   user: '********************************' }
difftool             | { NODE_VERSION: '11.14.0',
difftool             |   HOSTNAME: '70661cd83801',
difftool             |   YARN_VERSION: '1.15.2',
difftool             |   LD_LIBRARY_PATH:
difftool             |    '/home/differ/diffconfabulator/oraclient/instantclient_19_3:',
difftool             |   HOME: '/home/differ',
difftool             |   https_proxy: 'http://172.17.0.1:8118/',
difftool             |   http_proxy: 'http://172.17.0.1:8118/',
difftool             |   PATH:
difftool             |    '/home/differ/diffconfabulator/oraclient/instantclient_19_3:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
difftool             |   PWD: '/home/differ/diffconfabulator' }
difftool             | Error: Invalid argument
difftool             |     at Proxy.getConnection (/home/differ/diffconfabulator/node_modules/oracledb/lib/oracledb.js:270:10)
difftool             |     at /home/differ/diffconfabulator/node_modules/oracledb/lib/util.js:180:16
difftool             |     at new Promise (<anonymous>)
difftool             |     at Proxy.<anonymous> (/home/differ/diffconfabulator/node_modules/oracledb/lib/util.js:168:14)
difftool             |     at /home/differ/diffconfabulator/lib/extractors/oradb.js:16:22
difftool             |     at new Promise (<anonymous>)
difftool             |     at Proxy.require.module.exports.start (/home/differ/diffconfabulator/lib/extractors/oradb.js:11:12)
difftool             |     at import.then (/home/differ/diffconfabulator/lib/operations/extract.js:11:21)
difftool             |     at runNextTicks (internal/process/task_queues.js:52:5)
difftool             |     at processImmediate (internal/timers.js:416:9)
difftool             |     at process.topLevelDomainCallback (domain.js:136:23)
```
The code @ line 270 in oracledb.js is 
```javascript
  } else {
    self._getConnection(connAttrs, function(err, connInst) {
      if (err) {
```
I added some console.log in there, just before the _getConnection, to confirm than the connAttrs was proper and unaltered, it was. This _getConnection is the native call, can't console.log into there.

For reference, here is the whole piece of code pieced together:
```javascript
"use strict";
/*jshint esversion: 6 */
import OracleDB from 'oracledb';
import proc from 'child-process-promise';
import csvtojson from 'csvtojson';
import temp from 'temp';
import fs from 'fs';
import util from 'util'

module.exports.start = function (params, instance) {
    return new Promise(function (resolve, reject) {
        if ((params.source.query || params.source.sqlfile) && params.source.dbConfig) {
            console.log("Connecting to db");
            console.log(params.source.dbConfig);
            console.log(process.env);
            OracleDB.getConnection(params.source.dbConfig).then((conn) => {
                console.log("Running %s",params.source.query);
                conn.execute(params.source.query).then((res)=>{
                    console.log(res);
                    resolve(res);
                }).catch((err)=>{reject(err)});
            }).catch((err)=>{reject(err)});

            temp.open("params.source.query", (err, tmpFile) => {
                if (err) reject(err);
                var cmd = params.source.query ? "echo \"SET PAGESIZE 0\nSET LINESIZE 9999\nSET FEEDBACK OFF\nSET HEAD ON\nSET NEWPAGE 0\nSET SPACE 0\nSET ECHO OFF\nSET VERIFY OFF\nSET TERMOUT OFF\nSET SHOWMODE OFF\nwhenever sqlerror exit sql.sqlcode;\n" + params.source.query + ";\"\
                     | sqlplus -S -M 'csv on' " + params.source.dbConfig.user + "/" + params.source.dbConfig.password + "@" + params.source.dbConfig.connectString + " | egrep -v '^$' > " + tmpFile.path : "echo \"SET PAGESIZE 0\nSET LINESIZE 9999\nSET FEEDBACK OFF\nSET HEAD ON\nSET NEWPAGE 0\nSET SPACE 0\nSET ECHO OFF\nSET VERIFY OFF\nSET TERMOUT OFF\nSET SHOWMODE OFF\nwhenever sqlerror exit sql.sqlcode;\n" + params.source.query + ";\"\
                     | sqlplus -S -M 'csv on' " + params.source.dbConfig.user + "/" + params.source.dbConfig.password + "@" + params.source.dbConfig.connectString + " <" + params.source.sqlfile + " | egrep -v '^$' > " + tmpFile.path;
                proc.exec(cmd).then((res) => {
                    csvtojson().fromFile(tmpFile.path)
                        .then((json) => { resolve(json); })
                        .catch((err) => {reject(err)})
                        .finally(() => {
                            fs.exists(tmpFile.path, (exists) => {
                                if (exists) {
                                    fs.unlink(tmpFile.path,(err)=>{reject(err)});
                                }
                            });
                        });
                }).catch((err) => {err.stderr == "" && err.code == 1 ? resolve([]) : reject(err);});
            });
        } else {reject({ message: "Missing db dbconfig or query", errorCode: 500, params: params });}
    });
}
```
Now I realise that I should probably be using some sort of connection pool getup, but that is a future me problem. Current me is only tasked with getting this to work. So, what the future internet technologists, what am I doing wrong?!?!

**Comment by cjbj** [comment]
I don't see an NJS error about the argument being invalid?

I suggest starting simple with the setup.  Look at https://blogs.oracle.com/opal/dockerfiles-for-node-oracledb-are-easy-and-simple and change the index.js file to do something like https://github.com/oracle/node-oracledb/blob/master/examples/example.js

**Comment by dmcghan** [comment]
@Louis-Riel I was able to reproduce. In the future please provide a reproducible test case so we don't have to do it for you.

The problem is coming from your dependency on `esm`.

I recommend creating a reproducible test case for the `esm` team and submitting an issue there. To help you with that, here are the files I ended up with:

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "dependencies": {
    "esm": "^3.2.25",
    "oracledb": "^4.0.0"
  }
}
```

index.js
```javascript
"use strict";

import OracleDB from 'oracledb';
import dbConfig from './dbConfig.js';

function start() {
    return new Promise(function (resolve, reject) {
        console.log("Connecting to db");
        console.log(dbConfig);
        console.log(process.env);
        OracleDB.getConnection(dbConfig)
          .then((conn) => {resolve()})
          .catch((err)=>{reject(err)});
    });
}

start()
  .then(() => {
    console.log('cool');
  })
  .catch((err) => {
    console.log('not cool', err);
  });
```

Dockerfile
```dockerfile
FROM node:11

RUN apt-get update
RUN apt-get install -y libaio1 netcat

RUN groupadd docker
RUN useradd --create-home --shell /bin/false -g docker differ

ENV HOME /home/differ

RUN mkdir $HOME/diffconfabulator
RUN mkdir $HOME/diffconfabulator/result

WORKDIR $HOME/diffconfabulator
COPY package.json $HOME/diffconfabulator

RUN export && yarn config list && yarn

COPY . $HOME/diffconfabulator

WORKDIR $HOME/diffconfabulator/oraclient

RUN pwd && ls -l
RUN unzip instantclient-basic-linux.x64-19.3.0.0.0dbru.zip

ENV LD_LIBRARY_PATH=$HOME/diffconfabulator/oraclient/instantclient_19_3:$LD_LIBRARY_PATH
ENV PATH=$HOME/diffconfabulator/oraclient/instantclient_19_3:$PATH

WORKDIR $HOME/diffconfabulator

RUN chown -R differ $HOME/diffconfabulator
USER differ
ENTRYPOINT node -r esm .
#ENTRYPOINT node .
```

**Comment by Louis-Riel** [comment]
Thank you @dmcghan for the help and direction. I will send that along their way. I was hoping I was doing it completely wrong or forgot an obvious thing, and someone would say, put an await, or something. That's why I had flagged my thing as a question. I will flip this over to the esm team, with a full test case, rather than a question. I'll see what they say. 

I got a feeling that since I was able to put a console.log line just before the call to the bins, in the oracledb.js, that would indicate that es6 and whatnot has worked fine, the failure seems to occurs on the oracle side. Will post back.

**Comment by Louis-Riel** [comment]
@cjbj The NJS validations occur at the beginning of the getConnection function. I get up to line 270 in oracledb.js, which is way past the parameter validations. I fudged the input parameters, as a test, and did get the NJS errors, so my params passed the parameter validations. 

Also, I had added a console.log(connAttrs) line to the oracledb.js, just before line 270, it executed and it showed that it had the proper values. So all the JS part seems to works in oracledb.js, until it calls _getConnection({options}), which then falls outside of the oracledb node library.

**Comment by cjbj** [comment]
What if you hardcode values in the getConnection() call?

**Comment by Louis-Riel** [comment]
Same problem. Run an Oracle db docker container,by running this after a ```docker login``` run a 
```docker run -d -p 8080:8080 -p 1521:1521 --name OracleDB store/oracle/database-enterprise:12.2.0.1-slim```

 Then some login, a table and some irrelevant data
 ```docker exec -it OracleDB bash -c "source /home/oracle/.bashrc; sqlplus /nolog"```

```sql
connect sys as sysdba;
alter session set "_ORACLE_SCRIPT"=true;
create user dummy identified by dummy;
GRANT CONNECT, RESOURCE, DBA TO dummy;
create table some_data(some_column varchar(30),some_other_columns varchar(30));
insert into some_data values ('some','good data');
insert into some_data values ('more','good data');
insert into some_data values ('some','crap data');
insert into some_data values ('some','otherwise well intented data');
commit
exit
```

I patched the oracldb.js to add the log line before the _getconnection
```patch
@@ -267,6 +267,7 @@
 
     pool.getConnection(connAttrs, getConnectionCb);
   } else {
+    console.log("The args %s",JSON.stringify(connAttrs));
     self._getConnection(connAttrs, function(err, connInst) {
       if (err) {
         if (err.message.match(/DPI-1047/)) {
```

and the new js file
```javascript
"use strict";
/*jshint esversion: 6 */
import OracleDB from 'oracledb';
import proc from 'child-process-promise';
import csvtojson from 'csvtojson';
import temp from 'temp';
import fs from 'fs';
import util from 'util'

module.exports.start = function (params, instance) {
    return new Promise(function (resolve, reject) {
        if ((params.source.query || params.source.sqlfile) && params.source.dbConfig) {
            console.log("Connecting to db");
            console.log(process.env);
            OracleDB.getConnection({ connectString: 'localhost:1521/ORCLCDB.localdomain',
                                     password: 'dummy',
                                     user: 'dummy' }).then((conn) => {
                console.log("Running %s",params.source.query);
                conn.execute(params.source.query).then((res)=>{
                    console.log(res);
                    resolve(res);
                }).catch((err)=>{reject(err)});
            }).catch((err)=>{reject(err)});
        } else {reject({ message: "Missing db dbconfig or query", errorCode: 500, params: params });}
    });
}
```
and twaeked Dockerfile
```dockerfile
FROM node:11

ARG UID
ARG GID

#ENV http_proxy=http://172.17.0.1:8118/
#ENV https_proxy=http://172.17.0.1:8118/

RUN apt-get update
RUN apt-get install -y libaio1 netcat

EXPOSE 8009

RUN groupadd -g ${GID} docker
RUN useradd --create-home --shell /bin/false -u ${UID} -g ${GID} differ

ENV HOME /home/differ

RUN mkdir $HOME/diffconfabulator
RUN mkdir $HOME/diffconfabulator/result

WORKDIR $HOME/diffconfabulator
COPY package.json $HOME/diffconfabulator

#RUN export && yarn config set proxy $http_proxy && yarn config list && yarn
RUN export && yarn

COPY . $HOME/diffconfabulator

WORKDIR $HOME/diffconfabulator/oraclient

RUN pwd && ls -l
RUN unzip instantclient-basic-linux.x64-19.3.0.0.0dbru.zip
RUN unzip instantclient-sqlplus-linux.x64-19.3.0.0.0dbru.zip

ENV LD_LIBRARY_PATH=$HOME/diffconfabulator/oraclient/instantclient_19_3:$LD_LIBRARY_PATH
ENV PATH=$HOME/diffconfabulator/oraclient/instantclient_19_3:$PATH

#RUN export && yarn config list && yarn
WORKDIR $HOME/diffconfabulator
RUN patch ./node_modules/csvtojson/v2/Converter.js ./csvtojson.patch
RUN patch ./node_modules/oracledb/lib/oracledb.js ./oracledb_js.patch

RUN chown -R differ $HOME/diffconfabulator
USER differ
ENTRYPOINT node -r esm .
```
I get the same problem. These docker containers (the oracle db and the one hosting this code) are running on an Arch linux. I had initially reproduced this problem on the docker running on RHEL. Here is the output.

```text
difftool             | Connecting to db
difftool             | { NODE_VERSION: '11.15.0',
difftool             |   HOSTNAME: '31da8d386a19',
difftool             |   YARN_VERSION: '1.15.2',
difftool             |   LD_LIBRARY_PATH:
difftool             |    '/home/differ/diffconfabulator/oraclient/instantclient_19_3:',
difftool             |   HOME: '/home/differ',
difftool             |   PATH:
difftool             |    '/home/differ/diffconfabulator/oraclient/instantclient_19_3:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
difftool             |   PWD: '/home/differ/diffconfabulator' }
difftool             | The args {"connectString":"localhost:1521/ORCLCDB.localdomain","password":"dummy","user":"dummy"}
difftool             | Error: Invalid argument
difftool             |     at Proxy.getConnection (/home/differ/diffconfabulator/node_modules/oracledb/lib/oracledb.js:271:10)
difftool             |     at /home/differ/diffconfabulator/node_modules/oracledb/lib/util.js:180:16
difftool             |     at new Promise (<anonymous>)
difftool             |     at Proxy.<anonymous> (/home/differ/diffconfabulator/node_modules/oracledb/lib/util.js:168:14)
difftool             |     at /home/differ/diffconfabulator/lib/extractors/oradb.js:15:22
difftool             |     at new Promise (<anonymous>)
difftool             |     at Proxy.require.module.exports.start (/home/differ/diffconfabulator/lib/extractors/oradb.js:11:12)
difftool             |     at import.then (/home/differ/diffconfabulator/lib/operations/extract.js:11:21)
```

**Comment by dmcghan** [comment]
@Louis-Riel Please see [my previous comment](https://github.com/oracle/node-oracledb/issues/1131#issuecomment-516222041).

**Comment by Louis-Riel** [comment]
Yeah, missing the http server part. Stubbing that out and I will post it. All my tests were done as part of a bigger tool. Crap. And the package.json. Juggling all them balls you know.

I'll sand up a git soon.

**Comment by Louis-Riel** [comment]
@dmcghan was right, it's the esm module. If I run this as ```node --experimental-modules  ./index.js```, it works.
To repro, if any are interrested, clone 
```https://github.com/Louis-Riel/oradbesm.git```
To see the working version, get the without_esm branch to see it go.
To repoduce the problem, 

Run an Oracle db docker container,by running this after a ```docker login``` run a 
```docker run -d -p 8088:8080 -p 1521:1521 --name OracleDB store/oracle/database-enterprise:12.2.0.1-slim```

 Then some login, a table and some irrelevant data
 ```docker exec -it OracleDB bash -c "source /home/oracle/.bashrc; sqlplus /nolog"```

```sql
connect sys as sysdba;
alter session set "_ORACLE_SCRIPT"=true;
create user dummy identified by dummy;
GRANT CONNECT, RESOURCE, DBA TO dummy;
connect dummy/dummy
create table some_data(some_column varchar(30),some_other_columns varchar(30));
insert into some_data values ('some','good data');
insert into some_data values ('more','good data');
insert into some_data values ('some','crap data');
insert into some_data values ('some','otherwise well intented data');
commit
exit
```

I patched the oracldb.js to add the log line before the _getconnection
```patch
@@ -267,6 +267,7 @@
 
     pool.getConnection(connAttrs, getConnectionCb);
   } else {
+    console.log("The args %s",JSON.stringify(connAttrs));
     self._getConnection(connAttrs, function(err, connInst) {
       if (err) {
         if (err.message.match(/DPI-1047/)) {
```

#Build and spin-up the docker container
- Clone this repo
- run ```mkdir oraclient```
- Get a copy of instantclient-basic-linux.x64-19.3.0.0.0dbru.zip and instantclient-sqlplus-linux.x64-19.3.0.0.0dbru.zip and put those in the ```oraclient```  folder
- run ```docker-compose build && docker-compose up```
- run on a separate session to that server, run ```bash herebedragons.sh```

you should expect to see

```text
errorchech           | Server listening on port:8009
errorchech           | Server running
errorchech           | running  "nothin"
errorchech           | Connecting to db
errorchech           | { NODE_VERSION: '11.15.0',
errorchech           |   HOSTNAME: '591e59f89f86',
errorchech           |   YARN_VERSION: '1.15.2',
errorchech           |   LD_LIBRARY_PATH:
errorchech           |    '/home/differ/diffconfabulator/oraclient/instantclient_19_3:',
errorchech           |   HOME: '/home/differ',
errorchech           |   PATH:
errorchech           |    '/home/differ/diffconfabulator/oraclient/instantclient_19_3:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
errorchech           |   PWD: '/home/differ/diffconfabulator' }
errorchech           | The args {"connectString":"localhost:1521/ORCLCDB.localdomain","password":"dummy","user":"dummy"}
errorchech           | Error: Invalid argument
errorchech           |     at Proxy.getConnection (/home/differ/diffconfabulator/node_modules/oracledb/lib/oracledb.js:271:10)
errorchech           |     at /home/differ/diffconfabulator/node_modules/oracledb/lib/util.js:180:16
errorchech           |     at new Promise (<anonymous>)
errorchech           |     at Proxy.<anonymous> (/home/differ/diffconfabulator/node_modules/oracledb/lib/util.js:168:14)
errorchech           |     at /home/differ/diffconfabulator/oradb.js:9:18
errorchech           |     at new Promise (<anonymous>)
errorchech           |     at Proxy.require.module.exports.start (/home/differ/diffconfabulator/oradb.js:6:12)
errorchech           |     at import.then (/home/differ/diffconfabulator/index.js:85:21)
```


Thanks, Louis.
