### ISSUE TITLE
TNS Connection closed - random

### ISSUE THREAD

**Issue by jacopocappelli1989** [oracle/node-oracledb#1214]
On Connection Pool configuration I receive TNS Connection Closed error with random.

In db.js I do this:
```
oracledb.createPool({
                user: configDB.USER,
                password: config.DB.PASSWORD,
                connectString: config.DB.CONNECT_STRING
            },
            function (err, pool) {
                if (err) {
                    console.error(err.message);
                }
                exports.pool_db = pool;
         });
```
In all Express routing file:
```
router.post('/', function(req, res, next) {
    db.pool_db.getConnection(function (err, connection) {
        if (err) {
            console.error(err.message);
            return;
        }
       .....
    });
});
```

Node: v9.11.2
node-oracledb: oracledb@2.3.0
Oracle Client: 12.2 64bit
Oracle Server: AWS RDS 12.1
Linux Ubuntu Xenial

**Comment by jacopocappelli1989** [comment]
After upgrading to:
Node: v12.16.1
node-oracledb: oracledb@4.2.0

Same issue

**Comment by cjbj** [comment]
What exact errors are shown and by what node-oracledb function?  Define random in more detail.

**Comment by jacopocappelli1989** [comment]
<img width="356" alt="Schermata 2020-02-25 alle 14 47 42" src="https://user-images.githubusercontent.com/5347335/75252870-c99b2b80-57dd-11ea-8cd5-5f158deb6e89.png">

I have this exact errors

**Comment by cjbj** [comment]
Is your firewall disconnecting you?  Search the [doc](https://oracle.github.io/node-oracledb/doc/api.html) for 'firewall'.

You haven't given enough background info about the scenarios this occurs in.

PS.  Please cut & paste instead of putting screenshots. Thanks!

**Comment by jacopocappelli1989** [comment]
Ask me everything you need to debug the issue.

I write my code details and all environment version.

About firewall is not this because I use AWS (Amazon Web Service) on EC2 Instance I run node.js application on RDS Oracle I run database server and I open firewall between server and database.

Thanks,
Jacopo

**Comment by jacopocappelli1989** [comment]
```
1|crm-dev  | Mon, 24 Feb 2020 16:43:12 GMT body-parser deprecated undefined extended: provide extended option at luniversotuo-crm-dev/luniversotuo-backend-node.js:46:17
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | Mon, 24 Feb 2020 17:25:20 GMT body-parser deprecated undefined extended: provide extended option at luniversotuo-crm-dev/luniversotuo-backend-node.js:46:17
1|crm-dev  | (node:9890) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | NJS-040: connection request timeout. Request exceeded queueTimeout of 60000
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | ORA-12537: TNS:connection closed
1|crm-dev  | NJS-040: connection request timeout. Request exceeded queueTimeout of 60000
1|crm-dev  | NJS-040: connection request timeout. Request exceeded queueTimeout of 60000
1|crm-dev  | NJS-040: connection request timeout. Request exceeded queueTimeout of 60000
1|crm-dev  | NJS-040: connection request timeout. Request exceeded queueTimeout of 60000
1|crm-dev  | NJS-040: connection request timeout. Request exceeded queueTimeout of 60000
1|crm-dev  | NJS-040: connection request timeout. Request exceeded queueTimeout of 60000
1|crm-dev  | NJS-040: connection request timeout. Request exceeded queueTimeout of 60000
```

**Comment by jacopocappelli1989** [comment]
Seems to be a stupid programming error.

Not added connection.close() at the end of elaboration on database and this issue cause too many connection and exploded database.

**Comment by jacopocappelli1989** [comment]
Seems to be a stupid programming error.

Not added connection.close() at the end of elaboration on database and this issue cause too many connection and exploded database.
