### ISSUE TITLE
NJS-045: cannot load a node-oracledb binary for Node.js 10.16.3 (linux x64) -  failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by wkoberstein** [oracle/node-oracledb#1247]
# Answer the following questions

1. Describe the problem and show the error you have.
```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
```
```
$ cat package.json
{
  "name": "oracle_test",
  "version": "1.0.0",
  "description": "test oracle client",
  "main": "test.js",
  "author": "Weston Koberstein",
  "dependencies": {
    "oracledb": "oracle/node-oracledb#v4.2.0"
  }
}
```
```
]$ cat test.js
console.log('env',process.env.LD_LIBRARY_PATH);
const oracledb = require('oracledb');
const dbConfig = require('./dbconfig.js');

async function run() {
  let connection;

  try {
    connection = await oracledb.getConnection(dbConfig);
    const result = await connection.execute(`SELECT 1 FROM dual`);
    console.log(result.metaData);
    console.log(result.rows);
  } catch (err) {
    console.error(err);
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
}
run();
```

```
$ node -v
v10.16.3
```
```
$ node test.js
env /usr/lib/oracle/19.6/client64/lib:/opt/rh/rh-nodejs10/root/usr/lib64
/home/v844072/oracle_test/node_modules/oracledb/lib/oracledb.js:82
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^

Error: NJS-045: cannot load a node-oracledb binary for Node.js 10.16.3 (linux x64)
  Node.js require('oracledb') error was:
  /home/v844072/oracle_test/node_modules/oracledb/build/Release/oracledb.node: failed to map segment from shared object: Operation not permitted
  Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html


    at Object.<anonymous> (/home/v844072/oracle_test/node_modules/oracledb/lib/oracledb.js:82:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/v844072/oracle_test/node_modules/oracledb/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

2. What Node.js version are you using?  Run node and show the output of:
- Platform 'linux'
- Node version: 'v10.16.3'
- Arch:'x64'
- oracleDB: 4.2.0
- Oracle Client 19.6/client64

3. Are you installing into vanilla Node.js, or using something like Electron?
Vanilla Node

4. Show the directory listing where your Oracle client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?
```
$ ls -ltra /usr/lib/oracle/19.6/client64/lib
total 234384
-rwxr-xr-x 1 root root 130519448 Dec 17 16:40 libociei.so
-rwxr-xr-x 1 root root    478400 Dec 17 16:40 libmql1.so
-rwxr-xr-x 1 root root   3609792 Dec 17 16:40 libipc1.so
-rw-r--r-- 1 root root     37519 Dec 17 16:40 xstreams.jar
-rwxr-xr-x 1 root root    116008 Dec 17 16:40 liboramysql19.so
-rwxr-xr-x 1 root root    153624 Dec 17 16:40 libocijdbc19.so
-rwxr-xr-x 1 root root   2339888 Dec 17 16:40 libocci.so.19.1
-rwxr-xr-x 1 root root   6587592 Dec 17 16:40 libnnz19.so
-rwxr-xr-x 1 root root  80496048 Dec 17 16:40 libclntsh.so.19.1
-rwxr-xr-x 1 root root   8049064 Dec 17 16:40 libclntshcore.so.19.1
-rw-r--r-- 1 root root   4340110 Dec 17 16:40 ojdbc8.jar
-rwxr-xr-x 1 root root   1577584 Dec 17 16:41 libsqlplus.so
-rwxr-xr-x 1 root root   1660752 Dec 17 16:41 libsqlplusic.so
-rw-r--r-- 1 root root       342 Dec 17 16:41 glogin.sql
drwxr-xr-x 4 root root        26 Dec 17 16:41 ..
lrwxrwxrwx 1 root root        17 Apr  8 15:47 libclntsh.so.18.1 -> libclntsh.so.19.1
lrwxrwxrwx 1 root root        17 Apr  8 15:47 libclntsh.so.12.1 -> libclntsh.so.19.1
lrwxrwxrwx 1 root root        17 Apr  8 15:47 libclntsh.so.11.1 -> libclntsh.so.19.1
lrwxrwxrwx 1 root root        17 Apr  8 15:47 libclntsh.so.10.1 -> libclntsh.so.19.1
lrwxrwxrwx 1 root root        17 Apr  8 15:47 libclntsh.so -> libclntsh.so.19.1
lrwxrwxrwx 1 root root        21 Apr  8 15:47 libclntshcore.so -> libclntshcore.so.19.1
drwxr-xr-x 3 root root        18 Apr  8 15:47 network
drwxr-xr-x 3 root root      4096 Apr 28 20:29 .
```

```
$ file /usr/lib/oracle/19.6/client64/lib/libipc1.so
/usr/lib/oracle/19.6/client64/lib/libipc1.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=454dec61042d6674d6561f2c345ddd56f17fe3e8, not stripped
```

5. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?  On macOS, show what is in `~/lib`.
```
$ echo $LD_LIBRARY_PATH
/usr/lib/oracle/19.6/client64/lib:/opt/rh/rh-nodejs10/root/usr/lib64
```
6. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).
No oracle environment variables set.

**Comment by cjbj** [comment]
Thanks for the useful detail.

> /home/v844072/oracle_test/node_modules/oracledb/build/Release/oracledb.node

This is a custom build (not our pre-built binary) so I am guessing you have built it on a different OS and copied it to Linux.

If that's not the cause, check file & directory permissions.  Check for file corruption.

PS.  Please review the [markdown syntax](https://help.github.com/github/writing-on-github/basic-writing-and-formatting-syntax) and update your post with appropriate backticks to format code and console output.

**Comment by wkoberstein** [comment]
@cjbj Thanks for the quick response. I am building the client on the same host / OS that I running the test script on.  I also tried with the prebuilt 4.2.1 client and get the same error. 

When i try and run ldd for the built client I get the following:
```
$ file oracledb.node
oracledb.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, 
BuildID[sha1]=4b711c10dec2e94b36626c7851e89f2d47d6a6ea, not stripped
```
```
$ ldd oracledb.node
ldd: warning: you do not have execution permission for `./oracledb.node'
        not a dynamic executable
```
```
$ ls -ltra
total 536
drwxr-xr-x 3 v844072 sdwgrp    101 May  3 21:44 ..
drwxr-xr-x 3 v844072 sdwgrp     20 May  3 21:44 .deps
drwxr-xr-x 3 v844072 sdwgrp     41 May  3 21:44 obj.target
-rwxr-xr-x 1 v844072 sdwgrp 546936 May  3 21:44 oracledb.node
drwxr-xr-x 4 v844072 sdwgrp     55 May  3 21:44 .
```
I also was able to connect to oracle with sqlplus, so I believe that the oracle client is installed and setup correctly.

**Comment by cjbj** [comment]
Check you don't have other builds laying around in lower or higher directories.

Keep digging and experimenting.   Or share details and logs.

This is my `ldd` output on Oracle Linux 7.8
```
cjones@localhost:~/n$ ldd node_modules/oracledb/build/Release/oracledb.node 
	linux-vdso.so.1 =>  (0x00007fff6dbe4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd04dc89000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd04da6d000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd04d765000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd04d463000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd04d24d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd04ce7f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd04e105000)
```

**Comment by wkoberstein** [comment]
@cjbj  As you expected it was a permission issues. The home directory was mounted without execute pervilages

```
$  mount | grep noexec | grep /home
/dev/mapper/rhel-home on /home type xfs (rw,nosuid,nodev,noexec,relatime,attr2,inode64,noquota
```

What I did was install it the global packages directory:
```
npm install -g oracledb@4.2.0
```
Then in the require i have the following:
```
var oracledb = require(process.env.ORACLEDB_PATH?process.env.ORACLEDB_PATH:'oracledb');
```
That way based on the environment I can set the path to the module.  

Is there a better way to do this?

**Comment by cjbj** [comment]
I'm glad you found the cause.

For loading the library, this might be a case to use NODE_PATH before running Node.js.  Maybe like:
```
export NODE_PATH=`npm root -g`
```
