### ISSUE TITLE
Oracle instant client 19.3

### ISSUE THREAD

**Issue by sdamte0428** [oracle/node-oracledb#1265]
# Do these first

- Review and follow the [installation instructions](https://oracle.github.io/node-oracledb/INSTALL.html)

- Review the [troubleshooting tips](https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting)

- If you have a `DPI-1047`, `DPI-1050` or `DPI-1072` error, review both the above again before opening an issue.

# Answer the following questions

1. Describe the problem and show the error you have.
**Cut and paste text showing the command you ran.  No screenshots.  Use a gist for long screen output and logs: see https://gist.github.com/**.

2. What Node.js version are you using?  Run node and show the output of:

```
process.platform
process.version
process.arch
require('oracledb').versionString
require('oracledb').oracleClientVersionString
```

3. Are you installing into vanilla Node.js, or using something like Electron?

4. Show the directory listing where your Oracle client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?

5. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?  On macOS, show what is in `~/lib`.

6. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).

**Comment by sdamte0428** [comment]
Hi ,
Please help , I am having the same issue for last couple of days . I have set the paths and checked all the versions seems 64bit . But I couldn't connect python 3.8.3 with oracle 19c using the 19.3 oracle instant client version .
attached my error message .
Traceback (most recent call last):
File "<pyshell#2>", line 1, in 
con = cx_Oracle.connect("hr/oracle@localhost/orcl")
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1)
I am connected to Oracle VM .

Thanks

**Comment by cjbj** [comment]
Wrong repo.  Look at https://github.com/oracle/python-cx_Oracle/issues/341

**Comment by ideal22** [comment]
Hey, i am facing this problem can not solve this issue, please help me!
1. Error: `Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the 64-bit Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
They can be downloaded from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
    at OracleDb.getConnection (/Users/nodir/projects/mobile-console/node_modules/oracledb/lib/oracledb.js:287:10)
    at OracleDb.getConnection (/Users/nodir/projects/mobile-console/node_modules/oracledb/lib/util.js:185:19)
    at /Users/nodir/projects/mobile-console/node_modules/knex/lib/dialects/oracledb/index.js:105:19
    at Promise._execute (/Users/nodir/projects/mobile-console/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/nodir/projects/mobile-console/node_modules/knex/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/nodir/projects/mobile-console/node_modules/knex/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_Oracledb.acquireRawConnection (/Users/nodir/projects/mobile-console/node_modules/knex/lib/dialects/oracledb/index.js:80:27)
    at create (/Users/nodir/projects/mobile-console/node_modules/knex/lib/client.js:290:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errorNum: 0,
  offset: 0
}`

2. 
proccess.platform: darwin
proccess.version: v14.3.0
process.arch: x64
require('oracledb').versionString: 4.2.0
require('oracledb').oracleClientVersionString: 
`Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
    at module.exports (/Users/nodir/projects/mobile-console/server-app.js:19:34)
    at Object.<anonymous> (/Users/nodir/projects/mobile-console/server-entry.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47`

3. 
Installing into Nodejs (Reactjs project)
`
nodir@MacBook-Pro-3 lib % cd ~/lib 
nodir@MacBook-Pro-3 lib % ls
libclntsh.dylib`

`
nodir@MacBook-Pro-3 ~ % cd /opt/oracle 
nodir@MacBook-Pro-3 oracle % ls
BASIC_LICENSE			libclntsh.dylib			libclntsh.dylib.18.1		libocci.dylib			libocci.dylib.18.1		liboramysql19.dylib		uidrvci
BASIC_README			libclntsh.dylib.10.1		libclntsh.dylib.19.1		libocci.dylib.10.1		libocci.dylib.19.1		network				xstreams.jar
adrci				libclntsh.dylib.11.1		libclntshcore.dylib.19.1	libocci.dylib.11.1		libociei.dylib			ojdbc8.jar
genezi				libclntsh.dylib.12.1		libnnz19.dylib			libocci.dylib.12.1		libocijdbc19.dylib		ucp.jar`

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/1239#issuecomment-636819727 and also try the upcoming changes in 5.0.0-dev, see https://github.com/oracle/node-oracledb/issues/1239#issuecomment-637948310

Note that in 5.0, putting libraries in ~/lib won't work with recent Node.js versions.

**Comment by sdamte0428** [comment]
After so many trials, this command solved my issue .Now I am able to
connect .The rest of the process is the same as its described in the
instructions .

ln -s ~/instantclient_19_3/libclntsh.dylib
~/Library/Python/3.8/lib/python/site-packages

Thanks,
