### ISSUE TITLE
Segmentation fault crash which cannot be catched

### ISSUE THREAD

**Issue by UserSina** [oracle/node-oracledb#1362]
## 0. General context: ##
I'm running an express backend which includes:

- A [Bree](https://github.com/breejs/bree) `Scheduler` which executes queries by connecting to a remote oracle database (using the instant client library).
- A  `REST API` which handles HTTP Requests.

## 1. What versions are you using? ##
Running node in a terminal:
```BASH
   - process.platform => 'win32'
   - process.version => 'v14.16.0'
   - process.arch => 'x64'
   - require('oracledb').versionString => '5.1.0'
   - require('oracledb').oracleClientVersionString => '19.10.0.0.0'
```

## 2. Is it an error or a hang or a crash? ##
A crash in the application that I couldn't catch, which happens as follows:
1. **Intermittently**: When the `Scheduler` has been running for some time (This is very irregular and can crash after an hour or not at all)
2. **Always**: This happens 10 out of 10 times, exactly when the `Scheduler` is running (IE, executing an oracle query or making a connection to an oracledb) **AND** I hit any API route.

**VERY IMPORTANT:** The app NEVER crashes when connecting to a database other than oracle. Tested extensively with [mysql2](https://www.npmjs.com/package/mysql2)

## 3.0 What error(s) or behavior you are seeing? ##
```JAVASCRIPT
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! myexpress-backend@1.0.0 node: `node ./bin/www`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the myexpress-backend@1.0.0 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Roaming\npm-cache\_logs\2021-04-11T10_21_39_366Z-debug.log
/c/Program Files/nodejs/npm: line 37:  1508 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"

```
<details>
  <summary>Full npm-cache log</summary>

```JAVASCRIPT
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Asus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'node'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'prenode', 'node', 'postnode' ]
5 info lifecycle myexpress-backend@1.0.0~prenode: myexpress-backend@1.0.0
6 info lifecycle myexpress-backend@1.0.0~node: myexpress-backend@1.0.0
7 verbose lifecycle myexpress-backend@1.0.0~node: unsafe-perm in lifecycle true
8 verbose lifecycle myexpress-backend@1.0.0~node: PATH: C:\Users\Asus\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\.bin;C:\Users\Asus\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Asus\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter\Driver;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Crucial\Crucial Storage Executive;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Asus\AppData\Local\Microsoft\WindowsApps;C:\Users\Asus\AppData\Local\Programs\Microsoft VS Code\bin;C:\adb;C:\Program Files\Git LFS;C:\wamp64\bin\php\php7.4.0;C:\composer;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Symfony;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Python\Python38\Scripts;C:\Python\Python38;C:\Users\Asus\AppData\Local\Microsoft\WindowsApps;C:\Users\Asus\AppData\Local\Programs\Microsoft VS Code\bin;C:\shortcuts;C:\Users\Asus\AppData\Roaming\Composer\vendor\bin;C:\symfony;C:\mingw-w64\mingw32\bin;C:\Users\Asus\AppData\Local\Android\Sdk\platform-tools;C:\Users\Asus\.dotnet\tools;C:\Users\Asus\AppData\Local\GitHubDesktop\bin;C:\src\flutter\bin;C:\Program Files\heroku\bin;C:\oracle\instantclient_19_10;C:\Users\Asus\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle myexpress-backend@1.0.0~node: CWD: A:\Documents\GitHub\database-to-appdynamics\myexpress-backend
10 silly lifecycle myexpress-backend@1.0.0~node: Args: [ '/d /s /c', 'node ./bin/www' ]
11 silly lifecycle myexpress-backend@1.0.0~node: Returned: code: 3221225477  signal: null
12 info lifecycle myexpress-backend@1.0.0~node: Failed to exec node script
13 verbose stack Error: myexpress-backend@1.0.0 node: `node ./bin/www`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Asus\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Asus\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid myexpress-backend@1.0.0
15 verbose cwd A:\Documents\GitHub\database-to-appdynamics\myexpress-backend
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Asus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "node"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 3221225477
22 error myexpress-backend@1.0.0 node: `node ./bin/www`
22 error Exit status 3221225477
23 error Failed at the myexpress-backend@1.0.0 node script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]

```
</details>

## 3.1 Still doesn't say much, any extra details about the bug? ##

According to [this blog](https://httptoolkit.tech/blog/how-to-debug-node-segfaults/), it has to do with **_native code somewhere trying to use a null pointer as a memory address_**.
Using [segfault handler](https://www.npmjs.com/package/segfault-handler), I did indeed manage to find more information about the crash, (but the app still crashes nonetheless).

<details>
  <summary>Here's the crash: (It's very long)</summary>

```JAVASCRIPT
PID 13968 received SIGSEGV for address: 0x47d0569a
SymInit: Symbol-SearchPath: '.;A:\Documents\GitHub\database-to-appdynamics\myexpress-backend;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Asus'
OS-Version: 10.0.17763 () 0x100-0x1
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\StackWalker.cpp (923): StackWalker::ShowCallstack
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FFDA9766896 (ntdll): (filename not available): RtlInitializeCriticalSectionAndSpinCount
00007FFDA9704709 (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97A231E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFD47D0569A (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47D03EDD (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CDAFA1 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCB139 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCAE0B (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CB4EF2 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FF66C9D84CE (node): (filename not available): uv_queue_work
00007FF66C9C4AFD (node): (filename not available): uv_poll_stop
00007FF66D791E90 (node): (filename not available): v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
00007FFDA9627E94 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFDA9767AD1 (ntdll): (filename not available): RtlUserThreadStart

PID 13968 received SIGSEGV for address: 0xa65d5299
SymInit: Symbol-SearchPath: '.;A:\Documents\GitHub\database-to-appdynamics\myexpress-backend;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Asus'
OS-Version: 10.0.17763 () 0x100-0x1
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\StackWalker.cpp (923): StackWalker::ShowCallstack
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FFDA9766896 (ntdll): (filename not available): RtlInitializeCriticalSectionAndSpinCount
00007FFDA9704709 (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97088A6 (ntdll): (filename not available): RtlRaiseException
00007FFDA65D5299 (KERNELBASE): (filename not available): RaiseException
00007FFD32217C87 (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD32217ACC (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD3227338E (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD32237E77 (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322373A6 (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322371DA (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD32199D56 (OraOCIEI19): (filename not available): dbgecPop
00007FFD3219A5EA (OraOCIEI19): (filename not available): dbgecPop
00007FFD322B1F53 (OraOCIEI19): (filename not available): dbgfcsIlcsRegister
00007FFD322AFB5A (OraOCIEI19): (filename not available): dbgfcsIlcsRegister
00007FFD32180539 (OraOCIEI19): (filename not available): dbgePostErrorDirect
00007FFD3217F629 (OraOCIEI19): (filename not available): dbgePostErrorDirect
00007FFD31FB1EA0 (OraOCIEI19): (filename not available): kpeDbgHdlPostop
00007FFD3221B94E (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFDA66053AC (KERNELBASE): (filename not available): UnhandledExceptionFilter
00007FFDA97A7100 (ntdll): (filename not available): memset
00007FFDA978F306 (ntdll): (filename not available): _C_specific_handler
00007FFDA97A35AF (ntdll): (filename not available): _chkstk
00007FFDA9704AAF (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97A231E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFD47D0569A (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47D03EDD (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CDAFA1 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCB139 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCAE0B (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CB4EF2 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FF66C9D84CE (node): (filename not available): uv_queue_work
00007FF66C9C4AFD (node): (filename not available): uv_poll_stop
00007FF66D791E90 (node): (filename not available): v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
00007FFDA9627E94 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFDA9767AD1 (ntdll): (filename not available): RtlUserThreadStart

PID 13968 received SIGSEGV for address: 0x322190df
SymInit: Symbol-SearchPath: '.;A:\Documents\GitHub\database-to-appdynamics\myexpress-backend;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Asus'
OS-Version: 10.0.17763 () 0x100-0x1
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\StackWalker.cpp (923): StackWalker::ShowCallstack
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FFDA9766896 (ntdll): (filename not available): RtlInitializeCriticalSectionAndSpinCount
00007FFDA9704709 (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97A231E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFD322190DF (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD32218018 (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD32217BF9 (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD32217ACC (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD3227338E (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322375EA (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322371DA (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD32199D56 (OraOCIEI19): (filename not available): dbgecPop
00007FFD3219A5EA (OraOCIEI19): (filename not available): dbgecPop
00007FFD322B1F53 (OraOCIEI19): (filename not available): dbgfcsIlcsRegister
00007FFD322AFB5A (OraOCIEI19): (filename not available): dbgfcsIlcsRegister
00007FFD32180539 (OraOCIEI19): (filename not available): dbgePostErrorDirect
00007FFD3217F629 (OraOCIEI19): (filename not available): dbgePostErrorDirect
00007FFD31FB1EA0 (OraOCIEI19): (filename not available): kpeDbgHdlPostop
00007FFD3221B94E (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFDA66053AC (KERNELBASE): (filename not available): UnhandledExceptionFilter
00007FFDA97A7100 (ntdll): (filename not available): memset
00007FFDA978F306 (ntdll): (filename not available): _C_specific_handler
00007FFDA97A35AF (ntdll): (filename not available): _chkstk
00007FFDA9704AAF (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97A231E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFD47D0569A (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47D03EDD (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CDAFA1 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCB139 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCAE0B (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CB4EF2 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FF66C9D84CE (node): (filename not available): uv_queue_work
00007FF66C9C4AFD (node): (filename not available): uv_poll_stop
00007FF66D791E90 (node): (filename not available): v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
00007FFDA9627E94 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFDA9767AD1 (ntdll): (filename not available): RtlUserThreadStart

PID 13968 received SIGSEGV for address: 0xa65d5299
SymInit: Symbol-SearchPath: '.;A:\Documents\GitHub\database-to-appdynamics\myexpress-backend;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Asus'
OS-Version: 10.0.17763 () 0x100-0x1
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\StackWalker.cpp (923): StackWalker::ShowCallstack
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FFDA9766896 (ntdll): (filename not available): RtlInitializeCriticalSectionAndSpinCount
00007FFDA9704709 (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97088A6 (ntdll): (filename not available): RtlRaiseException
00007FFDA65D5299 (KERNELBASE): (filename not available): RaiseException
00007FFD32217C87 (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD32217ACC (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD3227338E (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD32237E77 (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322373A6 (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322371DA (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322B177E (OraOCIEI19): (filename not available): dbgfcsIlcsRegister
00007FFD322B04DC (OraOCIEI19): (filename not available): dbgfcsIlcsRegister
00007FFD32180539 (OraOCIEI19): (filename not available): dbgePostErrorDirect
00007FFD3217F629 (OraOCIEI19): (filename not available): dbgePostErrorDirect
00007FFD31FB1EA0 (OraOCIEI19): (filename not available): kpeDbgHdlPostop
00007FFD3221B94E (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFDA66053AC (KERNELBASE): (filename not available): UnhandledExceptionFilter
00007FFDA97A7100 (ntdll): (filename not available): memset
00007FFDA978F306 (ntdll): (filename not available): _C_specific_handler
00007FFDA97A35AF (ntdll): (filename not available): _chkstk
00007FFDA9704AAF (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97A231E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFD47D0569A (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47D03EDD (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CDAFA1 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCB139 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCAE0B (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CB4EF2 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FF66C9D84CE (node): (filename not available): uv_queue_work
00007FF66C9C4AFD (node): (filename not available): uv_poll_stop
00007FF66D791E90 (node): (filename not available): v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
00007FFDA9627E94 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFDA9767AD1 (ntdll): (filename not available): RtlUserThreadStart

PID 13968 received SIGSEGV for address: 0x322190df
SymInit: Symbol-SearchPath: '.;A:\Documents\GitHub\database-to-appdynamics\myexpress-backend;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Asus'
OS-Version: 10.0.17763 () 0x100-0x1
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\StackWalker.cpp (923): StackWalker::ShowCallstack
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FFDA9766896 (ntdll): (filename not available): RtlInitializeCriticalSectionAndSpinCount
00007FFDA9704709 (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97A231E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFD322190DF (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD32218018 (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD32217BF9 (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD32217ACC (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD3227338E (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322375EA (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322371DA (OraOCIEI19): (filename not available): dbgtfFilePop
00007FFD322B177E (OraOCIEI19): (filename not available): dbgfcsIlcsRegister
00007FFD322B04DC (OraOCIEI19): (filename not available): dbgfcsIlcsRegister
00007FFD32180539 (OraOCIEI19): (filename not available): dbgePostErrorDirect
00007FFD3217F629 (OraOCIEI19): (filename not available): dbgePostErrorDirect
00007FFD31FB1EA0 (OraOCIEI19): (filename not available): kpeDbgHdlPostop
00007FFD3221B94E (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFDA66053AC (KERNELBASE): (filename not available): UnhandledExceptionFilter
00007FFDA97A7100 (ntdll): (filename not available): memset
00007FFDA978F306 (ntdll): (filename not available): _C_specific_handler
00007FFDA97A35AF (ntdll): (filename not available): _chkstk
00007FFDA9704AAF (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97A231E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFD47D0569A (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47D03EDD (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CDAFA1 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCB139 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCAE0B (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CB4EF2 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FF66C9D84CE (node): (filename not available): uv_queue_work
00007FF66C9C4AFD (node): (filename not available): uv_poll_stop
00007FF66D791E90 (node): (filename not available): v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
00007FFDA9627E94 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFDA9767AD1 (ntdll): (filename not available): RtlUserThreadStart

PID 13968 received SIGSEGV for address: 0xa65d5299
SymInit: Symbol-SearchPath: '.;A:\Documents\GitHub\database-to-appdynamics\myexpress-backend;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Asus'
OS-Version: 10.0.17763 () 0x100-0x1
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\StackWalker.cpp (923): StackWalker::ShowCallstack
A:\Documents\GitHub\database-to-appdynamics\myexpress-backend\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FFDA9766896 (ntdll): (filename not available): RtlInitializeCriticalSectionAndSpinCount
00007FFDA9704709 (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97088A6 (ntdll): (filename not available): RtlRaiseException
00007FFDA65D5299 (KERNELBASE): (filename not available): RaiseException
00007FFD3221B6BA (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFD31FB1DC5 (OraOCIEI19): (filename not available): kpeDbgHdlPostop
00007FFD3221B94E (OraOCIEI19): (filename not available): slgetohorabaseconfig
00007FFDA66053AC (KERNELBASE): (filename not available): UnhandledExceptionFilter
00007FFDA97A7100 (ntdll): (filename not available): memset
00007FFDA978F306 (ntdll): (filename not available): _C_specific_handler
00007FFDA97A35AF (ntdll): (filename not available): _chkstk
00007FFDA9704AAF (ntdll): (filename not available): RtlWalkFrameChain
00007FFDA97A231E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFD47D0569A (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47D03EDD (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CDAFA1 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCB139 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CCAE0B (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FFD47CB4EF2 (oracledb-5.1.0-win32-x64): (filename not available): (function-name not available)
00007FF66C9D84CE (node): (filename not available): uv_queue_work
00007FF66C9C4AFD (node): (filename not available): uv_poll_stop
00007FF66D791E90 (node): (filename not available): v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
00007FFDA9627E94 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFDA9767AD1 (ntdll): (filename not available): RtlUserThreadStart
```

</details>

## 4. Include a runnable Node.js script that shows the problem. ##

Here's a small explanation, the `app.js` has a timeout of 5 seconds, which starts a scheduler instance from `Scheduler.js`. The instance then creates a worker from `query-worker.js` which runs every 1 minute to get data from an oracle database.

<details>
 <summary><b>app.js</b></summary>

```JAVASCRIPT
// ...
var express = require('express');
var SegfaultHandler = require('segfault-handler');

const Scheduler = require('./Scheduler');
var scheduler = Scheduler;

// routes
var indexRouter = require('./routes/indexRoutes');
var usersRouter = require('./routes/usersRoutes');

SegfaultHandler.registerHandler('crash.log', function (signal, address, stack) {
  // App still crashes even with this
  console.log('Segmentation error handled!');
});

// Start the scheduler after 5 seconds
setTimeout(async () => {
  scheduler.startScheduler();
}, 5000);

app.use('/', indexRouter);
app.use('/users', usersRouter);

// catch 404 and forward to error handler
app.use(function (_req, _res, next) {
  next(createError(404));
});
```
</details>

<details>
 <summary><b>Scheduler.js</b></summary>

```JAVASCRIPT
// My job scheduler
const Bree = require('bree');

class Scheduler {
	constructor() {
		this.bree = null;
		this.started = false;
	}
  
	startScheduler = () => {
		this.bree = new Bree({
			root: false,
			logger,
			jobs: [{
				name: 'query-worker',
				path: path.join('jobs', 'query-worker.js')
                                interval: '1m' // Executes every minute
			}],
			errorHandler: (error, workerMetaData) => {
				logger.error(error);
				logger.warn(`Error running a worker: ${workerMetaData.name}`);
			},
		});
		this.bree.start();
	}
}

module.exports = new Scheduler();
```

</details>

<details>
 <summary><b>query-worker.js</b></summary>

```JAVASCRIPT
const params = require('./path/to/connection/parameters');
const logger = require('my/logger');

(async () => {
  var result = {status: 'pending'}

  // Make a connection to the database
  var conn;
  try {
	const oracledb = require('oracledb');
	conn = await oracledb.getConnection({
		user: params.user,
		password: params.password,
		connectString: `${params.host}:${params.port}/${params.database}?
		  connect_timeout=${Math.floor(params.connectTimeout / 1000)}`,
	});
	} catch (error) {
	  logger.error(error.stack)
	  result.status = 'fail';
    };
  }
  
  // Execute the query from the connection
  var data;
  try {
	data = await conn.execute(params.query);
	// When I don't close, app also crashes with this code
        // ORA-24550: signal received: Unhandled exception
	await conn.close();
	result.status = 'success';
  } catch (error) {
	  logger.error(error.stack)
	  result.status = 'fail';
  }
  
  result.status === 'fail'
    ? logger.error('Could not execute query')
    : logger.info('Query executed successfully');
  terminate();
})();

// The logger does not show any error when the segmentation fault happens

```

</details>

**Comment by cjbj** [comment]
Please continue with your original post on this topic, #1342 instead of opening this duplicate.  I know this issue is annoying you.  A _complete_ runnable testcase will be needed for us to identify more - preferably without Bree.

**Comment by UserSina** [comment]
The reason I opened this issue is because I thought it was a separate bug entirely (`Segmentation fault` instead of `ORA-24550`) and not because of being annoyed or anything. You get used to errors at this point and see them as challenges honestly 😅
