### ISSUE TITLE
NJS-040: connection request timeout. Request exceeded queueTimeout of 60000

### ISSUE THREAD

**Issue by sarikonda1** [oracle/node-oracledb#1448]
Hell Team,
I am facing this issue in the production, I am really very thankful i am little surprised to see this issue for the first time.

(node:21) UnhandledPromiseRejectionWarning: Error: NJS-040: connection request timeout. Request exceeded queueTimeout of 60000
    at Pool.onRequestTimeout (/opt/app-root/clientproductassociation/node_modules/oracledb/lib/pool.js:143:38)
    at Timeout._onTimeout (/opt/app-root/clientproductassociation/node_modules/oracledb/lib/pool.js:205:28)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 

Below are configuration we are using for creating connection pool..
pool = await oracledb.createPool({
      user:USER,
      password: PWD,
      connectString: CONNECTIONSTRING,
      poolMin: 10,
      poolMax: 50,
      poolIncrement: 10,
      poolPingInterval: 60,
      poolTimeout: 60, 
      queueTimeout: 60000 
    });

and also below is the way we are getting connections 
let  connection = await oracledb.getConnection();
and closing connections properly

and package.json is like below
"scripts": {
      "start": "node --max-http-header-size=40960 ./dist/server.js"
   },

**Comment by cjbj** [comment]
Sounds like your app isn't closing connections.  And/or perhaps you haven't set UV_THREADPOOL_SIZE.  The doc has details.

**Comment by sarikonda1** [comment]
We are closing connections correctly @cjbj . But we haven't used UV_THREADPOOL_SIZE in your project..
If i want us to use for above listed configuration..
where to place and What is the right value to keep for UV_THREADPOOL_SIZE ?

**Comment by cjbj** [comment]
See https://oracle.github.io/node-oracledb/doc/api.html#numberofthreads

**Comment by cjbj** [comment]
Closing - no activity.

**Comment by mbanda1** [comment]
> Sounds like your app isn't closing connections

This solved my case.
Why is it necessary to close connection after queue or de-queue action yet we still use same pool ?
