### ISSUE TITLE
NJS-112 error thrown when changing port on oracledb 6.0.0

### ISSUE THREAD

**Issue by Thibaut-Mouton** [oracle/node-oracledb#1556]
Hello ! First of all thank you for this amazing feature which will save me a lot of time. However I encounter a somewhat strange error when I try to connect to my Oracle DB.

1. What versions are you using?

- Alpine Linux v3.16 
- Arch x64
- Docker in Kubernetes v1.23.10
- Node 16.17.0
- npm 8.15.0
- oracledb 6.0.0
- Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

**Note** : it's working fine on my PC with the following configuration : 
- Windows 10.22H2
- Node 16.17.0
- npm 8.15.0
- oracledb 6.0.0

2. Is it an error or a hang or a crash?

I got an error : when changing the default Oracle port (I changed it to 1522), connection is impossible and I see the message below. When I set the default port in the connection string (I tried with another Oracle DB), the connexion is established successfullly.

3. What error(s) or behavior you are seeing ?

```
Error: NJS-112: internal error: read integer of length 64 when expecting integer of no more than length 4
    at Object.throwErr (/opt/app/node_modules/oracledb/lib/errors.js:588:10)
    at ReadPacket._readInteger (/opt/app/node_modules/oracledb/lib/thin/protocol/buffer.js:100:14)
    at ReadPacket.readUB4 (/opt/app/node_modules/oracledb/lib/thin/protocol/buffer.js:491:17)
    at ReadPacket._readBytesWithLength (/opt/app/node_modules/oracledb/lib/thin/protocol/packet.js:160:36)
    at ReadPacket.readBytesWithLength (/opt/app/node_modules/oracledb/lib/thin/protocol/buffer.js:364:17)
    at ReadPacket.readStr (/opt/app/node_modules/oracledb/lib/thin/protocol/buffer.js:463:22)
    at AuthMessage.processReturnParameter (/opt/app/node_modules/oracledb/lib/thin/protocol/messages/auth.js:308:21)
    at AuthMessage.processMessage (/opt/app/node_modules/oracledb/lib/thin/protocol/messages/base.js:213:12)
    at AuthMessage.process (/opt/app/node_modules/oracledb/lib/thin/protocol/messages/base.js:196:12)
    at AuthMessage.decode (/opt/app/node_modules/oracledb/lib/thin/protocol/messages/base.js:187:10) {
  code: 'NJS-112'
}
```

4. Include a runnable Node.js script that shows the problem.

I use this sample with nodejs in command line : 
```
const oracle = require('oracledb')
const connection = await oracle.getConnection({user:'XXXXX',password:'XXXXX',connectString:'(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=XXXXXX)(PORT=1522))(CONNECT_DATA=(SID=XXXXXX)))'})
```

Could you help me ? In advance, thank you for your help !

**Comment by anthony-tuininga** [comment]
Are you able to share the packet trace by setting the environment variable `NODE_ORACLEDB_DEBUG_PACKETS` to any value before running your script? I only need the last one sent and received.

**Comment by anthony-tuininga** [comment]
Wait. I don't think I need it, actually. Thin mode doesn't support Oracle Database 11g. You will have to enable thick mode for that database. An error should be raised for this condition but clearly isn't!

**Comment by sharadraju** [comment]
> Hi, @Thibaut-Mouton. Thank you for trying our new release. However, node-oracledb 6.0 Thin mode supports only Oracle Database versions 12.1 and later. https://node-oracledb.readthedocs.io/en/latest/user_guide/installation.html Oracle Database 11g is not supported :)

Oops, @anthony-tuininga beat me to it :)

**Comment by Thibaut-Mouton** [comment]
Oh indeed I double check my nodejs compatibility with oracledb but I forgot to check the DB version compatibility, which is indeed a few versions behind :)
Sorry for this false problem I'll close the issue and try with thick mode !
Have a nice day

**Comment by cjbj** [comment]
We'll improve the error message in this scenario.
