### ISSUE TITLE
Error DPI-1019 in version 6.0.0

### ISSUE THREAD

**Issue by okamototomoyuki** [oracle/node-oracledb#1560]
1. What versions are you using?  

OS: windows 11  
node.js: v18.8.0  
node-oracledb: 6.0.0  

2. Is it an error or a hang or a crash?  
error  

4. What error(s) or behavior you are seeing?

The following error occurs after upgrading node-oracledb from 5.5.0 to 6.0.0.  
The table name and path are hidden for the convenience of my company.  
```
QueryFailedError: DPI-1019: buffer size of 7 is too small
    at OracleQueryRunner.query (D:\repository\APP\node_modules\typeorm\driver\oracle\OracleQueryRunner.js:190:19)
    at async InsertQueryBuilder.execute (D:\repository\APP\node_modules\typeorm\query-builder\InsertQueryBuilder.js:106:33)
    at async #insertOrUpdate (D:/repository/APP/src/lib/core/db/DbSystem.ts:82:15)
    at async ProjectDb.insert (D:/repository/APP/src/lib/core/db/DbSystem.ts:56:5)
    at async MenuService.save (D:/repository/APP/src/lib/app/service/MenuService.ts:82:5)
    at async eval (D:/repository/APP/src/routes/edit-menu/api/+server.ts:14:5)
    at async DiContainer.resolve (D:/repository/APP/src/lib/app/container/DiContainer.ts:33:7)
    at async POST (D:/repository/APP/src/routes/edit-menu/api/+server.ts:12:3)
    at async Module.render_endpoint (D:/repository/APP/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:18)
    at async resolve (D:/repository/APP/node_modules/@sveltejs/kit/src/runtime/server/respond.js:403:17) {
  query: 'INSERT INTO "TABLE_NAME"("ENT_USER_ID", "ENT_DTM", "ENT_PGM_ID", "UPD_USER_ID", "UPD_DTM", "UPD_PGM_ID", "ID", "NAME", "NODE_TYPE", "URL", "IS_AUTH_ONLY", "MENU_CODE", "IS_DISABLED") VALUES (:1, :2, :3, DEFAULT, DEFAULT, DEFAULT, :4, :5, :6, :7, :8, :9, :10)',
  parameters: [
    'NA',
    2023-05-29T04:49:40.654Z,
    'SYSNM',
    1,
    'MENU_NAME',
    2,
    null,
    0,
    null,
    0
  ],
  driverError: Error: DPI-1019: buffer size of 7 is too small
      at async OracleQueryRunner.query (D:\repository\APP\node_modules\typeorm\driver\oracle\OracleQueryRunner.js:153:25)
      at async InsertQueryBuilder.execute (D:\repository\APP\node_modules\typeorm\query-builder\InsertQueryBuilder.js:106:33)
      at async #insertOrUpdate (D:/repository/APP/src/lib/core/db/DbSystem.ts:82:15)
      at async ProjectDb.insert (D:/repository/APP/src/lib/core/db/DbSystem.ts:56:5)
      at async MenuService.save (D:/repository/APP/src/lib/app/service/MenuService.ts:82:5)
      at async eval (D:/repository/APP/src/routes/edit-menu/api/+server.ts:14:5)
      at async DiContainer.resolve (D:/repository/APP/src/lib/app/container/DiContainer.ts:33:7)
      at async POST (D:/repository/APP/src/routes/edit-menu/api/+server.ts:12:3)
      at async Module.render_endpoint (D:/repository/APP/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:18)
      at async resolve (D:/repository/APP/node_modules/@sveltejs/kit/src/runtime/server/respond.js:403:17) {
    errorNum: 0,
    offset: 0,
    code: 'DPI-1019'
  },
  errorNum: 0,
  offset: 0,
  code: 'DPI-1019'
}
```

5. Include a runnable Node.js script that shows the problem.  

Oracle's connection is used internally by TypeORM.

**Comment by sharadraju** [comment]
@okamototomoyuki  Can you provide the schema of "TABLE NAME"? That will help us identify which bind variable is complaining and possibly enable us to replicate the issue.

It would be useful if you can provide a simple runnable Node.js script without TypeORM that replicates the problem\

**Comment by YeisonKirax** [comment]
In my case the reason for the error was that the sent text had tildes

**Comment by cjbj** [comment]
You could do worse than try the patch in https://github.com/oracle/node-oracledb/issues/1554

**Comment by okamototomoyuki** [comment]
> @okamototomoyuki 「TABLE NAME」のテーブル スキーマと列の型を提供していただけますか? これは、問題を抱えているバインド変数を特定するのに役立ち、問題を再現できる可能性があります。
> 
> 問題を再現する、TypeORM を使用せずに実行可能な単純な Node.js スクリプトを提供できれば便利です。

Thank you for your reply.  
The table definition is below.
```sql
  CREATE TABLE "SCHEMA_NAME"."TABLE_NAME" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE), 
	"NODE_TYPE" NUMBER(1,0), 
	"URL" VARCHAR2(255 BYTE), 
	"IS_AUTH_ONLY" NUMBER(1,0), 
	"MENU_CODE" VARCHAR2(5 BYTE), 
	"IS_DEFAULT" NUMBER(1,0), 
	"IS_DISABLED" NUMBER(1,0), 
	"ENT_USER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ENT_DTM" DATE DEFAULT current_timestamp NOT NULL ENABLE, 
	"ENT_PGM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"UPD_USER_ID" VARCHAR2(20 BYTE), 
	"UPD_DTM" DATE, 
	"UPD_PGM_ID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "LGSTR_PTL_MENU_ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS_DEV2"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS_DEV2" ;
```
Oracle Version: 12.1.0.1  
DB Server OS: WindowsServer2016  

Below is the line where the TypeORM error occurs.  
https://github.com/typeorm/typeorm/blob/abb9079f2b2c5e02253b4c83ba10358d1a1f373f/src/driver/oracle/OracleQueryRunner.ts#L210

**Comment by sharadraju** [comment]
@okamototomoyuki You might want to try the patch in [#1554](https://github.com/oracle/node-oracledb/issues/1554) as @cjbj suggested as the columns all seem to be multi-byte

**Comment by sharadraju** [comment]
Hi @okamototomoyuki, were you able to try the patch in #1554?

**Comment by cjbj** [comment]
This was fixed in 6.0.1

**Comment by okamototomoyuki** [comment]
@cjbj @sharadraju 
I am very sorry for the reply after closing.
After upgrading to 6.0.1, the error disappeared.

**Comment by cjbj** [comment]
@okamototomoyuki no problem at all!  We are very happy to have your confirmation.
