### ISSUE TITLE
NJS-116: password verifier type 0x939 is not supported by node-oracledb in Thin mode

### ISSUE THREAD

**Issue by venkateshkolisetty** [oracle/node-oracledb#1585]
1. What versions are you using?

Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

process.platform: `win32`
process.version: ` v18.16.0`
process.arch: `x64`
require('oracledb').versionString: `6.0.2`
require('oracledb').oracleClientVersionString:
```
Uncaught:
Error: NJS-089: getting the Oracle Client version is not supported by node-oracledb in Thin mode
    at throwErr (~\node_modules\oracledb\lib\errors.js:591:10)
    at Object.throwNotImplemented (~\node_modules\oracledb\lib\errors.js:600:3)
    at get oracleClientVersionString [as oracleClientVersionString] (~\node_modules\oracledb\lib\oracledb.js:1064:14) {
  code: 'NJS-089'
```

2. Is it an error or a hang or a crash?

`Error`

3. What error(s) or behavior you are seeing?

```
Uncaught Error Error: NJS-116: password verifier type 0x939 is not supported by node-oracledb in Thin mode
    at throwErr (~\node_modules\oracledb\lib\errors.js:591:10)
    at encode (~\node_modules\oracledb\lib\thin\protocol\messages\auth.js:208:20)
    at _encodeMessage (~\node_modules\oracledb\lib\thin\protocol\protocol.js:105:20)
    at _processMessage (~\node_modules\oracledb\lib\thin\protocol\protocol.js:146:18)
    at connect (~\node_modules\oracledb\lib\thin\connection.js:547:28)
    at processTicksAndRejections (internal/process/task_queues:95:5)
```

4. Include a runnable Node.js script that shows the problem.

```
import * as oracledb from 'oracledb';
oracledb.createPool({
                user: 'username'
                , password: 'password'
                , connectString: 'host:port/sid'
            }).then((pool) => {
                resolve(pool);
            }).catch((err) => {
                reject(err);
            });
```

**Comment by cjbj** [comment]
Duplicate of https://github.com/oracle/node-oracledb/issues/1584
