### ISSUE TITLE
Cannot connect to Oracle RDS Host with TLS

### ISSUE THREAD

**Issue by agregory23** [oracle/node-oracledb#1593]
1. What versions are you using?
Oracle RDS: 19.0.0.0.ru-2023-07.rur-2023-07.r1

npm -v oracledb
8.19.2

nodeJS node-v16.18.0-linux-x64 - Also tried 20.5.1.

I cannot show the run output due to it being a cloud hosted database.  I have configured TLS and added the RDS public certificates to the trust store of my client per:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

I have configured the option group to enable TLS port 2484 per this guide:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.Oracle.Options.SSL.html#Appendix.Oracle.Options.SSL.OptionGroup

2. Describe the problem

I have a button that does a simple connection check to a database in RDS.  The node output for that looks like:
```
{
  user: 'signserver',
  password: 'XXXXXXXX,
  connectString: '(DESCRIPTION =(ADDRESS=(PROTOCOL = TCPS)(HOST = alex.c3tXXXXXXX2ws.us-east-1.rds.amazonaws.com)(PORT= 2484 ))(CONNECT_DATA =(SID= SIGNSERV)(security=(SSL_SERVER_CERT_DN="CN=alex.c3tXXXXXX2ws.us-east-1.rds.amazonaws.com"))))'
}
```
3. Include a runnable Node.js script that shows the problem.

```
router.post("/oracledbtest", async (req, res) => {
  const dbFQDN = req.body.dbhost;
  const dbFQDNArr = dbFQDN.split(".");
  const dbHostName = dbFQDNArr[0];
  const dbName = req.body.dbname;
  console.log(dbFQDN);
  console.log(req.body.dbhost);
  console.log(dbHostName);
  const connString = `(DESCRIPTION =(ADDRESS=(PROTOCOL = TCPS)(HOST = ${dbFQDN})(PORT= ${req.body.dbport} ))(CONNECT_DATA =(SID= ${dbName})(security=(SSL_SERVER_CERT_DN="CN=${dbFQDN}"))))`
  const dbuser = req.body.dbuser;
  const oracleDBConnect = {
    user: dbuser,
    password: req.body.dbpass,
    connectString : connString,
  }
  let connection;

  try {
    console.log(oracleDBConnect);
    connection = await oracledb.getConnection(oracleDBConnect);
    connection.callTimeout = 3000;
  }
  catch (err) {
    console.log(err.stack);
    const response = {
      status: 400,
      success: "Failed!",
      message: "CONNECTION_FAILURE",
    };
    console.log(err.stack);
    return res.send(JSON.stringify(response));
  }
  try {
    const result = await connection.execute('SELECT INSTANCE_NAME, STATUS, DATABASE_STATUS FROM V$INSTANCE');
    console.log(result.rows[0]);
  }
  catch (err) {
    console.log(err.stack);
    const response = {
      status: 400,
      success: "Failed!",
      message: "CONNECTION_FAILURE",
    };
    console.log(err.stack);
    await connection.close();
    return res.send(JSON.stringify(response));
  }
  console.log("Connected!");
  try {
    const result = await connection.execute("SELECT rowVersion FROM GlobalConfigurationData WHERE configurationId='UPGRADE'");
    if (result.rows.length >= 1) {
      const response = {
      status: 400,
      success: "Failed!",
      message: "DBEXIST_FAILURE",
      }
      return res.send(JSON.stringify(response));
    };
 }
 catch (err) {
  console.log(err.stack);
 }
 await connection.close();
 const response = {
     status: 200,
     success: "Connected!",
     message: "SUCCESS",
 };
  return res.send(JSON.stringify(response));
});
```
4. More detail...

When I try to connect to the host with openssl it validates fine showing the host trusts the cert and makes a connection:
```
[root@ip-172-16-1-195 confwizard]# openssl s_client -connect alex.c3tXXXX2ws.us-east-1.rds.amazonaws.com:2484
CONNECTED(00000003)
depth=2 C = US, L = Seattle, ST = Washington, O = "Amazon Web Services, Inc.", OU = Amazon RDS, CN = Amazon RDS Root 2019 CA
verify return:1
depth=1 C = US, ST = Washington, L = Seattle, O = "Amazon Web Services, Inc.", OU = Amazon RDS, CN = Amazon RDS us-east-1 2019 CA
verify return:1
depth=0 CN = alex.c3tXXXX2ws.us-east-1.rds.amazonaws.com, OU = RDS, O = Amazon.com, L = Seattle, ST = Washington, C = US
verify return:1
---
Certificate chain
 0 s:CN = alex.c3tXXXX2ws.us-east-1.rds.amazonaws.com, OU = RDS, O = Amazon.com, L = Seattle, ST = Washington, C = US
   i:C = US, ST = Washington, L = Seattle, O = "Amazon Web Services, Inc.", OU = Amazon RDS, CN = Amazon RDS us-east-1 2019 CA
 1 s:C = US, ST = Washington, L = Seattle, O = "Amazon Web Services, Inc.", OU = Amazon RDS, CN = Amazon RDS us-east-1 2019 CA
   i:C = US, L = Seattle, ST = Washington, O = "Amazon Web Services, Inc.", OU = Amazon RDS, CN = Amazon RDS Root 2019 CA
 2 s:C = US, L = Seattle, ST = Washington, O = "Amazon Web Services, Inc.", OU = Amazon RDS, CN = Amazon RDS Root 2019 CA
   i:C = US, L = Seattle, ST = Washington, O = "Amazon Web Services, Inc.", OU = Amazon RDS, CN = Amazon RDS Root 2019 CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIE2jCCA8KgAwIBAgIQAJmc8vAvdihAhufFvs3SyTANBgkqhkiG9w0BAQsFADCB
lDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcMB1Nl
YXR0bGUxIjAgBgNVBAoMGUFtYXpvbiBXZWIgU2VydmljZXMsIEluYy4xEzARBgNV
BAsMCkFtYXpvbiBSRFMxJTAjBgNVBAMMHEFtYXpvbiBSRFMgdXMtZWFzdC0xIDIw
MTkgQ0EwHhcNMjMwODE4MTUzNDIzWhcNMjQwODIyMTcwODUwWjCBjzE2MDQGA1UE
AwwtYWxleC5jM3Qya2xnNWEyd3MudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
MQwwCgYDVQQLDANSRFMxEzARBgNVBAoMCkFtYXpvbi5jb20xEDAOBgNVBAcMB1Nl
YXR0bGUxEzARBgNVBAgMCldhc2hpbmd0b24xCzAJBgNVBAYTAlVTMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj+GjAVJaObAPvjwJXM+LtGJ/yaVi3E0K
vGq9+KXHDMdWpB3PIax0ayS8FGCrTulMalPlrQLvJHZ5kUN+MLSnbsbOQRFy0CiM
KNEqoF5/I8mJCl292g0ly+sJRALqQfO/AdfNqkwmobLmE8qWRXtY/JIMk8sDVjZf
pZxVwvIX5el9kj2ylOvV3ZHCiMdf9fS5iWJYJMEtX4MUWNOhht3dRlEGLBCKItRI
76TdOkuc3qsxaE2IwsJCilsrKwAnWI0dWHRP9JUmTn4WHb+1zoBGiik0n+wd3WCW
MG6/IBe3rbWhV/zuOG9zYE1F9HALPkepBxjmXOcqKdJv6nAH82PCNwIDAQABo4IB
KTCCASUwOAYDVR0RBDEwL4ItYWxleC5jM3Qya2xnNWEyd3MudXMtZWFzdC0xLnJk
cy5hbWF6b25hd3MuY29tMIG9BgNVHSMEgbUwgbKAFPqhoWZcrVY9mU7tuemRRBnQ
Ij1joYGVpIGSMIGPMQswCQYDVQQGEwJVUzEQMA4GA1UEBwwHU2VhdHRsZTETMBEG
A1UECAwKV2FzaGluZ3RvbjEiMCAGA1UECgwZQW1hem9uIFdlYiBTZXJ2aWNlcywg
SW5jLjETMBEGA1UECwwKQW1hem9uIFJEUzEgMB4GA1UEAwwXQW1hem9uIFJEUyBS
b290IDIwMTkgQ0GCAiVVMCkGA1UdDgQiBCB9A8SBoTiasO5eFwashFrepkH90IN6
GWfElbGhFGhiATANBgkqhkiG9w0BAQsFAAOCAQEAcP2AktQ9VOVrb8tJsU0XbMi3
HRw/8YJIBCUMrGcLjSAaVCVQK9rLuGwSljigIB3ojxpyr9A4y3ko7MLsOyLazYi+
5qm4GSVPaPQpajRIhQiZNveqEPRQqfggmD7rb4vFvFmlp4ad4uWqFZi3Nyurx2yz
89dT4zoVIcVrX/tTR+EgJ+dXSyijT9mRfXqJwtTYCv934B9naL4XuU9aT5A3EFwY
IDA694NnWHKgBnMiW6LI3Ri92I33GbRAA5eveqX0IWKg9+dXjLhFq5EYs6pn/PsV
uoKomoVKzu8ymwSdVV/V3CW60MvxBFyAZ9z4nW0lnEm73fLYl068G+LxBqhF2g==
-----END CERTIFICATE-----
subject=CN = alex.c3tXXXX2ws.us-east-1.rds.amazonaws.com, OU = RDS, O = Amazon.com, L = Seattle, ST = Washington, C = US

issuer=C = US, ST = Washington, L = Seattle, O = "Amazon Web Services, Inc.", OU = Amazon RDS, CN = Amazon RDS us-east-1 2019 CA

---
No client certificate CA names sent
Peer signing digest: SHA384
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3820 bytes and written 473 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 62E7523D8475208384A3F0576ABA8BB873A5DCF8DAE408576CC88CA22A7296D0
    Session-ID-ctx:
    Master-Key: D0EF83E3EF4BB29D776057026DF42173A90A2C8F8147BEFF866EAD75175C05A4E76715408E6E0A79E7D1AC60A08F7369
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1692384202
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```
Yet no matter what I try I get the same error in node-oracledb:
```
Error: NJS-506: connection to host 172.16.2.105 port 2484 encountered TLS handshake failure. (CONNECTION_ID=vtZwR4E50wXbFY62kaBU6A==)
self signed certificate in certificate chain
    at Object.throwErr (/opt/confwizard/node_modules/oracledb/lib/errors.js:592:10)
    at NTTCP.tlsConnect (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/ntTcp.js:125:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NTTCP.connect (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/ntTcp.js:224:9)
    at async NetworkSession.transportConnect (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/networkSession.js:176:5)
    at async NetworkSession.connect2 (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/networkSession.js:214:7)
    at async NetworkSession.connect1 (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/networkSession.js:317:23)
    at async NetworkSession.connect (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/networkSession.js:524:5)
    at async ThinConnectionImpl.connect (/opt/confwizard/node_modules/oracledb/lib/thin/connection.js:509:5)
    at async Object.getConnection (/opt/confwizard/node_modules/oracledb/lib/oracledb.js:628:3)
Error: NJS-506: connection to host 172.16.2.105 port 2484 encountered TLS handshake failure. (CONNECTION_ID=vtZwR4E50wXbFY62kaBU6A==)
self signed certificate in certificate chain
    at Object.throwErr (/opt/confwizard/node_modules/oracledb/lib/errors.js:592:10)
    at NTTCP.tlsConnect (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/ntTcp.js:125:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NTTCP.connect (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/ntTcp.js:224:9)
    at async NetworkSession.transportConnect (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/networkSession.js:176:5)
    at async NetworkSession.connect2 (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/networkSession.js:214:7)
    at async NetworkSession.connect1 (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/networkSession.js:317:23)
    at async NetworkSession.connect (/opt/confwizard/node_modules/oracledb/lib/thin/sqlnet/networkSession.js:524:5)
    at async ThinConnectionImpl.connect (/opt/confwizard/node_modules/oracledb/lib/thin/connection.js:509:5)
    at async Object.getConnection (/opt/confwizard/node_modules/oracledb/lib/oracledb.js:628:3)
POST /oracledbtest 200 74.480 ms - 65
```
5. What have I tried:
* Numerous ways to try to connect to the DB.  I have tried adding (SSL_SERVER_DN_MATCH=OFF) to the connect string.
* I have tried adding ssl_server_dn_match : FALSE to the router.
* Tried running the certificate import script AWS offers here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html#UsingWithRDS.SSL-certificate-rotation-sample-script
* Various node side settings do disable cert validation like export NODE_TLS_REJECT_UNAUTHORIZED='0'.

I just cant get this host to connect to a TLS port.  This all worked about 6 months ago when I wrote it.  Did something change on the Oracle or node-oracledb side to not allow TLS connections via the trust store?  Configuring a wallet is not an option for me unfortunately.  There is not much information on Error: NJS-506 on the internet unfortunately.

**Comment by cjbj** [comment]
What's the actual [node-oracledb version](https://raw.githubusercontent.com/oracle/node-oracledb/main/examples/version.js)?  (`npm -v oracledb` just gives the npm version).

Six month ago you would have been using node-oracledb 5 and so all the network connectivity/security was handled by Oracle Client libraries.  In node-oracledb 6 those libraries are optional - and you haven't opted in.  One potential workaround for the moment could be to enable the 'Thick' mode and continue using Oracle Client libraries, see [Enabling node-oracledb Thick Mode on Linux and Related Platforms](https://node-oracledb.readthedocs.io/en/latest/user_guide/initialization.html#enabling-node-oracledb-thick-mode-on-linux-and-related-platforms).  Or perhaps grab the latest code from GitHub and see if any of the DN changes help.  I'll ask our Net team to comment.

**Comment by agregory23** [comment]
Thanks for the reply @cjbj ... I actually found something that seems to also have worked.  There is a new enviornment variable that was introduced (maybe with node-oracledb 6?) and seems to have worked if I set.  If I take the global bundle from AWS of all their public certs and put in this variable, magic happens:

export NODE_EXTRA_CA_CERTS=/etc/pki/ca-trust/source/anchors/global-bundle.pem
combine that with:
curl -L --silent https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -o /etc/pki/ca-trust/source/anchors/global-bundle.pem
and I am good to go!

**Comment by cjbj** [comment]
Thanks for sharing the solution. For the record, NODE_EXTRA_CA_CERTS is a [Node.js environment variable ](https://nodejs.org/api/cli.html#node_extra_ca_certsfile), not specifically for node-oracledb.  However node-oracledb 6's default Thin mode uses Node.js's [crypto](https://nodejs.org/api/crypto.html) module, but does not use it for Thick mode or node-oracledb 5.5.

**Comment by sathish-skb** [comment]
Thank you all. This conversation helped me a lot. We were connecting RDS from node. Adding certificates NODE_EXTRA_CA_CERTS=/etc/pki/ca-trust/source/anchors/global-bundle.pem solved this issue.
