### ISSUE TITLE
NJS-103: Unexpected error on fetchMoreRows

### ISSUE THREAD

**Issue by manibhushan** [oracle/node-oracledb#1661]
1. What versions are you using?
    Database Version - Oracle Database 19c Enterprise Edition Release 19.0.0.0.0

    process.platform - linux
    process.version - 382v20.12.1
    process.arch - 383x64
    require('oracledb').versionString - 6.4.0
    require('oracledb').oracleClientVersionString - undefined

2. Is it an error or a hang or a crash? - error

3. What error(s) or behavior you are seeing?

```
Error: NJS-103: unexpected message type 1 received at position 11 of packet 594
    at Object.throwErr (/opt/server/node_modules/oracledb/lib/errors.js:617:10)
    at FetchMessage.processMessage (/opt/server/node_modules/oracledb/lib/thin/protocol/messages/base.js:216:14)
    at FetchMessage.processMessage (/opt/server/node_modules/oracledb/lib/thin/protocol/messages/withData.js:91:13)
    at FetchMessage.process (/opt/server/node_modules/oracledb/lib/thin/protocol/messages/base.js:195:12)
    at FetchMessage.decode (/opt/server/node_modules/oracledb/lib/thin/protocol/messages/base.js:186:10)
    at Protocol._decodeMessage (/opt/server/node_modules/oracledb/lib/thin/protocol/protocol.js:78:17)
    at async Protocol._processMessage (/opt/server/node_modules/oracledb/lib/thin/protocol/protocol.js:153:9)
    at async ThinResultSetImpl._fetchMoreRows (/opt/server/node_modules/oracledb/lib/thin/resultSet.js:44:5)
    at async ThinResultSetImpl.getRows (/opt/server/node_modules/oracledb/lib/thin/resultSet.js:104:9)
    at async ResultSet._getRows (/opt/server/node_modules/oracledb/lib/resultset.js:107:12)
    at async ResultSet.getRows (/opt/server/node_modules/oracledb/lib/resultset.js:298:23)
    at async ResultSet.<anonymous> (/opt/server/node_modules/oracledb/lib/util.js:165:14)
    at async ResultSet.<anonymous> (/opt/server/node_modules/oracledb/lib/util.js:179:14)
    at async /opt/server/src/services/invoice-sync/orchestrate-invoice-sync.service.js:40:16
    at async /opt/server/src/services/invoice-sync/begin-scheduled-invoice-sync.service.js:63:13 {
  code: 'NJS-103'
```

4. Include a runnable Node.js script that shows the problem.

Getting the issue while running this query

```
SELECT
  PAYMENT_DATE , INVOICE_NO , PO_NUMBER , INVOICE_AMOUNT, DUE_DATE ,
  INVOICE_STATUS , PAYMENT_AMOUNT , CHECK_AMOUNT , CHECK_NO ,
  VENDOR_ID , INVOICE_DATE , PAYMENT_CURRENCY , SOURCE , CURRENCY ,
  DISCOUNT_DUE_DATE , RECEIVED_DATE, CARRIER_ID, UPDATE_DATE,
  SEGMENT_TYPE, TRANSPORT_MODE, LAST_INVOICE_OPERATIONS_REMARK
FROM
  ERPCUSTOBJS.ERP_OTM_SHP_INV_VW
WHERE
  (CARRIER_ID, 0) IN (('', 0), ('1001565', 0), ('1011907', 0))
AND ((SOURCE IN ('OTHER') AND (SEGMENT_TYPE IN ('HWY', 'DRC', 'MAT', 'DDR', 'LHL', 'ORC', 'CLA', 'SPT', 'EQP', 'ODR', 'ACR', 'NMV', 'MSC', 'XTN')))
OR (SOURCE IN ('OTHER-UYSN', 'OTHER-INS', 'OTHER-LGS')))
AND UPDATE_DATE >= TIMESTAMP '2024-04-01 00:03:57'
AND INVOICE_STATUS <> 'Voided'
```
Additional info:

- All the column types are Number, VARCHAR2, DATE.

- Application flow - We have two systems one of which uses SQL DB while the other uses Mongo DB. For our application requirements these two DBs need to be in sync. We have a job that runs and reads data from the SQL DB using the oracledb package and then populates in the MongoDB. The read op on SQL DB happens in batches. The query above returns a resultSet on which we further run the fetchMoreRows method to get next set of rows for batch processing.
There are no writes on the SQL DB in the entire process.

- The size of rows is not much, the table contains simple data.

**Comment by sudarshan12s** [comment]
@manibhushan ,
Can you let us know your findings with enabling thick mode,  `initOracleClient`

**Comment by sharadraju** [comment]
I am closing this as there is no response.
Please feel free to reopen this, when you are able to provide us your findings with enabling thick mode using `initOracleClient()`
