### ISSUE TITLE
node-oracledb 6.7 is now available

### ISSUE THREAD

**Issue by sharadraju** [oracle/node-oracledb#1705]
See the [release announcement](https://medium.com/@sharad-chandran/node-oracledb-6-7-brings-more-flexibility-and-power-to-oracle-database-apps-a3c315738864) and [release notes](https://node-oracledb.readthedocs.io/en/latest/release_notes.html) for details.
This release brings OpenTelemetry support, settable session attributes, enhanced Centralized Configuration provider and CQN support. In addition, it also provides multiple bug fixes for the previous 6.x.x releases, including the patches provided for the issues raised by our users. Thank you for reporting the issues promptly!

Pre-built binaries are available for Node.js 14.6 or later.

Windows 64-bit (x64) (built with VS 2017)
macOS 64-bit (Intel x64)
macOS ARM 64-bit
Linux 64-bit (x86-64) (built on Oracle Linux 7)
Linux ARM 64-bit

For other environments, refer to [INSTALL](https://node-oracledb.readthedocs.io/en/latest/user_guide/installation.html) on building from source code.

**Comment by Luk4h** [comment]
Hello! I was working on a simple Docker image, and I am getting errors on a simple `bun install`, which I am not getting on version 6.6. I am not sure about others, but I have a dozen of apps that use bun to install dependencies just because we use them in development. **This is currently BREAKING! And needs a fix!**
Error:
```sh
bun install v1.1.38 (bf2f153f)
170 |     return;
171 |   }
172 | 
173 |   // Fill the traceContext.
174 |   if (err) {
175 |     traceContext.error = Object.assign(({}, err));
      ^
SyntaxError: Unexpected token ','
      at <parse> (/app/node_modules/oracledb/lib/util.js:175:1)
      at anonymous (native:1:1)
      at /app/node_modules/oracledb/package/install.js:99:18
      at native:11:43

Bun v1.1.38 (Linux x64 baseline)

error: install script from "oracledb" exited with 1
```

For reproduction:
`index.js`
```js
imports...
initOracleClient();
const pool = await createPool({...})
const conn = await pool.getConnection()
await conn.ping();
await conn.close();
await pool.close();
```

`package.json`
```json
{
    "name": "node",
    "module": "index.js",
    "type": "module",
    "dependencies": {
        "oracledb": "^6.7.0"
    }
}
```

`Dockerfile`
```Dockerfile
FROM oven/bun AS deps

WORKDIR /app
COPY package.json bun.lock* ./

RUN  bun install --frozen-lockfile;
...
```

**Comment by sharadraju** [comment]
@Luk4h This has already been reported in 6.7 See https://github.com/oracle/node-oracledb/issues/1707 
You can take the patch provided there. It will be fixed in the next patch release

**Comment by Luk4h** [comment]
My apologies, the default filter `is:open` has betrayed me again.
