### ISSUE TITLE
node-oracledb doesn't install with io.js 3.0

### ISSUE THREAD

**Issue by lostinplace** [oracle/node-oracledb#172]
this is important since the new node v4 will be proceeding from the apis in io v3

using `npm install oracledb`  on io.js v3 yields:

    ➜  fuel-fraud-extract git:(master) ✗ npm install oracledb
    npm WARN package.json fuel-fraud-extract@1.0.0 No description
    npm WARN package.json fuel-fraud-extract@1.0.0 No repository field.
    npm WARN package.json fuel-fraud-extract@1.0.0 No README data
    \
    > oracledb@1.0.0 install /Users/cwheeler/dev/git/fuel-fraud-extract/node_modules/oracledb
    > node-gyp rebuild
    
    CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
    In file included from ../src/njs/src/njsOracle.cpp:53:
    In file included from ../src/njs/src/njsOracle.h:56:
    ../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
    NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
    ^
    ../node_modules/nan/nan.h:319:17: note: previous definition is here
    v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
    ^
    ../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
    NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
    ^
    ../node_modules/nan/nan.h:334:27: note: previous definition is here
    NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
    ^
    ../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
    ~~~~~~^
    ../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
    ^~~~~~~~~~~~~~~~~
    /Users/cwheeler/.node-gyp/3.0.0/include/node/node_buffer.h:35:40: note: candidate function not viable: no known conversion from 'uint32_t'
    (aka 'unsigned int') to 'enum encoding' for 3rd argument
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/node_buffer.h:47:40: note: candidate function not viable: 2nd argument ('const char *') would lose const
    qualifier
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/node_buffer.h:32:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/node_buffer.h:40:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
    ^
    In file included from ../src/njs/src/njsOracle.cpp:53:
    In file included from ../src/njs/src/njsOracle.h:56:
    ../node_modules/nan/nan.h:772:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
    'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
    class Local {
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
    'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
    class Local {
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
    V8_INLINE Local(Local<S> that)
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:327:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
    V8_INLINE Local(S* that)
    ^
    In file included from ../src/njs/src/njsOracle.cpp:53:
    In file included from ../src/njs/src/njsOracle.h:56:
    ../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
    ~~~~~~~~~~~~~~^
    ../src/njs/src/njsOracle.cpp:760:11: warning: 'FatalException' is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
    node::FatalException(tc);
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/node.h:283:29: note: 'FatalException' has been explicitly marked deprecated here
    inline void FatalException(const v8::TryCatch& try_catch) {
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
    ^
    ../src/njs/src/njsOracle.cpp:913:11: warning: 'FatalException' is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
    node::FatalException (tc);
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/node.h:283:29: note: 'FatalException' has been explicitly marked deprecated here
    inline void FatalException(const v8::TryCatch& try_catch) {
    ^
    /Users/cwheeler/.node-gyp/3.0.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
    ^
    In file included from ../src/njs/src/njsOracle.cpp:51:
    In file included from /Users/cwheeler/.node-gyp/3.0.0/include/node/node.h:42:
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
    ^ ~~~~~~~~~~~~~~~~~~
    ../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
    ^
    ../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
    ^
    In file included from ../src/njs/src/njsOracle.cpp:51:
    In file included from /Users/cwheeler/.node-gyp/3.0.0/include/node/node.h:42:
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
    ^ ~~~~~~~~~~~~~~~~~~
    ../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
    ^
    ../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
    ^
    In file included from ../src/njs/src/njsOracle.cpp:51:
    In file included from /Users/cwheeler/.node-gyp/3.0.0/include/node/node.h:42:
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
    ^ ~~~~~~~~~~~~~~~~~~
    ../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
    ^
    ../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
    ^
    In file included from ../src/njs/src/njsOracle.cpp:51:
    In file included from /Users/cwheeler/.node-gyp/3.0.0/include/node/node.h:42:
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
    /Users/cwheeler/.node-gyp/3.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
    ^ ~~~~~~~~~~~~~~~~~~
    ../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
    ^
    ../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
    ^
    2 warnings and 10 errors generated.
    make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/cwheeler/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 14.4.0
    gyp ERR! command "/Users/cwheeler/.nvm/versions/io.js/v3.0.0/bin/iojs" "/Users/cwheeler/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/cwheeler/dev/git/fuel-fraud-extract/node_modules/oracledb
    gyp ERR! node -v v3.0.0
    gyp ERR! node-gyp -v v2.0.2
    gyp ERR! not ok
    npm ERR! Darwin 14.4.0
    npm ERR! argv "/Users/cwheeler/.nvm/versions/io.js/v3.0.0/bin/iojs" "/Users/cwheeler/.nvm/versions/io.js/v3.0.0/bin/npm" "install" "oracledb"
    npm ERR! node v3.0.0
    npm ERR! npm  v2.13.3
    npm ERR! code ELIFECYCLE
    
    npm ERR! oracledb@1.0.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the oracledb@1.0.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the oracledb package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls oracledb
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/cwheeler/dev/git/fuel-fraud-extract/npm-debug.log
    ➜  fuel-fraud-extract git:(master) ✗

**Comment by lostinplace** [comment]
this is not an issue for io.js 2.5

**Comment by cjbj** [comment]
This was predicted in https://github.com/oracle/node-oracledb/issues/115#issuecomment-130495301 and noted in the release announcement https://blogs.oracle.com/opal/entry/node_oracledb_goes_1_0
It's on the ToDo list. Thanks for the report.
