### ISSUE TITLE
Bundling native dependencies in Electron github application

### ISSUE THREAD

**Issue by RaviVaranasi** [oracle/node-oracledb#176]
Anyone tried bundling the native dependencies in an electron github app (http://electron.atom.io/) ?

**Comment by jrop** [comment]
@RaviVaranasi I just got this working, and wrote a (very sloppy) blog-post of how I got it working [here](http://jigantic.blogspot.com/2015/08/get-atom-shell-electron-working-with.html).

I have since figured out a cleaner version of this process:

1. `npm i --save electron-rebuild`
2. Add this to your `package.json`:
    * `"scripts": { "postinstall": "./node_modules/.bin/electron-rebuild" }`
3. `rm -rf node_modules`
4. `npm install`

**Comment by RaviVaranasi** [comment]
@jrop do you bundle all the instant client native dependencies under node_modules ?

**Comment by jrop** [comment]
@RaviVaranasi no, I installed the instant client on my machine as per the instructions [here](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx) (I am on OSX).  Once the environment variables, etc. are setup, it apparently knows where to find the needed libs.  I am not an Oracle expert, though, sorry!

**Comment by cjbj** [comment]
@jrop thanks for sharing.  I'm looking forward to seeing more blog posts.

**Comment by danielmhair** [comment]
@RaviVaranasi thank you for asking about this. @jrop thank you for answering! It gives me hope that someone has fixed this before. I have been working over 7+ hours on this error. I am trying to figure out why I am still getting this error.

I followed your suggestions, @jrop which got me further, but I am getting quite a bit of errors. If you don't want to look at the full stack trace, then here is the summary:
```
[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ Error: Command failed: "C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\.bin\node-pre-gyp.cmd" install --fallback-to-build=false
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Empty target version is not supported if electron is the target.
```

If you need the full stack trace; here it is.
```
npm install
npm WARN deprecated jws@1.0.1: Security update: Versions below 3.0.0 are deprecated.
npm WARN prefer global npm@3.9.6 should be installed with -g

> nslog@3.0.0 install C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nslog
> node-gyp rebuild


C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
  win_delay_load_hook.c
     Creating library C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nslog\build\Release\nslog.lib and object C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nslog\build\Release\nslog.exp
  Generating code
  Finished generating code
  nslog.vcxproj -> C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nslog\build\Release\\nslog.node

> nodegit@0.13.2 install C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ Error: Command failed: "C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\.bin\node-pre-gyp.cmd" install --fallback-to-build=false
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Empty target version is not supported if electron is the target.
node-pre-gyp ERR! stack     at get_electron_abi (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\node-pre-gyp\lib\util\versioning.js:26:15)
node-pre-gyp ERR! stack     at get_runtime_abi (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\node-pre-gyp\lib\util\versioning.js:73:16)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\node-pre-gyp\lib\util\versioning.js:277:19)
node-pre-gyp ERR! stack     at install (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\node-pre-gyp\lib\install.js:148:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\node-pre-gyp\lib\node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\node-pre-gyp\bin\node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\node-pre-gyp\bin\node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:541:32)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:550:10)
node-pre-gyp ERR! stack     at Module.load (module.js:458:32)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hair4\\Projects\\chemtrack-sds-search\\node_modules\\nodegit\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nodegit
node-pre-gyp ERR! node -v v6.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\Users\\hair4\\Projects\\chemtrack-sds-search\\node_modules\\nodegit\\node_modules\\.bin\\node-pre-gyp.cmd" install --fallback-to-build=false' }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
...
[nodegit] Everything is ready to go, attempting compilation
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v6.2.1/node-v6.2.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\node-gyp\lib\install.js:244:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\nodegit\node_modules\request\request.js:977:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:469:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:359:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hair4\\Projects\\chemtrack-sds-search\\node_modules\\nodegit\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\hair4\Projects\chemtrack-sds-search\node_modules\nodegit
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
...
npm WARN chemtrack-sds-search@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.13.2 install: `node lifecycleScripts/install`
npm ERR! Exit status 13
npm ERR!
npm ERR! Failed at the nodegit@0.13.2 install script 'node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hair4\Projects\chemtrack-sds-search\npm-debug.log
```

Any ideas on how to solve this?

**Comment by danielmhair** [comment]
I try to put in the target version in my .npmrc, but it breaks npm because when I do anything dealing with `npm install`, it always errors out until I remove this (especially with node-gyp)

**Comment by cjbj** [comment]
The first error doesn't look like a node-oracledb issue. (Or is it coming from #18?)

Have you checked #449 which leads to https://github.com/electron/electron/issues/5851 pointing out some issues with Electron's ABI.  This seems to be a source of pain.

**Comment by danielmhair** [comment]
I think your right. I don't think it's coming from #18.

I haven't looked into #449 and electron/electron#5851. I will look into it and see if that resolves it. I sure hope this is the solution. I appreciate your help.

**Comment by danielmhair** [comment]
@cjbj Thank you so much for fixing this error by directing me to #449. So here is an update. 

I realized that I did not give you the entire details about the core issue I was having. When I ran `electron main.js`, it would show this error:
```
[2016-06-21 13:53:09.609] [ERROR] console - App threw an error during load
[2016-06-21 13:53:09.610] [ERROR] console - Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\oracledb\lib\oracledb.js:32:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
```

After running `npm install --save-dev electron-rebuild` and `npm install --save-dev electron-rebuilt` (I had electron-rebuilt installed before), I ran the command [suggested by @irfannuri](https://github.com/oracle/node-oracledb/issues/449#issuecomment-226706754) about running `node_modules/.bin/electron-rebuild -f -w oracledb`. At first, I got errors with this command, until I added these to my `.npmrc` file:
```
runtime = electron
target_arch = x64
target = 1.2.3
disturl = https://atom.io/download/atom-shell
progress = true
```
Previously, I didn't have `target = 1.2.3` because I can't run `npm install` with the target in the `.npmrc` because it gives many errors. So every time I run electron-rebuilt or anything electron, I have to add `target=1.2.3` and whenever I do an `npm install`, I have to remove it...

That being said, after running the command, I ran `electron main.js` again and that error is now solved! However, now, I am getting this error:

**NOTE: Keep in mind that this is most likely an electron issue, but I want to post it here with a *full* update.

![image](https://cloud.githubusercontent.com/assets/7373734/16270105/f012f11a-3849-11e6-86e3-7bb3338c2512.png)

Any ideas @cjbj or what the main issue with this is?
