### ISSUE TITLE
Not connection oracle 10.2.5 using 11.2 instant client

### ISSUE THREAD

**Issue by jcsena** [oracle/node-oracledb#181]
```
util.js:355
  desc = Object.getOwnPropertyDescriptor(value, key) || { value: value[key] };
                ^
Error: NJS-015: action is a write-only property
    at Function.getOwnPropertyDescriptor (native)
    at formatProperty (util.js:355:17)
    at util.js:294:14
    at Array.map (native)
    at formatValue (util.js:293:19)
    at inspect (util.js:140:10)
    at Console.exports.format (util.js:27:20)
    at Console.log (console.js:53:34)
```

**Comment by cjbj** [comment]
What's the question?  What did you install?  What did you run?

```
$ node db102.js 
Executing "select * from v$version"
[ { name: 'BANNER' } ]
[ [ 'Oracle Database 10g Express Edition Release 10.2.0.1.0 - Product' ],
  [ 'PL/SQL Release 10.2.0.1.0 - Production' ],
  [ 'CORE\t10.2.0.1.0\tProduction' ],
  [ 'TNS for Linux: Version 10.2.0.1.0 - Production' ],
  [ 'NLSRTL Version 10.2.0.1.0 - Production' ] ]
```

Also see https://github.com/oracle/node-oracledb/issues/175

**Comment by jcsena** [comment]
@cjbj yes is the solution, i using console.log(connection) and the error is caused by that. thx
