### ISSUE TITLE
not working in node.js v4.0.0

### ISSUE THREAD

**Issue by sukjin** [oracle/node-oracledb#212]
node.js announced Ver 4.0.0 

I upgraded it, and run oracle modules, but it wasn't working.

this is error message.

C:\.......\node_modules\oracledb\lib\oracledb.js:28
    throw err;

Error: The specified procedure could not be found.
C:\Users\user\Desktop\abcd\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\user\Desktop\abcd\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/202
