### ISSUE TITLE
install oracledb without Visual Studio in Windows

### ISSUE THREAD

**Issue by sukjin** [oracle/node-oracledb#213]
is it way to install node-oracledb without Visual Studio ?

I have a license issues to install VS(visual Studio) on my Windows Server(2008)

so I can not install VS, but I want to use my app.js using node-oracledb

**Comment by cjbj** [comment]
@sukjin node-oracledb is curently only distributed as source code.  You may be able to copy a binary from another Windows machine, if you have one.  See https://github.com/oracle/node-oracledb/issues/189#issuecomment-137874533

**Comment by sukjin** [comment]
I tried it.

but oracledb.js give me a error


here is error code.

C:\Users\Administrator\Desktop\abcd\node_modules\oracledb\lib\oracledb.js:28
    throw err;
          ^
Error: %1 is not a valid Win32 application.
C:\Users\Administrator\Desktop\abcd\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\abcd\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)


what is '%1 is not a valid Win32 application.' error?

**Comment by sukjin** [comment]
I found it.

instantclient is crashed. so module didn't run on time.
(I re-download instantclient and it works good.)
thanks.

**Comment by cjbj** [comment]
For the record the error was also reported in the repo before when there was an incorrect mix of 32 & 64 bit binaries.
