### ISSUE TITLE
How to run tests from installation directory

### ISSUE THREAD

**Issue by doberkofler** [oracle/node-oracledb#233]
I'm starting to get acquainted with the project and after having successfully build node-oracledb, I would like to run the test suite from within the installation directory.

I'm able to run the tests after creating a separate node-oracledb installation but to from within the directory where I build and get the following error stack and was wondering what I overlooked:
```
>npm run testWin

> oracledb@1.2.0 testWin D:\MyDev\doberkofler\node-oracledb
> node node_modules\mocha\bin\mocha -R spec --timeout 10000 test\*.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\MyDev\doberkofler\node-oracledb\test\accessTerminatedPoolAttributes.js:35:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at D:\MyDev\doberkofler\node-oracledb\node_modules\mocha\lib\mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (D:\MyDev\doberkofler\node-oracledb\node_modules\mocha\lib\mocha.js:189:14)
    at Mocha.run (D:\MyDev\doberkofler\node-oracledb\node_modules\mocha\lib\mocha.js:422:31)
    at Object.<anonymous> (D:\MyDev\doberkofler\node-oracledb\node_modules\mocha\bin\_mocha:398:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by doberkofler** [comment]
My mistake. Forgot to npm link `oracledb` and not `node-oracledb`

**Comment by cjbj** [comment]
@doberkofler Do you have steps you want added to https://github.com/oracle/node-oracledb/blob/master/test/README.md ?

**Comment by doberkofler** [comment]
@cjbj It could be helpful to explain why and how to setup the forked directory using `npm link`

**Comment by cjbj** [comment]
@doberkofler do you have some text that explains it?

**Comment by doberkofler** [comment]
@cjbj I not sure, if the instruction for people that want to contribute should not generally be in a separate document. Nevertheless I would just use the documentation provided by hmp itself and add something like this:

---

### 4. Create a package link

If you want to use the oracledb package from within this directory you most likely want to use a package link.

Package linking is a two-step process.
* First, npm link in a package folder will create a globally-installed symbolic link from prefix/package-name to the current folder.
* Next, in some other location, npm link package-name will create a symlink from the local node_modules folder to the global symlink.

Create the needed links for oracledb as follows:
```
npm link
npm link oracledb
```

**Comment by cjbj** [comment]
@doberkofler I was originally thinking just documenting this for the test set up.  But we could a 'developer' section to INSTALL.md?

**Comment by doberkofler** [comment]
@cjbj Depending on how important code contributions are, that would definitively be a good idea. One of the projects I have been contributing to, is eslint. I think Nicholas did a very good job in his http://eslint.org/docs/developer-guide/contributing section.
