### ISSUE TITLE
oracledb needed for both windows and linux

### ISSUE THREAD

**Issue by vrmerlin** [oracle/node-oracledb#264]
I have a project that is being developed on Windows, but being deployed onto Linux. I was able to get oracledb installed and working while developing on  Windows. I then took the code to Linux, and re-installed the oracledb into the project, hoping it would add Linux build stuff that made oracledb work on Linux. It did. But, when I went back to Windows, I got this error when I tried to run:

    c:\Users\fisher23\IdeaProjects\SDSAppSample\node_modules\oracledb\lib\oracledb.js:28
        throw err;
          ^
    Error: %1 is not a valid Win32 application.
    c:\Users\fisher23\IdeaProjects\SDSAppSample\node_modules\oracledb\build\Release\oracledb.node
        at Error (native)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous>     (c:\Users\fisher23\IdeaProjects\SDSAppSample\node_modules\oracledb\lib\oracledb.js:23:15)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)

How do i get oracledb installed into my project, working on both Windows and Linux?

Thanks,
John

**Comment by bchr02** [comment]
Try using my fork which has pre built binaries for both Linux and Windows. But you must be using node 12.7

**Comment by vrmerlin** [comment]
Ok, where do I find that?

**Comment by vrmerlin** [comment]
Actually, I was able to get this working by:

- Modifying the oracledb package.json twice, to change it's name (oracledb-win, oracledb-linux), and installing it twice (once on each platform).

- Editing the several files in the orawrap to do a conditional load of the oracledb library, depending on the value of the proces.platform variable.
