### ISSUE TITLE
CentOS 6.6 Build error on installation

### ISSUE THREAD

**Issue by dayney** [oracle/node-oracledb#290]
Hi,there

installed node-oracledb with `CentOS6.6` `Node v4.2.2` `Npm v2.14.7` 

## Step1 - rpm
```shell
rpm -ivh oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
rpm -ivh oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm
```

## Step2 - upgrade gcc 
```shell
[root@localhost wxAdmin]# gcc --version
gcc (GCC) 4.8.1 20130715 (Red Hat 4.8.1-4)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Q: How to set C++11 is required ???

## Step3 - npm install oracledb in project's folder
build errors...

```shell
[root@localhost wxAdmin]# npm install oracledb
\
> oracledb@1.4.0 install /home/workspaces/wxAdmin/node_modules/oracledb
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/workspaces/wxAdmin/node_modules/oracledb/.node-gyp"
make: Entering directory `/home/workspaces/wxAdmin/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsPool.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsConnection.o
/home/workspaces/wxAdmin/node_modules/oracledb/ccn0Tazf.s: Assembler messages:
/home/workspaces/wxAdmin/node_modules/oracledb/ccn0Tazf.s:12442: Error: expecting string instruction after `rep'
make: *** [Release/obj.target/oracledb/src/njs/src/njsConnection.o] Error 1
make: Leaving directory `/home/workspaces/wxAdmin/node_modules/oracledb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodejs/node-v4.2.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64
gyp ERR! command "/home/nodejs/node-v4.2.2-linux-x64/bin/node" "/home/nodejs/node-v4.2.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/workspaces/wxAdmin/node_modules/oracledb
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! argv "/home/nodejs/node-v4.2.2-linux-x64/bin/node" "/home/nodejs/node-v4.2.2-linux-x64/bin/npm" "install" "oracledb"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/workspaces/wxAdmin/npm-debug.log

```

help!~

T^T

**Comment by cjbj** [comment]
NAN would have given a compilation error if your compiler wasn't C++11 compatible: https://github.com/nodejs/nan/blob/master/nan.h#L41

Have you got all the recent OS patches? Googling leads to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57017

FWIW, I have gcc (GCC) 4.8.3 on Oracle Linux 7.

**Comment by vkoster** [comment]
I can confirm that dev-tool versions are critical.
Had this very error too. Upgraded so that binutils is now 2.23.52.0.1
Now it builds.

**Comment by cjbj** [comment]
Thanks @vkoster.  I'll close this now.
