### ISSUE TITLE
oracledb.node causes error

### ISSUE THREAD

**Issue by kerosin** [oracle/node-oracledb#304]
Hi,

I did all preparations like
- Installed VS/MSBuild compiler + Python + Oracle Instant Client Base + SDK
- Added oracle instant client  folder to path
- Added system variable OCI_INC_DIR & OCI_LIB_DIR

But on starting my app (just a hello world with require oracledb) I get a error:

```
C:\Users\my.username\Desktop\node>node app.js
C:\Users\my.username\node_modules\oracledb\lib\oracledb.js:28
    throw err;
    ^

Error: error: 127\\?\C:\Users\my.username\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\my.username\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

My installation/build went through but gave some warning:

```
C:\Users\my.username\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Scha
lter "/m" hinzufügen.
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
  njsMessages.cpp
  njsIntLob.cpp
  dpiEnv.cpp
  dpiEnvImpl.cpp
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
..\src\njs\src\njsIntLob.cpp(617): warning C4456: declaration of 'msg' hides previous local declaration [C:\Users\my.username\node_modules\oracledb\build\oracledb.vcxproj]
  ..\src\njs\src\njsIntLob.cpp(614): note: see declaration of 'msg'
..\src\njs\src\njsIntLob.cpp(715): warning C4456: declaration of 'msg' hides previous local declaration [C:\Users\my.username\node_modules\oracledb\build\oracledb.vcxproj]
  ..\src\njs\src\njsIntLob.cpp(712): note: see declaration of 'msg'
..\src\njs\src\njsIntLob.cpp(719): warning C4456: declaration of 'msg' hides previous local declaration [C:\Users\my.username\node_modules\oracledb\build\oracledb.vcxproj]
  ..\src\njs\src\njsIntLob.cpp(712): note: see declaration of 'msg'
..\src\njs\src\njsConnection.cpp(533): warning C4457: declaration of 'index' hides function parameter [C:\Users\my.username\node_modules\oracledb\build\oracledb.vcxproj]
  ..\src\njs\src\njsConnection.cpp(502): note: see declaration of 'index'
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
  dpiLob.cpp
  dpiCommon.cpp
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(12): warning C4005: 'WIN32_LEAN_AND_MEAN
': macro redefinition [C:\Users\my.username\node_modules\oracledb\build\oracledb.vcxproj]
  C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(12): note: command-line arguments:  see previous definition of 'WIN32_LEAN_AND_MEAN'
     Creating library C:\Users\my.username\node_modules\oracledb\build\Release\oracledb.lib and object C:\Users\my.username\node_modules\oracledb\build\Release\oracledb.exp
  Generating code
  Finished generating code
  oracledb.vcxproj -> C:\Users\my.username\node_modules\oracledb\build\Release\\oracledb.node
oracledb@1.4.0 ..\..\node_modules\oracledb
└── nan@2.1.0
```

I Have no idea what could have been gone wrong :/

**Comment by cjbj** [comment]
What's the require line in app.js?  If you copy app.js to C:\Users\my.username, change the app to use '"require('oracledb'); " and run it there, does it work? Or perhaps you need to set NODE_PATH?  And check PATH contains your Instant Client (or desired Oracle libraries) before other Oracle libraries in PATH.

**Comment by kerosin** [comment]
require looks like ```var oracledb = require('oracledb');```

It now works. I defined OCI_INC_DIR & OCI_LIB_DIR as system variable and as user variable

**Comment by cjbj** [comment]
@kerosin you only need  OCI_INC_DIR & OCI_LIB_DIR during installation.  They can be unset when you run node.

**Comment by ukris** [comment]
Hello - I am still getting this error.
I have OCI_INC_DIR & OCI_LIB_DIR defined as both user and system variables.
Please help
