### ISSUE TITLE
Segmentation Fault after installing

### ISSUE THREAD

**Issue by FreakinaBox** [oracle/node-oracledb#371]
* **Node Version**: v4.3.2
* **Platform**: Darwin C02PVKVKG8WP 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64

I install oracledb and it compiles without error on OSX. including the lib in any project imidiatly returns a segmentation fault.

```
npm i oracledb
-
> oracledb@1.7.1 install /Users/.../projects/.../node_modules/oracledb
> node-gyp rebuild

  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsPool.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsConnection.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsResultSet.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsMessages.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsIntLob.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnv.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnvImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiException.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiExceptionImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiConnImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiDateTimeArrayImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiPoolImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiStmtImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiUtils.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiLob.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiCommon.o
  SOLINK_MODULE(target) Release/oracledb.node
oracledb@1.7.1 node_modules/oracledb
└── nan@2.1.0

node -e "require('oracledb')"
Segmentation fault: 11
```

**Comment by cjbj** [comment]
Got a stacktrace? Tried another version / distro of Node? Check you have the correct Instant Client (what do you have?)

I'm using Homebrew  Node 4.3.1 on OS X El Capitan (Darwin Kernel Version 15.3.0) just fine. 
@dmcghan stayed on Yosemite longer than me but wasn't seeing issues there at the time he upgraded.

**Comment by FreakinaBox** [comment]
I'm not sure how to get more verbose output from this. I am going to do the OSX update and see if that changes anything.

**Comment by FreakinaBox** [comment]
```
node -e "var SegfaultHandler = require('segfault-handler'); SegfaultHandler.registerHandler('crash.log'); require('oracledb')"
/Users/stephendahl/projects/application-repository-corporate-registration-portal/node_modules/oracledb/lib/oracledb.js:32
    throw err;
    ^

Error: dlopen(/Users/stephendahl/projects/application-repository-corporate-registration-portal/node_modules/oracledb/build/Release/oracledb.node, 1): no suitable image found.  Did find:
        /Users/stephendahl/projects/application-repository-corporate-registration-portal/node_modules/oracledb/build/Release/oracledb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/stephendahl/projects/application-repository-corporate-registration-portal/node_modules/oracledb/lib/oracledb.js:27:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by cjbj** [comment]
@FreakinaBox how did you install Instant Client?  Does Instant Client SQL*Plus work?

**Comment by FreakinaBox** [comment]
I installed the client following the instructions in this repos readme. I didn't install SQL Plus, I will go try that.

**Comment by FreakinaBox** [comment]
```
sqlplus
dyld: Library not loaded: /ade/dosulliv_sqlplus_mac/oracle/sqlplus/lib/libsqlplus.dylib
  Referenced from: /opt/oracle/instantclient/sqlplus
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by FreakinaBox** [comment]
I set ORACLE_HOME and linked its lib file to the global lib folder then sqlplus started working, I was getting a new error from `npm rebuild oracledb` (probably from all the tinkering trying to fix this) so I wiped everything and reinstalled from scratch. It is now working.
