### ISSUE TITLE
install error on Windows7 32bit

### ISSUE THREAD

**Issue by hyogacs** [oracle/node-oracledb#416]
Hi,I'm trying install node-oracledb,but something wrong happened.

**my env is:
windows7 32bit
python 2.7.11
nodejs 0.12.7(the same issue as with 4.2.6 and 4.4.3)
oracleinstantclient instantclient-basic-nt-12.1.0.2.0 and instantclient-sdk-nt-12.1.0.2.0**

I have met the wrong message as below.

C:\sai\nodejs\myapp>set OCI_LIB_DIR=C:\oracle\instantclient\sdk\lib\msvc
C:\sai\nodejs\myapp>set OCI_INC_DIR=C:\oracle\instantclient\sdk\include
C:\sai\nodejs\myapp>set path=C:\oracle\instantclient;%path%
C:\sai\nodejs\myapp>
C:\sai\nodejs\myapp>npm install oracledb
/
> oracledb@1.8.0 install C:\sai\nodejs\myapp\node_modules\oracledb
> node-gyp rebuild

C:\sai\nodejs\myapp\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin
\node-gyp.js" rebuild )  else (node  rebuild )
このソリューション内のプロジェクトを 1 度に 1 つずつビルドします。並行ビルドを有効にするには、"/m" スイッチを追加してください。
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
..\src\njs\src\njsOracle.cpp(51): fatal error C1083: include ファイルを開けません。'node.h':No such file or directory [C:\sai\nodejs\myapp\node_modules\oracledb
\build\ora
cledb.vcxproj]
..\src\njs\src\njsResultSet.cpp(50): fatal error C1083: include ファイルを開けません。'node.h':No such file or directory [C:\sai\nodejs\myapp\node_modules\oracl
edb\build\
oracledb.vcxproj]
c:\sai\nodejs\myapp\node_modules\oracledb\src\njs\src\njsConnection.h(55): fatal error C1083: include ファイルを開けません。'node.h':No such file or directory (
..\src\njs
\src\njsConnection.cpp) [C:\sai\nodejs\myapp\node_modules\oracledb\build\oracledb.vcxproj]
  njsMessages.cpp
  njsIntLob.cpp
  dpiEnv.cpp
..\src\njs\src\njsPool.cpp(51): fatal error C1083: include ファイルを開けません。'node.h':No such file or directory [C:\sai\nodejs\myapp\node_modules\oracledb\b
uild\oracl
edb.vcxproj]
  dpiEnvImpl.cpp
..\src\njs\src\njsIntLob.cpp(58): fatal error C1083: include ファイルを開けません。'node_buffer.h':No such file or directory [C:\sai\nodejs\myapp\node_modules\o
racledb\bu
ild\oracledb.vcxproj]
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
  dpiLob.cpp
  dpiCommon.cpp
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\sai\nodejs\myapp\node_modules\oracledb
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.8.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\sai\nodejs\myapp\npm-debug.log

C:\sai\nodejs\myapp>

**Does anybody help me?Thank you.**

**Comment by hyogacs** [comment]
Hi,everyone,I have solved it!!!
The problem is ,my user-account folder is not English name so that compiler cannot find the node.h and other src.
Chinese or Japnese users may meet the problem.
Hope help someone.
