### ISSUE TITLE
i want to make a test with examples:connect.js & dbconfig.js ,but error like this

### ISSUE THREAD

**Issue by SHocker-Yu** [oracle/node-oracledb#434]
Error: The specified procedure could not be found.
\\?\C:\Users\Administrator\Desktop\warehouse-midware\node_modules\oracledb\build
\Release\oracledb.node
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\warehouse-midware\node
_modules\oracledb\lib\oracledb.js:32:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by cjbj** [comment]
Not enough information was provided to help you.
Review https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin and #18

**Comment by SHocker-Yu** [comment]
the problem has resolved.i copy the all .dll application like oci.dll in the C:\instantclient_12_1 to my My project startup directory，i think it is the problem with run dependent ，thank u

**Comment by cjbj** [comment]
Thanks for letting us know.  Maybe setting PATH in the project would also have helped.
