### ISSUE TITLE
error using npm to install node oracledb on oracle xe

### ISSUE THREAD

**Issue by onwunandu** [oracle/node-oracledb#441]
tried installing node oracledb on windows 10 and it gave this error..ive successfully installed websocket and express, now i nid the oracledb...im using oracle11g xe wit OCI_INC_DIR=C:\oraclexe\app\oracle\product\11.2.0\server\oci\include
and 
OCI_LIB_DIR=C:\oraclexe\app\oracle\product\11.2.0\server\oci\lib\MSVC.
pls assist

**Comment by cjbj** [comment]
Review https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin

If you are OK with 3rd party binaries, look at #18.

**Comment by onwunandu** [comment]
i have gone thru d links severally but still get this error:

C:\Program Files (x86)\nodeoracledb\node-oracledb-master>npm install -g
npm ERR! fetch failed https://registry.npmjs.org/nan/-/nan-2.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/nan/-/nan-2.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/nan/-/nan-2.2.1.tgz
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall getaddrinfo

npm ERR! enoent getaddrinfo ENOENT registry.npmjs.org:443
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\nodeoracledb\node-oracledb-master\npm-debug.log

C:\Program Files (x86)\nodeoracledb\node-oracledb-master>

what am i doing wrong??

**Comment by cjbj** [comment]
What have you done to try and troubleshoot?  The error looks a like a problem getting  https://registry.npmjs.org/nan/-/nan-2.2.1.tgz

**Comment by onwunandu** [comment]
i followed d instructions for downloading n installing, so i dont even knw where to start troubleshooting....??

**Comment by onwunandu** [comment]
when i ran cmd not as admin, i got this error instead...


C:\Program Files (x86)\nodeoracledb\node-oracledb-master>npm install -g
/
> oracledb@1.8.0 install C:\Users\Owner\AppData\Roaming\npm\node_modules\oracledb
> node-gyp rebuild


C:\Users\Owner\AppData\Roaming\npm\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Owner\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj
(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" wa
s not found. Confirm that the path in the <Import> declaration is correct, and
that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Owner\AppData\Roaming\npm\node_modules\oracledb
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.8.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! path C:\Program Files (x86)\nodeoracledb\node-oracledb-master\npm-debug.log.3686074309
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Program Files (x86)\nodeoracledb\node-oracledb-master\npm-debug.log.3686074309'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Program Files (x86)\nodeoracledb\node-oracledb-master\npm-debug.log.3686074309']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Program Files (x86)\\nodeoracledb\\node-oracledb-master\\npm-debug.log.3686074309' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\nodeoracledb\node-oracledb-master\npm-debug.log

C:\Program Files (x86)\nodeoracledb\node-oracledb-master>

**Comment by cjbj** [comment]
What does google tell you about the error the log shows for C:\Microsoft.Cpp.Default.props? (I'm not a Windows user)

Are you consistently using 32 or 64 bit components?

**Comment by onwunandu** [comment]
Google says nothing about it...im using 64bit                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Christopher JonesSent: Wednesday, 1 June 2016 12:39 PMTo: oracle/node-oracledbReply To: oracle/node-oracledbCc: onwunandu; AuthorSubject: Re: [oracle/node-oracledb] error using npm to install node oracledb on oracle xe (#441)What does google tell you about the error the log shows for C:\Microsoft.Cpp.Default.props? (I'm not a Windows user)

Are you consistently using 32 or 64 bit components?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cjbj** [comment]
I found some google hits, even some for NPM. 
Perhaps if you give some details about your compiler version etc it would help.

**Comment by onwunandu** [comment]
i used visual studio 2013 community update 5, python 2.7.11, node
v4.4.3-x64....im installing on a windows 10 of Microsoft Surface Pro 2
tablet. thanks.

On Fri, Jun 3, 2016 at 12:18 AM, Christopher Jones <notifications@github.com

**Comment by pvenkatraman** [comment]
Is your internet connection uses proxy server(s)?  If so, can you set HTTP_PROXY & HTTPS_PROXY environment variable(s).

**Comment by onwunandu** [comment]
no, its not using proxy servers

**Comment by cjbj** [comment]
@onwunandu have you progressed anything further and tried other options?

**Comment by onwunandu** [comment]
Still trying, but haven't succeeded yet, but I want to try some things as last option, then revert.                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Christopher JonesSent: Tuesday, 14 June 2016 2:24 AMTo: oracle/node-oracledbReply To: oracle/node-oracledbCc: onwunandu; MentionSubject: Re: [oracle/node-oracledb] error using npm to install node oracledb on oracle xe (#441)@onwunandu have you progressed anything further and tried other options?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cjbj** [comment]
Closing due to lack of activity.
