### ISSUE TITLE
Alpine Support

### ISSUE THREAD

**Issue by nixgadget** [oracle/node-oracledb#476]
Has anyone been able to build and run oracledb on Alpine Linux ? I understand that Alpine by default is shipped with `musl libc` instead of `glibc`.

But perhaps makes effort worth it specially when it comes to the size of Alpine base package.

The issue that I seem to run into is,
```
Error: Error relocating /opt/oracle/drivers/instantclient/libclntsh.so.11.1: getcontext: symbol not found
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/oracledb/lib/oracledb.js:32:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/oracledb/index.js:1:80)
```

**Comment by kubo** [comment]
IMO, it is impossible.
Look at these comments(https://github.com/kubo/ruby-oci8/issues/129#issuecomment-213764956, https://github.com/kubo/ruby-oci8/issues/129#issuecomment-213798746).

**Comment by nixgadget** [comment]
Thats a bummer. Would've been ideal.
Ive tried to use the `glibc` libraries from https://github.com/sgerrand/alpine-pkg-glibc/releases but had no luck. Hence why I raised this.

**Comment by kubo** [comment]
I found that you had asked this issue at https://github.com/sgerrand/alpine-pkg-glibc/issues/31.
You should have added a link to the alpine-pkg-glibc issue.

Anyway, I guess that you uses node-js compiled for musl libc and uses node-oracledb compiled for glibc.
IMO, if you uses node-js compiled for glibc, it may work.
I'll add a comment to the alpine-pkg-glibc issue about why I guess so.

**Comment by cjbj** [comment]
This is an Oracle Client-thing out of scope for node-oracledb.  I'll track it separately.  Don't hold your breath.
