### ISSUE TITLE
New v0.4.1 error install on Oracle Linux 6.3

### ISSUE THREAD

**Issue by zorrofox** [oracle/node-oracledb#51]
I just want to move the project from desktop to test environment, and the detail information:
Oracle Linux 6.3 / node 0.10.5 / oracle instant client x64 12.1.0.2 / node-oracledb 0.4.1

```Shell
[web8070@m1-erp-apptest05 node-oracledb]$ npm install -g
\
> oracledb@0.4.1 install /home/web8070/soft/node/node-v0.10.35-linux-x86/lib/node_modules/oracledb
> node-gyp rebuild

make: Entering directory `/home/web8070/soft/node/node-v0.10.35-linux-x86/lib/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsPool.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsConnection.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsMessages.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnv.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnvImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiException.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiExceptionImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiConnImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiDateTimeArrayImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiPoolImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiStmtImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiUtils.o
  SOLINK_MODULE(target) Release/obj.target/oracledb.node
/usr/bin/ld: skipping incompatible /home/web8070/soft/instantclient_12_1/libclntsh.so when searching for -lclntsh
/usr/bin/ld: cannot find -lclntsh
collect2: ld returned 1 exit status
make: *** [Release/obj.target/oracledb.node] Error 1
make: Leaving directory `/home/web8070/soft/node/node-v0.10.35-linux-x86/lib/node_modules/oracledb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/web8070/soft/node/node-v0.10.35-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.39-200.24.1.el6uek.x86_64
gyp ERR! command "node" "/home/web8070/soft/node/node-v0.10.35-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/web8070/soft/node/node-v0.10.35-linux-x86/lib/node_modules/oracledb
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! oracledb@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracledb@0.4.1 install script.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.39-200.24.1.el6uek.x86_64
npm ERR! command "/home/web8070/soft/node/node-v0.10.35-linux-x86/bin/node" "/home/web8070/soft/node/node-v0.10.35-linux-x86/bin/npm" "install" "-g"
npm ERR! cwd /home/web8070/Oracle/node/node-oracledb
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

I have setup the env variable as usual:
```Shell
[web8070@m1-erp-apptest05 demo]$ echo $LD_LIBRARY_PATH 
/home/web8070/soft/instantclient_12_1:
[web8070@m1-erp-apptest05 demo]$ echo $OCI_INC_DIR 
/home/web8070/soft/instantclient_12_1/sdk/include
[web8070@m1-erp-apptest05 demo]$ echo $OCI_LIB_DIR 
/home/web8070/soft/instantclient_12_1
[web8070@m1-erp-apptest05 demo]$ echo $NODE_PATH 
/home/web8070/soft/node/node-v0.10.35-linux-x86/lib/node_modules
```  

And I am very sure for the instant client version:

```Shell
[web8070@m1-erp-apptest05 node-oracledb]$ cat /etc/oracle-release 
Oracle Linux Server release 6.3
[web8070@m1-erp-apptest05 node-oracledb]$ file /home/web8070/soft/instantclient_12_1/libclntsh.so
/home/web8070/soft/instantclient_12_1/libclntsh.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

I also can compile the demo OCI code:
```Shell
[web8070@m1-erp-apptest05 demo]$ make -f demo.mk buildoci EXE=cdemo81 OBJS=cdemo81.o 
rm -rf SunWS_cache
rm -rf ../../libclntsh.so
rm -rf ../../libocci.so
ln ../../libclntsh.so.12.1 ../../libclntsh.so
ln ../../libocci.so.12.1 ../../libocci.so
/usr/bin/g++ -o cdemo81 -g cdemo81.o -L../../ -locci -lclntsh -lpthread
rm -rf ../../libclntsh.so
rm -rf ../../libocci.so
[web8070@m1-erp-apptest05 demo]$ ls
cdemo81  cdemo81.c  cdemo81.o  demo.mk  occidemod.sql  occidemo.sql  occidml.cpp  occiobj.cpp  occiobj.typ  oraaccess.xml  setuporamysql.sh
```

So what's the problem?

**Comment by zorrofox** [comment]
Sorry, I use x86 node. And I will close this issue.
