### ISSUE TITLE
Error when install oracledb "njsOracle.o" failed

### ISSUE THREAD

**Issue by xarrdastop** [oracle/node-oracledb#543]
Log:

```
oracledb.target.mk:120: recipe for target 'Release/obj.target/oracledb/src/njs/src/njsOracle.o' failed
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
make: Leaving directory '/var/www/html/nodejs/node_modules/oracledb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/nodejs/node_modules/oracledb
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN nodejs@1.0.0 No description
npm WARN nodejs@1.0.0 No repository field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "oracledb"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.11.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/nodejs/npm-debug.log
```

1. What error(s) you are seeing?
    oracledb.target.mk:120: recipe for target 'Release/obj.target/oracledb/src/njs/src/njsOracle.o' failed
2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
     npm install oracledb
     login as root
3. What environment variables did you set?  How *exactly* did you set them?

4. What is your version of Node.js?
    node js 7.0.0
5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
    oracle client basic and devel 10.2.0.5
6. What is your OS and version?
    Debian 8 (jessie)
7. What compiler version did you use?

What is wrong in my actions, when I'm installing oracledb?
Thanks.

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#-prerequisites
You need 11.2+ Oracle client.
