### ISSUE TITLE
oracledb build fails on Windows 8.1 64 Bit Os, Oracle 12

### ISSUE THREAD

**Issue by telkomops** [oracle/node-oracledb#547]
Node-gyp build fails.
Windows 8.1 x64
Node.js version  v6.2.2 and npm version 3.9.5
Python 2.7 
VS 2015 Installed with VC++ Support. 
Oracle 12 Instant Client + SDK installed .
Path added include OC
Error when compiling with OCI_LIB_DIR,  OCI_INC_DIR
` npm install --msvs_version=2015 --save oracledb`

`C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_lo
ad_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type
 modifiers [D:\oracleconn\node_modules\oracledb\build\oracledb.vcxproj]`

` D:\Program Files\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): not
  e: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fai
ed with exit code: 1  gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules
npm\node_modules\node-gyp\lib\build.js:276:23) gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7) gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces.js:204:12)`

**Comment by telkomops** [comment]
Issue resloved with help of an similar thread.
If you see this error, check OCI_LIB_DIR, OCI_INC_DIR under system variables.
Double check the Path to include the Instant Client + Instant Client SDK
`npm -g install npm@latest`
`npm config set msvs_version 2015 --global`
delete all the node_modules under that specific node.js app
npm install oracledb

This worked for me.
Learning, by setting the msvs_version=2015 on the npm install --msvs_version=2015 might also work.
With VS2015, the VS2012 etc.. need not be installed.
