### ISSUE TITLE
Windows - npm install ok, execute fails - The specified module could not be found

### ISSUE THREAD

**Issue by kgajowy** [oracle/node-oracledb#69]
Dear all,

I have successfully been working with previous node-oracledb release (before windows fix - with version 0.2.4). Now, as the modules is available at npm, I wanted to update it.

Everything installs without any errors:
```

> oracledb@0.4.2 install C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb
> node-gyp rebuild


C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsMessages.cpp
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\njs\src\njsMessages.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
  dpiEnv.cpp
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\njs\src\njsConnection.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\njs\src\njsOracle.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\njs\src\njsPool.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\dpi\src\dpiEnv.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(554): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(559): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(615): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(827): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
..\src\njs\src\njsConnection.cpp(833): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\vector(254): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
          with
          [
              T=v8::Object
          ] (..\src\njs\src\njsConnection.cpp)
C:\Users\gak8wz\.node-gyp\0.10.29\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
          with
          [
              T=v8::Object
          ] (..\src\njs\src\njsOracle.cpp)
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\vector(254): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ] (..\src\njs\src\njsConnection.cpp)
C:\Users\gak8wz\.node-gyp\0.10.29\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ] (..\src\njs\src\njsOracle.cpp)
  dpiEnvImpl.cpp
C:\Users\gak8wz\.node-gyp\0.10.29\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
          with
          [
              T=v8::Object
          ] (..\src\njs\src\njsPool.cpp)
C:\Users\gak8wz\.node-gyp\0.10.29\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ] (..\src\njs\src\njsPool.cpp)
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\dpi\src\dpiEnvImpl.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\dpi\src\dpiExceptionImpl.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\dpi\src\dpiDateTimeArrayImpl.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\dpi\src\dpiConnImpl.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\dpi\src\dpiPoolImpl.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\dpi\src\dpiStmtImpl.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\dpi\src\dpiUtils.cpp) [C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\oracledb.vcxproj]
     Creating library C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\Release\oracledb.lib and object C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\Release\oracledb.exp
  Generating code
  Finished generating code
  oracledb.vcxproj -> C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\Release\\oracledb.node
oracledb@0.4.2 node_modules\oracledb
```
Although, executing simple query against database:
dbconfig.js:
````javascript
module.exports = {
  user          : "xxx",
  password      : "yyyy",
  connectString : "host:port/sid"
};
````
select:
````javascript
var oracledb = require('oracledb');
var dbConfig = require('./dbconfig.js');

oracledb.getConnection(
  {
    user          : dbConfig.user,
    password      : dbConfig.password,
    connectString : dbConfig.connectString
  },
  function(err, connection)
  {
    if (err) {
      console.error(err.message);
      return;
    }


    connection.execute(
      "SELECT sysdate from dual",
      [],
      function(err, result)
      {
        if (err) {
          console.error(err.message);
          return;
        }
        console.log(result.rows);
      });
  });
````

returns the following:
````
C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\lib\oracledb.js:28
    throw err;
          ^
Error: The specified module could not be found.
C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\build\Release\oracledb.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\t53_APPMON_SVN_SCRIPT\branches\gak8wz\healthsate\node_modules\oracledb\lib\oracledb.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
````

````
>node -e "console.log(process.arch, require('os').arch())"
ia32 ia32

>SET OCI
OCI_INCLUDE_DIR=C:\oracle\instantclient\sdk\include
OCI_LIB_DIR=C:\oracle\instantclient\sdk\lib\msvc
OCI_VERSION=12

>npm -v
1.4.14

>node -v
v0.10.29

>systeminfo
Microsoft Windows 7 Enterprise 
6.1.7601 Service Pack 1 Kompilacja 7601
 [01]: Intel64 Family 6 Model 58 Stepping 9 GenuineIntel ~2601 Mhz
LENOVO G4ET62WW (2.04 ), 2012-09-13
````

The only thing I noticed it still uses MSVS 11, instead of 12, even with ````--msvs_version```` or ````npm config set msvs_version 2012````

**Comment by scottchantry** [comment]
I have the same issue, would like a solution as soon as possible or at least a work around.

**Comment by Bigous** [comment]
@kgajowy Look at your path configuration. It could happen if your oci.dll is not on your path or if you have an OCI.DLL x64 on your path and you compiled your library x86 or vice-versa.

**Comment by scottchantry** [comment]
Everything I have is x64.  If I compile version 0.4.1 it runs fine.  So it has to be something with 0.4.2

**Comment by Bigous** [comment]
Just to be sure, is OCI.DLL on you path?

**Comment by scottchantry** [comment]
Yes, it's in my instant client folder and that folder has been added to the PATH.

**Comment by cjbj** [comment]
@scottchantry there weren't a lot changes in 0.4.2.  Have you bisected the changes to identify a cause?

I'd encourage you to use a version of Node more recent than 0.10.29 (try 0.10.38) in case that is a problem.

**Comment by scottchantry** [comment]
I was using 0.10.38 when I had the problem.  I tried compiling and running my app again today and now it works.  No idea what changed but thanks for looking into the issue for me.

**Comment by cjbj** [comment]
@scottchantry thanks for letting us know.

@kgajowy have you solved your problem?

**Comment by cjbj** [comment]
@kgajowy can this be closed?

**Comment by kgajowy** [comment]
@cjbj yes, it was connected with mentioned OCI.DLL

**Comment by ariefgrando** [comment]
Hi kgajowy

May I know how you solve that problem, I still struggling with mine

D:\xampp\htdocs\portalsdm\node_modules\oracledb\lib\oracledb.js:28
    throw err;
          ^
Error: The specified procedure could not be found.
D:\xampp\htdocs\portalsdm\node_modules\oracledb\build\Release\oracledb.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\xampp\htdocs\portalsdm\node_modules\oracledb\lib\o
racledb.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by kgajowy** [comment]
Ensure that **OCI_LIB_DIR** **OCI_INC_DIR** and **OCI_VERSION** system variables are defined. Furthermore, double ensure that you have a directory of an instantclient (escpecially oci.dll) included in your **PATH environment**. Moreover - ensure that those variables are **visible** during runtime execution of your application. For Windows system in my case:
```
>set OCI
OCI_INCLUDE_DIR=C:\oracle\instantclient\sdk\include
OCI_LIB_DIR=C:\oracle\instantclient\sdk\lib\msvc
OCI_VERSION=12
```
and
```
>set PATH
PATH=C:\oracle\instantclient;....
```

for example, if you are using [node-windows](https://github.com/coreybutler/node-windows), ensure to put all of them when installing the service:
```
var svc = new Service({
  name:'Hello World',
  description: 'The nodejs.org example web server.',
  script: 'C:\\path\\to\\helloworld.js',
  env: {
    name: "HOME",
    value: process.env["USERPROFILE"] // service is now able to access the user who created its' home directory
  }
});
```
this is also necessary when running as a Scheduler's Task (probably best to put ENVs variables within code, as the programs there start with abstract terminal variables (neither the system nor the user ones)

**Comment by ariefgrando** [comment]
Thank's a lot :-)  it works

**Comment by cjbj** [comment]
@kgajowy great, useful info.  Thanks.

**Comment by gintsgints** [comment]
Ty. This is path issue.
