### ISSUE TITLE
(Windows 10) Cannot include file winsock.h error during installation

### ISSUE THREAD

**Issue by ShiraazMoollatjie** [oracle/node-oracledb#701]
I'm trying to install oracledb using `npm install oracledb --save` and I get the following error:

```
D:\source\gitlab\wbms-graphql-node\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Program Files\node
js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
  njsMessages.cpp
  njsIntLob.cpp
  dpiEnv.cpp
  dpiEnvImpl.cpp
c:\users\shiraaz.moollatjie\.node-gyp\7.9.0\include\node\uv-win.h(32): fatal error C1083: Cannot open include file: 'wi
nsock2.h': No such file or directory (..\src\njs\src\njsOracle.cpp) [D:\source\gitlab\wbms-graphql-node\node_modules\or
acledb\build\oracledb.vcxproj]
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
c:\users\shiraaz.moollatjie\.node-gyp\7.9.0\include\node\uv-win.h(32): fatal error C1083: Cannot open include file: 'wi
nsock2.h': No such file or directory (..\src\njs\src\njsPool.cpp) [D:\source\gitlab\wbms-graphql-node\node_modules\orac
ledb\build\oracledb.vcxproj]
c:\users\shiraaz.moollatjie\.node-gyp\7.9.0\include\node\uv-win.h(32): fatal error C1083: Cannot open include file: 'wi
nsock2.h': No such file or directory (..\src\njs\src\njsConnection.cpp) [D:\source\gitlab\wbms-graphql-node\node_module
s\oracledb\build\oracledb.vcxproj]
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
c:\users\shiraaz.moollatjie\.node-gyp\7.9.0\include\node\uv-win.h(32): fatal error C1083: Cannot open include file: 'wi
nsock2.h': No such file or directory (..\src\njs\src\njsIntLob.cpp) [D:\source\gitlab\wbms-graphql-node\node_modules\or
acledb\build\oracledb.vcxproj]
c:\users\shiraaz.moollatjie\.node-gyp\7.9.0\include\node\uv-win.h(32): fatal error C1083: Cannot open include file: 'wi
nsock2.h': No such file or directory (..\src\njs\src\njsResultSet.cpp) [D:\source\gitlab\wbms-graphql-node\node_modules
\oracledb\build\oracledb.vcxproj]
  dpiUtils.cpp
  dpiLob.cpp
  dpiCommon.cpp
  win_delay_load_hook.cc
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
76:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\source\gitlab\wbms-graphql-node\node_modules\oracledb
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "oracledb" "--save"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

My current environment:
* npm 4.2.0
* node v7.9.0
* Windows 10 64 bit
* Oracle Instant Client
* Python 2.7
* .NET Framework 3.5
* Windows 10 SDK (Installed it thinking that it would include winsock2.h, but it did not)
* Visual Studio 2013 Express Edition

**Comment by ShiraazMoollatjie** [comment]
I used chocolatey to install all my dependencies, it seems that this isn't a good way to go about things.

So I uninstalled everything and installed the `windows-build-tools` npm package and then I could get oracledb to compile. This seems to be much easier than the existing method.
