### ISSUE TITLE
Oracledb it's not working with NodeJS 8+

### ISSUE THREAD

**Issue by CanKer** [oracle/node-oracledb#706]
*Delete irrelevant parts of this template.*

#### Answer the following questions:

1. What is your version of Node.js?  Run examples/version.js to find versions.
8.0
2. What version of node-oracledb are you using?
1.13.1
5. What is your OS and version?
Linux Ubuntu 17.04
8. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
I just updated NodeJS from 7.10 to 8.0 and its not working anymore
9. What error(s) you are seeing?
```Error: The module '/srv/http/BackEndVisorBBVA/node_modules/oracledb/build/Release/oracledb.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires

NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/http/BackEndVisorBBVA/node_modules/oracledb/lib/oracledb.js:35:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/http/BackEndVisorBBVA/node_modules/oracledb/index.js:1:80)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/http/BackEndVisorBBVA/server/controllers/bucket.js:4:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (/srv/http/BackEndVisorBBVA/server/routes/index.js:4:27)
    at Object.<anonymous> (/srv/http/BackEndVisorBBVA/index.js:85:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3 ```

**Comment by CanKer** [comment]
I just ```rm -rf node_modules``` -> ```npm cache clean --force``` -> ```npm i``` and It's working again.  :)

**Comment by CanKer** [comment]
but It's taking more than usual to establish a connection... :/

**Comment by firrae** [comment]
Necro, but I am having no luck getting this to work on Node 8.1.1 on Windows Server 2012. When I ran it on Node 7.X things were fine, but now I just get the output below:

<img width="845" alt="screen shot 2017-06-26 at 14 21 24" src="https://user-images.githubusercontent.com/6454839/27553924-c96a834e-5a7a-11e7-9999-174ecbea0459.png">

This is now the only breaking issue for our Windows build and sadly it needs to be shipped out tomorrow, so I guess we'll be reverting back to a previous version of Node until a solution is found.

**Comment by firrae** [comment]
For extra info, this is the entire way I used to reproduce this error:

```javascript
var oracledb = require('oracledb');

console.log(oracledb);
```

Then install oracledb like follows: `npm i -S oracledb`.

I am running Node 8.1.1 and NPM 5.0.3.

**Comment by cjbj** [comment]
@firrae:
1) this is a closed issue. You should have opened a new one.
2) do some debugging.  Check what path being using in lib/oracledb.js, and see whether that leads to the oracledb.node file location.

At a pure guess, see if the npm from the node install is being used.
