### ISSUE TITLE
KeyError: '2017' installing node oracledb

### ISSUE THREAD

**Issue by johannschneider** [oracle/node-oracledb#776]
Hi,
I try to install oracledb for node.js but get always the KeyError: '2017' and an exception

**I have installed:**
- Windows 10
- Node.js: 6.11.5
- npm:     5.5.1
- oracle client: 12.2.0
- MS Visual C++ 2005, 2008, 2010, 2012, 2013, 2017 Redistributable
- MS Visual Studio 2008, 2013, 2015, 2017
- OCI_LIB_DIR and OCI_INC_DIR are defined
 
**Error on Console:**
File "C:\Users\joi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\joi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\joi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\p\mTMS\node_modules\oracledb
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN mtmspro@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Error from the log:**
319 silly lifecycle oracledb@1.13.1~install: Returned: code: 1  signal: null
320 info lifecycle oracledb@1.13.1~install: Failed to exec install script
321 verbose unlock done using C:\Users\joi\AppData\Roaming\npm-cache\_locks\staging-9f283cbcda2d635d.lock for C:\git\k\mTMS\node_modules\.staging
322 warn mtmspro@1.0.0 No repository field.
323 verbose stack Error: oracledb@1.13.1 install: `node-gyp rebuild`
323 verbose stack Exit status 1
323 verbose stack     at EventEmitter.<anonymous> (C:\Users\joi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
323 verbose stack     at emitTwo (events.js:106:13)
323 verbose stack     at EventEmitter.emit (events.js:191:7)
323 verbose stack     at ChildProcess.<anonymous> (C:\Users\joi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
323 verbose stack     at emitTwo (events.js:106:13)
323 verbose stack     at ChildProcess.emit (events.js:191:7)
323 verbose stack     at maybeClose (internal/child_process.js:920:16)
323 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
324 verbose pkgid oracledb@1.13.1

Does someone has the same problem or knows how to solve this?
Thanks
Joi

**Comment by johannschneider** [comment]
I think it's not a problem of oracledb but of node-gyp and MS VS...
