### ISSUE TITLE
error C2491

### ISSUE THREAD

**Issue by ugate** [oracle/node-oracledb#782]
```console
$ npm rebuild

> oracledb@1.13.1 install C:\test\node_modules\oracledb
> node-gyp rebuild


C:\test\node_modules\oracledb
$ if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  njsOracle.cpp
  njsPool.cpp
  njsConnection.cpp
  njsResultSet.cpp
  njsMessages.cpp
  njsIntLob.cpp
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(2456): error C2491: 'public: static int const v8::String::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsOracle.cpp) [C:\nss\lawson- lbi-plus\node_modules\oracledb\build\oracledb.vcxproj]
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(2456): error C2491: 'public: static int const v8::String::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsResultSet.cpp) [C:\nss\laws on-lbi-plus\node_modules\oracledb\build\oracledb.vcxproj]
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(2456): error C2491: 'public: static int const v8::String::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsPool.cpp) [C:\nss\lawson-lb i-plus\node_modules\oracledb\build\oracledb.vcxproj]
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(2456): error C2491: 'public: static int const v8::String::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsConnection.cpp) [C:\nss\law son-lbi-plus\node_modules\oracledb\build\oracledb.vcxproj]
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(4517): error C2491: 'public: static unsigned __int64 const v8::TypedArray::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsOracle.cpp ) [C:\test\node_modules\oracledb\build\oracledb.vcxproj]
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(4517): error C2491: 'public: static unsigned __int64 const v8::TypedArray::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsResultSet. cpp) [C:\test\node_modules\oracledb\build\oracledb.vcxproj]
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(4517): error C2491: 'public: static unsigned __int64 const v8::TypedArray::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsPool.cpp)
[C:\test\node_modules\oracledb\build\oracledb.vcxproj]
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(4517): error C2491: 'public: static unsigned __int64 const v8::TypedArray::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsConnection .cpp) [C:\test\node_modules\oracledb\build\oracledb.vcxproj]
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(2456): error C2491: 'public: static int const v8::String::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsIntLob.cpp) [C:\nss\lawson- lbi-plus\node_modules\oracledb\build\oracledb.vcxproj]
c:\users\someone\.node-gyp\9.0.0\include\node\v8.h(4517): error C2491: 'public: static unsigned __int64 const v8::TypedArray::kMaxLength': definition of dllimport data not allowed (compiling source file ..\src\njs\src\njsIntLob.cpp ) [C:\test\node_modules\oracledb\build\oracledb.vcxproj]
  dpiEnv.cpp
  dpiEnvImpl.cpp
  dpiException.cpp
  dpiExceptionImpl.cpp
  dpiConnImpl.cpp
  dpiDateTimeArrayImpl.cpp
  dpiPoolImpl.cpp
  dpiStmtImpl.cpp
  dpiUtils.cpp
  dpiLob.cpp
  dpiCommon.cpp
  win_delay_load_hook.cc
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\test\node_modules\oracledb
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\someone\AppData\Roaming\npm-cache\_logs\2017-11-03T15_52_16_186Z-debug.log
```

[MS Compiler Error](https://msdn.microsoft.com/en-us/library/62688esh.aspx)

#### Answer the following questions:

1. What is your version of Node.js?  Run examples/version.js to find versions.
9.0.0

2. What version of node-oracledb are you using?
1.13.1

3. What is the version of your Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
c12
C:\oracle\instantclient

4. What is the version of Oracle Database?
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
"CORE	11.2.0.4.0	Production"
TNS for IBM/AIX RISC System/6000: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

5. What is your OS and version?
OS Name	Microsoft Windows 7 Professional
Version	6.1.7601 Service Pack 1 Build 7601

6. What compiler version did you use?  For example, with GCC, run `gcc --version`
MSBuild 14.0

**Comment by ugate** [comment]
It looks like this issue was only happening on Windows 7 with Visual Studio 15 CE. Once I uninstalled VS, ran `npm install --global --production windows-build-tools` and reran `npm rebuild` the error went away.
