### ISSUE TITLE
The specified module could not be found.

### ISSUE THREAD

**Issue by ghost** [oracle/node-oracledb#795]
I am able to run node-oracledb on my winodws7, when i copy the same to windows server 8 r2 am getting the below error. I installed node(same version) and set install client path, but still getting the below error

C:\SampleTest-master>node BPISQLConnect.js
C:\SampleTest-master\node_modules\oracledb\lib\oracledb.js:38
    throw err;
    ^

Error: The specified module could not be found.
\\?\C:\SampleTest-master\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\SampleTest-master\node_modules\oracledb\lib\oracle
db.js:35:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by cjbj** [comment]
Check  https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Also the future [v2 trouble shooting guid](https://github.com/oracle/node-oracledb/blob/dev-2.0/INSTALL.md#troubleshooting) steps might have something useful.

Also filing in the [issue template](https://github.com/oracle/node-oracledb/blob/master/.github/issue_template.md) so we know what you have configured is helpful.

Keep an eye on #18.

**Comment by cjbj** [comment]
Closing; I see the report no longer has a github account.
