### ISSUE TITLE
Error: The specified procedure could not be found

### ISSUE THREAD

**Issue by pwxwabcd** [oracle/node-oracledb#81]
node select1.js

E:\node-test\node_modules\oracledb\lib\oracledb.js:28
    throw err;
          ^
Error: The specified procedure could not be found.
E:\node-test\node_modules\oracledb\build\Release\oracledb.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (E:\\node-test\node_modules\oracledb\l
ib\oracledb.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by cjbj** [comment]
Probably PATH doesn't contain a directory with Oracle client libraries.
