### ISSUE TITLE
NJS-045 error on Windows

### ISSUE THREAD

**Issue by mhcgolds** [oracle/node-oracledb#828]
Hello everybody. 

I'm having hard times to estabilish a connection to a database in my app. It is made over [nwjs](https://github.com/nwjs) version 0.26.6 on Win10 x64, node version is 8.6.0 and npm is 5.3.0. I already have oracle client 11.2.0 installed in my machine due to the target database being used for our main product made in .Net, which works fine with it. So database is ok.

As pointed in the NJS-045 error, I have downloaded and set path for [Instant Client ZIP files](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin)(version dowloaded was windows.x64-12.2.0.1.0, tried *basic* and *basiclite*  versions): [PATH screenshot](https://i.imgur.com/qkw0QA7.png)(last entry).

Below its a short piece of the connection code I'm using:

```
// DB Factory class
class OracleFactory
{
    constructor(config)
    {
        this.oracledb = require('oracledb');
        this.config = config;
        this.connection = null;
    }

    Connect(callback)
    {
        this.oracledb.getConnection(this.config, (err, connection) =>
        {
            if (!err) 
            {
                this.connection = connection;
            }

            callback(err);
        });
    }
}

// The call
let config = {
        "user": "myuser",
        "password": "secret",
        "connectString": "ORAPROD"
    },
    factory = new OracleFactory(config);
factory.Connect((err) => { ... });
```

Like I said, I already have Oracle set in my machine for other projects and apps, so I'm tring to connect using a TNS configuration called `ORAPROD`. My TNS definition(under *C:\oracle\product\11.2.0\client_1\network\admin*) is the following:

```
ORAPROD =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = SVRDB)(PORT = 1522))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = ORAPRD1)
    )
  )
```

But I'm not lucky and not sure what I have to do exactly as it is the first time I'm using this package. If you need more details, please let me know.

**Comment by cjbj** [comment]
Post the full error.  

You probably don't need Instant Client since you seem to have the full client - and the full client appears first in PATH, if I read it correctly.  Just make sure the full client is the same 32 or 64-bit architecture as your Node version (and same as the version of node-oracledb).

If you have multiple products with conflicting Oracle Client library requirements (versions and/or architectures), then you will need to find a way to change PATH to have the appropriate Oracle client libraries first in PATH before running each application.

**Comment by mhcgolds** [comment]
Sure, I'm sorry. I though the error code would be enough. The full error message is:

> Error: NJS-045: cannot load the oracledb add-on binary for Node.js 9.1.0 (win32, x64) Cannot load C:\\...\node_modules\oracledb\build\Release\oracledb.node Uma rotina de inicialização da biblioteca de vínculo dinâmico (DLL) falhou.
 \\?\C:\\...\node_modules\oracledb\build\Release\oracledb.node Node-oracledb installation instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md You must have 64-bit Oracle client libraries in your PATH environment variable. If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from http://www.oracle.com/technetwork/topics/winx64soft-089540.html A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

System paths supressed for brevity. The portuguese part of the message stands for: *"Dynamic link library (DLL) intialization routine failed."*.

I have checked and the client is positivelly a x86 version yet my nodejs is x64. I'm not sure how I will test it over node 32-bit version since I think I can't have both installed side-by-side unfortunatelly. Working on that.

Another point is that my node is 8.6.0 and in the error message it seems that somehow it believes that the node version is 9.1.0. Can this be a problem? I will upgrade my node version.

**Comment by mhcgolds** [comment]
I'm trying to test the lib in order to find out the problem with my app, but I got no success. I tried to run an example of this reposotiry, the *select1.js* script. So I downloaded the source, copied only the script in a separate folder, and with an old x64 installation of node, I installed oracledb(`npm install oracledb`) in that folder. I didn't want to lose that installation, so I downloaded a 32bit version of node and installed it. After that I realized that it removed the old installation, so then I had only the 32bit version. Yeah, what a mess. So I run the script in a new 32bit version of node(note that the lib was installed with npm of a x64 node):

> C:\\...\TesteNodeOracle>node select1.js
> C:\\...\TesteNodeOracle\node_modules\oracledb\lib\oracledb.js:68
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^
> 
> Error: NJS-045: cannot load the oracledb add-on binary for Node.js 9.4.0 (win32, ia32)
Cannot load C:\\...\TesteNodeOracle\node_modules\oracledb\build\Release\oracledb.node
\\?\C:\\...\TesteNodeOracle\node_modules\oracledb\build\Release\oracledb.node não é um aplicativo Win32 válido.
\\?\C:\\...\TesteNodeOracle\node_modules\oracledb\build\Release\oracledb.node
Node-oracledb installation instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
You must have 32-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winsoft-085727.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.
>
>  at Object.<anonymous> (C:\\...\TesteNodeOracle\node_modules\oracledb\lib\oracledb.js:68:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\\...\TesteNodeOracle\node_modules\oracledb\index.js:1:80)
    at Module._compile (module.js:660:30)

The portugues part of the message stands for: *"oracledb.node is not a valid Win32 application."*

I realized that it could have added a x64 version of the library, so I removed it, and tried to add it again with the new 32bit npm installer. To get the big picture here, now it is a 32bit v9.4.0 node, under a x64 win 10 installation and 32bit 11.2.0 oracle client. I got this:

> C:\\...\TesteNodeOracle>npm install oracledb
> 
> oracledb@2.0.15 install C:\\...\TesteNodeOracle\node_modules\oracledb
> node package/oracledbinstall.js
>
> oracledb Beginning installation
oracledb Verifying installation
oracledb Binary not found
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed from oracledb-v2.0.15-node-v59-win32-ia32.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.0.15/oracledb-v2.0.15-node-v59-win32-ia32.gz failed with code 404
oracledb ERR! If the error is not network or filesystem related, then review
oracledb ERR! the Python 2.7 and compiler prerequisites in the installation instructions and
oracledb ERR! then install from source code with: npm install oracle/node-oracledb.git#v2.0.15
oracledb ERR! See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
> 
> npm WARN testenodeoracle@1.0.0 No description
npm WARN testenodeoracle@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.0.15 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
npm ERR!     C:\\...\AppData\Roaming\npm-cache\_logs\2018-01-15T16_33_48_214Z-debug.log

I can't find anything related to error `NJS-054` on the web but looking into the error message, it seems that it can't find the url `https://github.com/oracle/node-oracledb/releases/download/v2.0.15/oracledb-v2.0.15-node-v59-win32-ia32.gz`.

I don't know if I'm in the right path though.

**Comment by anthony-tuininga** [comment]
Binaries are only available for LTS versions of Node.js. Since you are running 9.4.0, this is not LTS so no binary is available. You will need to perform an installation from source (or use Node.js 8.x instead). The error message indicates HTTP 404 (not found) and then provides instructions on how to build from source.

**Comment by cjbj** [comment]
@mhcgolds node-oracledb pre-built binaries for Node 9 are definitely available, but only for 64-bit.  (You can build 32 bit binaries if you want to.)

I still suspect an Oracle client clash, since you had a few installed, and your PATH had conflicts.

**Comment by mhcgolds** [comment]
Thank you for your replies guys. About PATH conflicts, I resolved that leaving just one client path added there. Then tried again connecting with both x64 and x86 version of my app, the error remains that same I posted above time. It just changes this part *You must have 64-bit Oracle client* to this *You must have 32-bit Oracle client* depending on the node arch I run. This happens while all my other apps(.net and vb6) still works with that client.

I'm focusing on run the 32bit version relying on what you have said about matching the same architecture of the installed client. But I'm unable to build it using `npm install oracle/node-oracledb.git#v2.0.15`(also using `--msvs_version=2015` param). I already installed Python 2.7, Windows SDK 8.1 and Visual Studio C++ SDK tools(hours of downloads and installations) and everytime a new error appears. Fortunatelly I will have to change my hardware this week so I will get brand new windows setup and I will try to install x64 client to get back aaaall my node environment back to that arch and try this package over again, because I don't know what I'm missing here.

I hope I can reach a solution about this issue and it can add troubleshooting information for the newcomers like that matching architecture rule about the client and node(if it is really the problem). I wish this could be more smoother and straighfoward installation.

I'm all ears for any information you can give and I'll let you know about any progress.

**Comment by cjbj** [comment]
Do you have the appropriate VS Redistributable installed?

**Comment by mhcgolds** [comment]
Yes, I have VC redist 2013 version.

**Comment by cjbj** [comment]
From googling, that points to a Windows misconfiguration or clash.  I'm not a Windows user and haven't come across that error before.

**Comment by cjbj** [comment]
Closing due to inactivity.
