### ISSUE TITLE
npm install failure / Windows  10 / npm registry artifactory 

### ISSUE THREAD

**Issue by brickpattern** [oracle/node-oracledb#889]
[2018-04-02T21_37_05_226Z-debug.log](https://github.com/oracle/node-oracledb/files/1874345/2018-04-02T21_37_05_226Z-debug.log)
I'm facing issue with npm install.  I ended up using the prebuilt binary. Others reported earlier on npm install failure did not provide the npm log, so created a new issue with log file showing verbose output. 

```
> 
> 68 verbose stack Exit status 87
> 68 verbose stack     at EventEmitter.<anonymous> (C:\node-v8.11.1\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
> 68 verbose stack     at emitTwo (events.js:126:13)
> 68 verbose stack     at EventEmitter.emit (events.js:214:7)
> 68 verbose stack     at ChildProcess.<anonymous> (C:\node-v8.11.1\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 68 verbose stack     at emitTwo (events.js:126:13)
> 68 verbose stack     at ChildProcess.emit (events.js:214:7)
> 68 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 68 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 
> 
```

### For installation issues:

- Review the install instructions https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

- Review the troubleshooting tips https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#troubleshooting

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from 
8.11.1

2. What is your node-oracledb version?
2.1.2

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?

4. What is your Oracle Database version?
11g

5. What is your OS and version?
Windows10

6. What is your compiler version?  For example, with GCC, run `gcc --version`

7. What Oracle environment variables did you set?  How *exactly* did you set them?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

10. What error(s) you are seeing?
see attached log

**Comment by cjbj** [comment]
For completeness, what output did you get on the screen?

What other things have you tried - outside firewalls, in different directories, with different versions of node, without having other dependencies in package.json etc?

Can you manually download the [bundle](https://github.com/oracle/node-oracledb/releases/download/v2.2.0/oracledb-2.2.0.tgz), extract it, and run 'node package/oracledbinstall.js' to see what is happening?

**Comment by brickpattern** [comment]
@cjbj  the screen error was the Exit status 87. The same in the npm log file.

I had  a fresh machine. installed NODE just for this exercise. So no other node or npm version previously existed. 

the package.json was empty to begin with... npm install oracledb was the very statement I hit it.

**Comment by cjbj** [comment]
As of yesterday `npm install oracledb` should install 2.2 but your log shows 2.1.2.

The error code 87 comes from [here](https://github.com/oracle/node-oracledb/blob/master/package/oracledbinstall.js#L352).  You can see the lines above it should print something.

**Comment by cjbj** [comment]
Closing - no activity
