### ISSUE TITLE
always tips me " Cannot find module 'oracledb' "

### ISSUE THREAD

**Issue by xulayen** [oracle/node-oracledb#900]
## WIN7 64

E:\工作\workpace\web\node-oracledb\examples>npm install oracledb -g

> oracledb@2.2.0 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb Oracledb downloaded
oracledb Verifying installation
oracledb Binary SHA matches SHA in SHASUMS256.txt
oracledb
oracledb ********************************************************************************
oracledb ** Node-oracledb 2.2.0 installation complete for Node.js 8.9.4 (win32, x64)
oracledb **
oracledb ** To use the installed node-oracledb:
oracledb ** - You must have 64-bit Oracle client libraries in your PATH environment variable
oracledb ** - If you do not already have libraries, install the Instant Client Basic or Basic Light package from
oracledb **   http://www.oracle.com/technetwork/topics/winx64soft-089540.html
oracledb ** - A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available
oracledb **   Check https://oracle.github.io/node-oracledb/INSTALL.html for details
oracledb **
oracledb ** Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
oracledb ********************************************************************************

+ oracledb@2.2.0
added 1 package in 5.143s

E:\工作\workpace\web\node-oracledb\examples>node select1.js
module.js:540
    throw err;
    ^

Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\工作\workpace\web\node-oracledb\examples\select1.js:35:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by cjbj** [comment]
Since you installed with -g, do you need to set NODE_PATH?

**Comment by cjbj** [comment]
Closing - no activity.
