### ISSUE TITLE
Issues installing node-oracleDB. Behind the proxy and getting ETIMEDOUT error

### ISSUE THREAD

**Issue by skullz03** [oracle/node-oracledb#909]
Hi, 
I am facing issue installing node-oracleDB. Below is the stack trace. Here is my config:-
1) OS: win 7 - 64 bit
2) Visual Studio 2017 community edition installed
3) Node - npm -5.6.0 and 8.10.0 
4) Installed the Oracle instant client - basic and SDK and added the path variable for OCI_LIB_DIR and OCI_INC_DIR. Also set the "instant client" folder on the path 
5) installed python and added the path variables

I am behind a proxy so I am using a proxy as well but this keep failing. Could someone tell me, looking at the stack trace where I may be going wrong?

```
> oracledb@2.2.0 install C:\Users\monnie\AppData\Roaming\npm\node_modules\oracledb
> node package/oracledbinstall.js

oracledb TRACE In initDynamicProps
oracledb TRACE dynamicProps = { PACKAGE_JSON_VERSION: '2.2.0',
  GITHUB_TAG: 'v2.2.0',
  BINARY_BUILD_NAME: 'oracledb-v2.2.0-node-v57-win32-x64-oracledb.node',
  PACKAGE_FILE_NAME: 'oracledb-v2.2.0-node-v57-win32-x64.gz' }
oracledb TRACE In install
oracledb Beginning installation
oracledb TRACE In verifyBinary
oracledb TRACE Checking for binary at C:\Users\monnie\AppData\Roaming\npm\node_modules\oracledb\build\Release\oracledb.node
oracledb Verifying installation
oracledb Continuing installation
oracledb TRACE In installBinary
oracledb TRACE In getRemoteFileReadStream github.com /oracle/node-oracledb/releases/download/v2.2.0/oracledb-v2.2.0-node-v57-win32-x64.gz
oracledb TRACE In getProxyConfig github.com
oracledb TRACE In getFileReadStreamBase github.com /oracle/node-oracledb/releases/download/v2.2.0/oracledb-v2.2.0-node-v57-win32-x64.gz
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v57-win32-x64.gz
oracledb ERR! connect ETIMEDOUT 192.30.253.112:443
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm verb lifecycle oracledb@2.2.0~install: unsafe-perm in lifecycle true
npm verb lifecycle oracledb@2.2.0~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\monnie\AppData\Roaming\npm\node_modules\oracledb\node_modules\.bin;C:\Users\monnie\AppData\Roaming\npm\node_modules\.bin;C:\Oracle\instant Client;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_65\bin;C:\Program Files (x
86)\Nice Systems\NICE Player Codec Pack\;C:\Program Files (x86)\Business Objects\BusinessObjects Enterprise 12.0\win32_x86\;C:\sybase\DataAccess\ODBC\dll;C:\sybase\RPL-15_0\bin;C:\sybase\Shared\Sybase Central 4.3;C:\sybase\UAF-2_0\bin;C:\sybase\OCS-15_0\lib3p;C:\sybase\OCS-15_0\dll;C:\sybase\OCS-15_0\bin;C:\sybase\ASE-15_0\dll;C:\sybase\ASE-15_0\bin;C:\WINDOWS\system32;C:\WINDO
WS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program Files (x86)\Microsoft Office 2010\Office14;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NIC
E Systems\NICE Player Release 3\;C:\WINDOWS\system32\;C:\WINDOWS\;C:\WINDOWS\system32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Enterprise Vault\EVClient;C:\Program Files (x86)\IBM\FNSW\client\bin;C:\Program Files (x86)\IBM\FNSW\client\shobj;C:\Program Files (x86)\IBM\IDM;C:\Program Files (x86)\IBM\Shared;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Python27;C:\Prog
ram Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\monnie\AppData\Roaming\npm
npm verb lifecycle oracledb@2.2.0~install: CWD: C:\Users\monnie\AppData\Roaming\npm\node_modules\oracledb
npm info lifecycle oracledb@2.2.0~install: Failed to exec install script
npm verb unlock done using C:\Users\monnie\AppData\Roaming\npm-cache\_locks\staging-2fbcff2e0624e898.lock for C:\Users\monnie\AppData\Roaming\npm\node_modules\.staging
npm verb stack Error: oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm verb stack Exit status 87
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:925:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid oracledb@2.2.0
npm verb cwd C:\Users\monnie\Desktop\Node app
npm verb Windows_NT 6.1.7601
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "oracledb" "-g" "--proxy=http://http.myproxy.com:8000"
npm verb node v8.10.0
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 87, true ]
```

**Comment by skullz03** [comment]
I had followed this article: https://community.oracle.com/docs/DOC-931127

**Comment by cjbj** [comment]
The first text in that article is **'Note: This article is for node-oracledb v1 and is outdated.  Node-oracledb v2 has pre-built binaries and installation is much simpler.  See https://oracle.github.io/node-oracledb/INSTALL.html'**. This basically means "don't follow this article".  You don't need python anymore.  You don't need to set the OCI_*_DIR environment variables anymore.

Check out https://oracle.github.io/node-oracledb/INSTALL.html  You may need to set https_proxy.  There are various alternative ways to install if your network setup (or bugs like https://github.com/npm/npm/issues/18567) impact you.  If your proxy needs a password you will need to use one of these alternative methods until something like https://github.com/oracle/node-oracledb/pull/810 is merged.

**Comment by cjbj** [comment]
The installation instructions have details - you don't need the SDK; you do need a VC redistributable.
You need to set https_proxy or other terminal environment proxy because the code downloading the binary package is a [Node.js app](https://github.com/oracle/node-oracledb/blob/master/package/oracledbinstall.js), not npm.  Please check the [instructions from top to bottom](https://oracle.github.io/node-oracledb/INSTALL.html#instwin)!

**Comment by skullz03** [comment]
I was able to run a sample query. Thanks for your inputs. Appreciate it!

**Comment by skullz03** [comment]
I deleted the SDK, I have the 2013 VC redistributable, set the proxy, deleted the OCI variables. I didn't  do anything different from last time. Just redid all my installations again and it worked magically.

**Comment by cjbj** [comment]
That's good news!
