### ISSUE TITLE
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.11.1 (win32, x64) Cannot load C:\oracle\node-oracledb-master\node_modules\oracledb\build\Release\oracledb.node Error while trying to retrieve text for error ORA-01804

### ISSUE THREAD

**Issue by rajmuni** [oracle/node-oracledb#916]
*Delete unnecessary parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

Use a gist for screen output and logs: see https://gist.github.com/ **Do not paste long output into this issue**.

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

- Review the install instructions https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

- Review the troubleshooting tips https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#troubleshooting

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js

2. What is your node-oracledb version?

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?

4. What is your Oracle Database version?

5. What is your OS and version?

6. What is your compiler version?  For example, with GCC, run `gcc --version`

7. What Oracle environment variables did you set?  How *exactly* did you set them?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

10. What error(s) you are seeing?

**Comment by cjbj** [comment]
Please answer the template questions.  Thanks.,

**Comment by rajmuni** [comment]
Can you please help resolving the issue:
---------------------------------------------------------------------------------
I've installed Node.js v8.11.1 , driver : oracledb@2.2.0 , oracleclient : instantclient_12_2 (Basic) in win x64 , Microsoft visual c++ 2015 redistributable (vc_redist.x86.exe & vc_redist.x64.exe).
--Connecting to remote database - v12.1.0.2.0
Path set for nodejs, instantclient_12_2, vc_redist.x86.exe & vc_redist.x64.exe.
Made changes to dbconfig.js.

---------------------------------------------------------------------------------
When i execute cmd : >node connect.js (or) >node select1.js , i am getting this error:
---------------------------------------------------------------------------------
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.11.1 (win32, x64)
Cannot load C:\oracle\node-oracledb-master\node_modules\oracledb\build\Release\oracledb.node
Error while trying to retrieve text for error ORA-01804

Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

    at Object.<anonymous> (C:\oracle\node-oracledb-master\node_modules\oracledb\lib\oracledb.js:68:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\oracle\node-oracledb-master\node_modules\oracledb\index.js:1:80)
    at Module._compile (module.js:652:30)

@cjbj : Can u kindly assist, what am i missing

**Comment by rajmuni** [comment]
Chris, Can u kindly help me in sorting out the issue.
-Thx

**Comment by cjbj** [comment]
What have you found by googling?

Are you really using Instant Client? - check your PATH

What has your DBA done with timezone files?

**Comment by cjbj** [comment]
Closing - no activity.

**Comment by Karen17** [comment]
When I am trying to connect to Oracle DB to read a table I am getting error . Following are the details. Could anyone please help me in resolving the issue?

   1) What is your Node.js version? Is it 64-bit or 32-bit? Run version.js from https://github.com/oracle/node-oracledb/blob/master/examples/version.js

**I am using NodeJS : 6.10.2 (64 bit)**


2) What is your node-oracledb version?

**Oracle-db 2.3.0**
3) What is your Oracle client (e.g. Instant Client) version? Is it 64-bit or 32-bit? How was it installed? Where is it installed?
**Version 12.2.0.1.0 (64-bit)**     

_( Instant Client Package - Basic: All files required to run OCI, OCCI, and JDBC-OCI applications                                                                                                                                                                              instantclient-basic-macos.x64-12.2.0.1.0-2.zip )
It is installed in /opt/oracle_

4) What is your Oracle Database version?

5)What is your OS and version?
**Mac OS High Sierra
Version 10.13.4**

6) What is your compiler version? For example, with GCC, run gcc --version

_Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin_


 7)What Oracle environment variables did you set? How exactly did you set them?
**Followed these steps

Installing Instant Client 12.2 on macOS

Instant Client 12.2 supports macOS High Sierra, Sierra and El Capitan.

1. Download the desired Instant Client ZIP files. All installations require the Basic or Basic Light package.

2. Unzip the packages into a single directory such as ~/instantclient_12_2 that is accessible to your application. For example:

  cd ~
  unzip instantclient-basic-macos.x64-12.2.0.1.0.zip


3. Add links to $HOME/lib or /usr/local/lib to enable applications to find the libraries. For example, OCI based applications could do:

  mkdir ~/lib
  ln -s ~/instantclient_12_2/libclntsh.dylib ~/lib/
  ln -s ~/instantclient_12_2/libclntsh.dylib.12.1 ~/lib/


Alternatively, copy the required libraries. For example, to use OCI applications:

  mkdir ~/lib
  cp /opt/oracle/instantclient_12_2/libclntsh.dylib.12.1 ~/lib/
  cp /opt/oracle/instantclient_12_2/libclntshcore.dylib.12.1 ~/lib/
  cp /opt/oracle/instantclient_12_2/libons.dylib ~/lib/
  cp /opt/oracle/instantclient_12_2/libnnz12.dylib ~/lib/
  cp /opt/oracle/instantclient_12_2/libociei.dylib ~/lib/
  ln -s ~/lib/libclntsh.dylib.12.1 ~/lib/libclntsh.dylib


Note: Custom OCI applications, such as those that bundle Instant Client, may want to link with -rpath set to the directory containing Instant Client 12.2 instead of relying on libraries being in ~/lib.**


8) What is the PATH environment variable (on Windows) or LD_LIBRARY_PATH (on Linux) set to? On **macOS, what is in ~/lib?
libclntsh.dylib
libclntsh.dylib.12.1
libclntshcore.dylib.12.1
libnnz12.dylib
libociei.dylib
libons.dylib**

9)What exact command caused the problem (e.g. what command did you try to install with)? Who were you logged in as?
**I am trying to connect and read a table through node js code**
10)What error(s) you are seeing?


_Error: NJS-045: cannot load the oracledb add-on binary for Node.js 6.10.2 (darwin, x64)
Node.js require() error was: 
  DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node.js require() mapped to /Users/Karen/git/StoretoDoor_KalyanJewellers_Platform_1stJune_Scheduler_DEV/node_modules/oracledb/build/Release/oracledb.node
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the 64-bit Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
They can be downloaded from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
    at Object.<anonymous> (/Users/Karen/git/StoretoDoor_KalyanJewellers_Platform_1stJune_Scheduler_DEV/node_modules/oracledb/lib/oracledb.js:65:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Karen/git/StoretoDoor_KalyanJewellers_Platform_1stJune_Scheduler_DEV/node_modules/oracledb/index.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Karen/git/StoretoDoor_KalyanJewellers_Platform_1stJune_Scheduler_DEV/server/boot/oracleConn.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)_

**Comment by cjbj** [comment]
Thanks for the details.  Because this issue is old, is closed, and was originally opened for Windows but you are using Mac, can you open a new issue?   Try running a demo program.  Check directory permissions.
