### ISSUE TITLE
oracledb electron crashes on execution

### ISSUE THREAD

**Issue by Chinmoy-globalIds** [oracle/node-oracledb#917]
I am trying to run some Oracle query on an Electron project. When I just run the script alone everything works, but when I run it into my Electron project I keep having this error :

```
App threw an error during load
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.9.3 (win32, x64)
Cannot load C:\Users\Chinmoy Samanta\Desktop\try-it-now\node_modules\oracledb\build\Release\oracledb.node
The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Users\Chinmoy Samanta\Desktop\try-it-now\node_modules\oracledb\build\Release\oracledb.node
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

    at Object.<anonymous> (C:\Users\Chinmoy Samanta\Desktop\try-it-now\node_modules\oracledb\lib\oracledb.js:69:13)
    at Object.<anonymous> (C:\Users\Chinmoy Samanta\Desktop\try-it-now\node_modules\oracledb\lib\oracledb.js:602:3)
    at Module._compile (module.js:642:30)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Chinmoy Samanta\Desktop\try-it-now\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Chinmoy Samanta\Desktop\try-it-now\node_modules\oracledb\index.js:1:173)
```

**Comment by dmcghan** [comment]
@Chinmoy-globalIds See these notes regarding Electron: https://github.com/oracle/node-oracledb/issues/881#issuecomment-375088080

Electron uses custom versions of Node.js (modified V8) so you need to compile the driver for that version. The notes there explain one way to do this and have a link to the details.

**Comment by cjbj** [comment]
@n-riesco The NAN issues we saw & fixed on the master branch with NAN 2.10 were only warnings.  The errors in https://gist.github.com/lealhugui/3020caa8b961618c9bf48aa34f1c437c  are something different; I noted that iojs-1.7.6 seemed to be used!?

**Comment by n-riesco** [comment]
@cjbj See #918

**Comment by cjbj** [comment]
@n-riesco thank you.  Since the original poster here hasn't been active, I'll close this.
