### ISSUE TITLE
Getting Error: NJS-045 on installation

### ISSUE THREAD

**Issue by GiantSlayer1913** [oracle/node-oracledb#937]
### For general questions:

I am confused by this error and really new at setting up this kind of database, so all help is appreciated. 
I have been following the installation setup steps from  ```3.5 Node-oracledb Installation on macOS``` https://oracle.github.io/node-oracledb/INSTALL.html#instosx .

----------------------------
### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

- Review the install instructions https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

- Review the troubleshooting tips https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#troubleshooting

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js
```64-bit```
2. Whatis your node-oracledb version?
package.json/
```json
"version": "3.0.0-dev",
```
3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?

```64-bit, installed by unzipping package file within project directory: test-oracle/```

4. What is your Oracle Database version?
package-lock.json
```json
{
  "name": "test-oracle",
  "version": "3.0.0-dev",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "oracledb": {
      "version": "github:oracle/node-oracledb#fcd78384727be545d08a96c0d5242902288dafd7",
      "from": "github:oracle/node-oracledb#v2.3.0",
      "requires": {
        "nan": "~2.10.0"
      },
      "dependencies": {
        "nan": {
          "version": "2.10.0",
          "resolved": "https://registry.npmjs.org/nan/-/nan-2.10.0.tgz",
          "integrity": "sha512-bAdJv7fBLhWC+/Bls0Oza+mvTaNQtP+1RyhhhvD95pgUJz6XM5IzgmxOkItJ9tkoCiplvAnXI1tNmmUD/eScyA=="
        }
      }
    }
  }
}
```
5. What is your OS and version?
```macOS High Sierra 10.13.5```

6. What is your compiler version?  For example, with GCC, run `gcc --version`
```$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

7. What Oracle environment variables did you set?  How *exactly* did you set them?

**(not sure how to answer this question)**

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

```/Users/michaelfisch/personal-projects/test-oracle```

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

10. What error(s) you are seeing?
```
~/personal-projects/test-oracle/examples (master)
$ node select1.js 
/Users/michaelfisch/personal-projects/test-oracle/node_modules/oracledb/lib/oracledb.js:65
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^

Error: NJS-045: cannot load the oracledb add-on binary for Node.js 10.5.0 (darwin, x64)
Node.js require() error was: 
  DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node.js require() mapped to /Users/michaelfisch/personal-projects/test-oracle/node_modules/oracledb/build/Release/oracledb.node
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the 64-bit Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
They can be downloaded from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
    at Object.<anonymous> (/Users/michaelfisch/personal-projects/test-oracle/node_modules/oracledb/lib/oracledb.js:65:13)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/michaelfisch/personal-projects/test-oracle/node_modules/oracledb/index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
```

**Comment by cjbj** [comment]
[If you get a chance to review the install instructions and point out what was confusing, we can update them.]

I unzip the Instant Client 'Basic' package into `~/instantclient_12_2` and this one link is all that's in my `~/lib` directory:
```
  /Users/cjones/lib:
  lrwxr-xr-x    1 cjones  staff    43  2 May 10:10 libclntsh.dylib -> /Users/cjones/instantclient_12_2/libclntsh.dylib
```

The question about Oracle environment variables is to find out if you have variables like `TNS_ADMIN`, or `NLS_LANG` (among others) set.

**Comment by Ventis** [comment]
Having this issue as well, even with the pre-built Docker image of Collin Estes.

**Comment by cjbj** [comment]
@Ventis A macOS image??  FWIW, see https://blogs.oracle.com/opal/a-node-oracledb-web-service-in-docker

**Comment by Ventis** [comment]
@cjbj I think Collin Estes image starts from the `node` image which runs Ubuntu if I'm not mistaken. But I am running it on my Macbook.

**Comment by cjbj** [comment]
@Ventis if the image is Ubuntu then it is not related to this issue: the library loading is different on macOS.  But I see you've opened https://github.com/oracle/node-oracledb/issues/939 where we can continue discussion.

**Comment by GiantSlayer1913** [comment]
Ok, so I was mainly concerned if I missed a step while setting up the oracle environment on my mac. I went back through the steps and edited my dbconfig.js file to the specifications in the instructions: 
```
3.5.6 Run an example program
Download the example programs from GitHub.

Edit dbconfig.js and set the database credentials to your environment, for example:

module.exports = {
  user          : "hr",
  password      : "welcome",
  connectString : "localhost/XE"
};
```
Then, I ran the following command and got a new error, so I must be doing something right.
```
Error:
~/personal-projects/test-oracle (master)
$ node examples/select1.js 
ORA-12541: TNS:no listener
```

**Comment by cjbj** [comment]
@GiantSlayer1913 that is progress.  Now you just need to find the correct connect string for your DB.  Do you know where your DB is?  Do you connect to it using other tools like SQL*Plus or SQL Developer? The 'localhost/XE' connect string will work if you have installed the Oracle XE edition DB on the same computer as Node.js.

**Comment by GiantSlayer1913** [comment]
I'm not sure if I may be installing the Oracle Instant Client Basic in the wrong location.
test-oracle is the project name and instant client was unzipped within the project directory.
``` 
/Users/"myname"/personal-projects/test-oracle/instantclient_12_2
```

**Comment by cjbj** [comment]
@GiantSlayer1913 has something gone backwards?  When you previously got the error `ORA-12541: TNS:no listener` you had everything installed just fine - all you needed was a database, but that's independent of node-oracledb.

Getting `DPI-1047` now means you've gone backwards!  The Instant Client install instructions for macOS are [here](https://oracle.github.io/node-oracledb/INSTALL.html#354-install-the-free-oracle-instant-client-basic-zip-file). You can pretty much install Instant Client in any location but then must have the right links set up in ~/lib or /usr/local/lib due to an Apple security requirement.  I earlier [showed](https://github.com/oracle/node-oracledb/issues/937#issuecomment-401642805) the link I have.  In practice, I would keep Instant Client out of the project directory and keep it somewhere central.

**Comment by samizzy** [comment]
Hi i am having a similar issue,

> C:\Users\Samrat\Desktop\node_projects\aws_sts_webservice\node_modules\oracledb\lib\oracledb.js:68
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^
Error: NJS-045: cannot load the oracledb add-on binary for Node.js 10.4.1 (win32, x64)
Cannot load C:\Users\Samrat\Desktop\node_projects\aws_sts_webservice\node_modules\oracledb\build\Release\oracledb.node
Error while trying to retrieve text for error ORA-01804
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.


On my windows 10 machine, I have a local installation of oracle XE, i have installed vc++ redistributable 2005 and 2015.  Nodejs version is 10.4.1.
Also my path variable is,

> D:\oraclexe\app\oracle\product\11.2.0\server\bin;;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Users\Samrat\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\Users\Samrat\AppData\Roaming\npm

so it is pointing correctly to the bin folder.

I have been stuck on this for hours, i have read the documentation and tried everything (I think), if anyone could provide help it would be great.

**Comment by cjbj** [comment]
@samizzy  your error is different to the one this issue was opened for.   It's best to open new issue.  And check with your DBA.

**Comment by cjbj** [comment]
Closing due to lack of activity.
