### ISSUE TITLE
Error: kali linux npm install -g oracle/node-oracledb.git#v2.3.0

### ISSUE THREAD

**Issue by hktalent** [oracle/node-oracledb#958]
kali linux
```
# npm install -g oracle/node-oracledb.git#v2.3.0


> oracledb@2.3.0 install /root/local/lib/node_modules/oracledb
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/local/lib/node_modules/oracledb/build'
gyp ERR! System Linux 4.9.93-linuxkit-aufs
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/local/lib/node_modules/oracledb
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN You are using a pre-release version of node and things may not work as expected

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-06T07_57_27_829Z-debug.log

# cat /root/.npm/_logs/2018-08-06T07_57_27_829Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/root/local/bin/node',
1 verbose cli   '/root/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'oracle/node-oracledb.git#v2.3.0' ]
2 info using npm@6.3.0
3 info using node@v11.0.0-pre
4 verbose npm-session 66e72022b63ba375
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly pacote git manifest for undefined@github:oracle/node-oracledb#v2.3.0 fetched in 1601ms
8 timing stage:loadCurrentTree Completed in 1804ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
12 silly install loadShrinkwrap
13 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
14 silly install loadAllDepsIntoIdealTree
15 silly resolveWithNewModule oracledb@2.3.0 checking installable status
16 http fetch GET 304 https://registry.npmjs.org/nan 1030ms (from cache)
17 silly pacote range manifest for nan@~2.10.0 fetched in 1040ms
18 silly resolveWithNewModule nan@2.10.0 checking installable status
19 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1055ms
20 timing stage:loadIdealTree Completed in 1061ms
21 silly currentTree lib
22 silly idealTree lib
22 silly idealTree └─┬ oracledb@2.3.0
22 silly idealTree   └── nan@2.10.0
23 silly install generateActionsToTake
24 timing stage:generateActionsToTake Completed in 4ms
25 silly diffTrees action count 2
26 silly diffTrees add nan@2.10.0
27 silly diffTrees add oracledb@2.3.0
28 silly decomposeActions action count 16
29 silly decomposeActions fetch nan@2.10.0
30 silly decomposeActions extract nan@2.10.0
31 silly decomposeActions preinstall nan@2.10.0
32 silly decomposeActions build nan@2.10.0
33 silly decomposeActions install nan@2.10.0
34 silly decomposeActions postinstall nan@2.10.0
35 silly decomposeActions finalize nan@2.10.0
36 silly decomposeActions refresh-package-json nan@2.10.0
37 silly decomposeActions fetch oracledb@2.3.0
38 silly decomposeActions extract oracledb@2.3.0
39 silly decomposeActions preinstall oracledb@2.3.0
40 silly decomposeActions build oracledb@2.3.0
41 silly decomposeActions install oracledb@2.3.0
42 silly decomposeActions postinstall oracledb@2.3.0
43 silly decomposeActions finalize oracledb@2.3.0
44 silly decomposeActions refresh-package-json oracledb@2.3.0
45 silly install executeActions
46 silly doSerial global-install 16
47 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
48 verbose lock using /root/.npm/_locks/staging-3a829bf2425f7779.lock for /root/local/lib/node_modules/.staging
49 silly doParallel extract 2
50 silly extract nan@2.10.0
51 silly extract oracledb@2.3.0
52 silly tarball trying nan@~2.10.0 by hash: sha512-bAdJv7fBLhWC+/Bls0Oza+mvTaNQtP+1RyhhhvD95pgUJz6XM5IzgmxOkItJ9tkoCiplvAnXI1tNmmUD/eScyA==
53 silly tarball no local data for github:oracle/node-oracledb#v2.3.0. Extracting by manifest.
54 silly extract nan@~2.10.0 extracted to /root/local/lib/node_modules/.staging/nan-0b8db6ba (178ms)
55 info lifecycle oracledb@2.3.0~prepack: oracledb@2.3.0
56 info lifecycle oracledb@2.3.0~postpack: oracledb@2.3.0
57 silly extract github:oracle/node-oracledb#v2.3.0 extracted to /root/local/lib/node_modules/.staging/oracledb-cf7a5aa8 (12189ms)
58 timing action:extract Completed in 12208ms
59 silly doReverseSerial unbuild 16
60 silly doSerial remove 16
61 silly doSerial move 16
62 silly doSerial finalize 16
63 silly finalize /root/local/lib/node_modules/oracledb/node_modules/nan
64 silly finalize /root/local/lib/node_modules/oracledb
65 timing action:finalize Completed in 9ms
66 silly doParallel refresh-package-json 2
67 silly refresh-package-json /root/local/lib/node_modules/oracledb/node_modules/nan
68 silly refresh-package-json /root/local/lib/node_modules/oracledb
69 timing action:refresh-package-json Completed in 14ms
70 silly doParallel preinstall 2
71 silly preinstall nan@2.10.0
72 info lifecycle nan@2.10.0~preinstall: nan@2.10.0
73 silly preinstall oracledb@2.3.0
74 info lifecycle oracledb@2.3.0~preinstall: oracledb@2.3.0
75 timing action:preinstall Completed in 1ms
76 silly doSerial build 16
77 silly build nan@2.10.0
78 info linkStuff nan@2.10.0
79 silly linkStuff nan@2.10.0 has /root/local/lib/node_modules/oracledb/node_modules as its parent node_modules
80 silly linkStuff nan@2.10.0 is part of a global install
81 silly linkStuff nan@2.10.0 is installed into a global node_modules
82 silly build oracledb@2.3.0
83 info linkStuff oracledb@2.3.0
84 silly linkStuff oracledb@2.3.0 has /root/local/lib/node_modules as its parent node_modules
85 silly linkStuff oracledb@2.3.0 is part of a global install
86 silly linkStuff oracledb@2.3.0 is installed into a global node_modules
87 silly linkStuff oracledb@2.3.0 is installed into the top-level global node_modules
88 timing action:build Completed in 1ms
89 silly doSerial global-link 16
90 silly doParallel update-linked 0
91 silly doSerial install 16
92 silly install nan@2.10.0
93 info lifecycle nan@2.10.0~install: nan@2.10.0
94 silly install oracledb@2.3.0
95 info lifecycle oracledb@2.3.0~install: oracledb@2.3.0
96 verbose lifecycle oracledb@2.3.0~install: unsafe-perm in lifecycle false
97 verbose lifecycle oracledb@2.3.0~install: PATH: /root/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/local/lib/node_modules/oracledb/node_modules/.bin:/root/local/lib/node_modules/.bin::/opt/mssql-tools/bin/:/usr/local/bin:/root/local/bin/:/usr/share/jython/bin:/root/local/bin:/usr/lib/jvm/java-10-openjdk-amd64/bin:/root/mytools/oracle_client_12_2_exp_imp/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
98 verbose lifecycle oracledb@2.3.0~install: CWD: /root/local/lib/node_modules/oracledb
99 silly lifecycle oracledb@2.3.0~install: Args: [ '-c', 'node-gyp rebuild' ]
100 silly lifecycle oracledb@2.3.0~install: Returned: code: 1  signal: null
101 info lifecycle oracledb@2.3.0~install: Failed to exec install script
102 timing action:install Completed in 2091ms
103 verbose unlock done using /root/.npm/_locks/staging-3a829bf2425f7779.lock for /root/local/lib/node_modules/.staging
104 timing stage:rollbackFailedOptional Completed in 22ms
105 timing stage:runTopLevelLifecycles Completed in 17242ms
106 warn You are using a pre-release version of node and things may not work as expected
107 verbose stack Error: oracledb@2.3.0 install: `node-gyp rebuild`
107 verbose stack Exit status 1
107 verbose stack     at EventEmitter.<anonymous> (/root/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
107 verbose stack     at EventEmitter.emit (events.js:182:13)
107 verbose stack     at ChildProcess.<anonymous> (/root/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
107 verbose stack     at ChildProcess.emit (events.js:182:13)
107 verbose stack     at maybeClose (internal/child_process.js:961:16)
107 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
108 verbose pkgid oracledb@2.3.0
109 verbose cwd /root/local/lib
110 verbose Linux 4.9.93-linuxkit-aufs
111 verbose argv "/root/local/bin/node" "/root/local/bin/npm" "install" "-g" "oracle/node-oracledb.git#v2.3.0"
112 verbose node v11.0.0-pre
113 verbose npm  v6.3.0
114 error code ELIFECYCLE
115 error errno 1
116 error oracledb@2.3.0 install: `node-gyp rebuild`
116 error Exit status 1
117 error Failed at the oracledb@2.3.0 install script.
117 error This is probably not a problem with npm. There is likely additional logging output above.
118 verbose exit [ 1, true ]
```

**Comment by hktalent** [comment]
```
# npm i -g node-oracledb
npm ERR! code E404
npm ERR! 404 Not Found: node-oracledb@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-06T08_04_00_848Z-debug.log
root@68a0c0fa2e94:~/local/lib# /root/.npm/_logs/2018-08-06T08_04_00_848Z-debug.log
bash: /root/.npm/_logs/2018-08-06T08_04_00_848Z-debug.log: Permission denied
root@68a0c0fa2e94:~/local/lib# cat /root/.npm/_logs/2018-08-06T08_04_00_848Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/root/local/bin/node',
1 verbose cli   '/root/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'node-oracledb' ]
2 info using npm@6.3.0
3 info using node@v11.0.0-pre
4 verbose npm-session e41703c097ef5916
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/node-oracledb 1161ms
8 silly fetchPackageMetaData error for node-oracledb@latest 404 Not Found: node-oracledb@latest
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 1358ms
11 verbose stack Error: 404 Not Found: node-oracledb@latest
11 verbose stack     at fetch.then.res (/root/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/root/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/root/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/root/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/root/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/root/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/root/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/root/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/root/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:664:18)
11 verbose stack     at tryOnImmediate (timers.js:635:5)
11 verbose stack     at processImmediate (timers.js:617:5)
12 verbose cwd /root/local/lib
13 verbose Linux 4.9.93-linuxkit-aufs
14 verbose argv "/root/local/bin/node" "/root/local/bin/npm" "i" "-g" "node-oracledb"
15 verbose node v11.0.0-pre
16 verbose npm  v6.3.0
17 error code E404
18 error 404 Not Found: node-oracledb@latest
19 verbose exit [ 1, true ]
```

**Comment by hktalent** [comment]
```
# npm search node-oracledb
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
oracledb                  | A Node.js module…    | =cjbj…          | 2018-06-08 | 2.3.0    | Oracle Database official DB SQL JSON PL/SQL OCI API client library driver add-on extension binding interface a


# npm i -g oracledb

> oracledb@2.3.0 install /root/local/lib/node_modules/oracledb
> node package/oracledbinstall.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/local/lib/node_modules/oracledb/package/oracledbinstall.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm WARN You are using a pre-release version of node and things may not work as expected

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@2.3.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 1


# cat /root/.npm/_logs/2018-08-06T08_06_47_716Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/root/local/bin/node',
1 verbose cli   '/root/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'oracledb' ]
2 info using npm@6.3.0
3 info using node@v11.0.0-pre
4 verbose npm-session d05d2e8cc2b07cb1
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/oracledb 1049ms (from cache)
8 silly pacote tag manifest for oracledb@latest fetched in 1067ms
9 timing stage:loadCurrentTree Completed in 1295ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule oracledb@2.3.0 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 4ms
18 timing stage:loadIdealTree Completed in 8ms
19 silly currentTree lib
20 silly idealTree lib
20 silly idealTree └── oracledb@2.3.0
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 4ms
23 silly diffTrees action count 1
24 silly diffTrees add oracledb@2.3.0
25 silly decomposeActions action count 8
26 silly decomposeActions fetch oracledb@2.3.0
27 silly decomposeActions extract oracledb@2.3.0
28 silly decomposeActions preinstall oracledb@2.3.0
29 silly decomposeActions build oracledb@2.3.0
30 silly decomposeActions install oracledb@2.3.0
31 silly decomposeActions postinstall oracledb@2.3.0
32 silly decomposeActions finalize oracledb@2.3.0
33 silly decomposeActions refresh-package-json oracledb@2.3.0
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
37 verbose lock using /root/.npm/_locks/staging-3a829bf2425f7779.lock for /root/local/lib/node_modules/.staging
38 silly doParallel extract 1
39 silly extract oracledb@2.3.0
40 silly tarball trying oracledb@latest by hash: sha512-zTG1elqQ3kdGiu93OcWYje3YCFO2kfLBTC1KjEyxIck8gnH9H2vAqrE5AgPdPmColIf961g3KwwxcwlEnX0CpA==
41 silly extract oracledb@latest extracted to /root/local/lib/node_modules/.staging/oracledb-cf7a5aa8 (83ms)
42 timing action:extract Completed in 88ms
43 silly doReverseSerial unbuild 8
44 silly doSerial remove 8
45 silly doSerial move 8
46 silly doSerial finalize 8
47 silly finalize /root/local/lib/node_modules/oracledb
48 timing action:finalize Completed in 5ms
49 silly doParallel refresh-package-json 1
50 silly refresh-package-json /root/local/lib/node_modules/oracledb
51 timing action:refresh-package-json Completed in 17ms
52 silly doParallel preinstall 1
53 silly preinstall oracledb@2.3.0
54 info lifecycle oracledb@2.3.0~preinstall: oracledb@2.3.0
55 timing action:preinstall Completed in 1ms
56 silly doSerial build 8
57 silly build oracledb@2.3.0
58 info linkStuff oracledb@2.3.0
59 silly linkStuff oracledb@2.3.0 has /root/local/lib/node_modules as its parent node_modules
60 silly linkStuff oracledb@2.3.0 is part of a global install
61 silly linkStuff oracledb@2.3.0 is installed into a global node_modules
62 silly linkStuff oracledb@2.3.0 is installed into the top-level global node_modules
63 timing action:build Completed in 1ms
64 silly doSerial global-link 8
65 silly doParallel update-linked 0
66 silly doSerial install 8
67 silly install oracledb@2.3.0
68 info lifecycle oracledb@2.3.0~install: oracledb@2.3.0
69 verbose lifecycle oracledb@2.3.0~install: unsafe-perm in lifecycle false
70 verbose lifecycle oracledb@2.3.0~install: PATH: /root/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/local/lib/node_modules/oracledb/node_modules/.bin:/root/local/lib/node_modules/.bin::/opt/mssql-tools/bin/:/usr/local/bin:/root/local/bin/:/usr/share/jython/bin:/root/local/bin:/usr/lib/jvm/java-10-openjdk-amd64/bin:/root/mytools/oracle_client_12_2_exp_imp/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
71 verbose lifecycle oracledb@2.3.0~install: CWD: /root/local/lib/node_modules/oracledb
72 silly lifecycle oracledb@2.3.0~install: Args: [ '-c', 'node package/oracledbinstall.js' ]
73 silly lifecycle oracledb@2.3.0~install: Returned: code: 1  signal: null
74 info lifecycle oracledb@2.3.0~install: Failed to exec install script
75 timing action:install Completed in 381ms
76 verbose unlock done using /root/.npm/_locks/staging-3a829bf2425f7779.lock for /root/local/lib/node_modules/.staging
77 timing stage:rollbackFailedOptional Completed in 26ms
78 timing stage:runTopLevelLifecycles Completed in 1834ms
79 warn You are using a pre-release version of node and things may not work as expected
80 verbose stack Error: oracledb@2.3.0 install: `node package/oracledbinstall.js`
80 verbose stack Exit status 1
80 verbose stack     at EventEmitter.<anonymous> (/root/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
80 verbose stack     at EventEmitter.emit (events.js:182:13)
80 verbose stack     at ChildProcess.<anonymous> (/root/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
80 verbose stack     at ChildProcess.emit (events.js:182:13)
80 verbose stack     at maybeClose (internal/child_process.js:961:16)
80 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
81 verbose pkgid oracledb@2.3.0
82 verbose cwd /root/local/lib
83 verbose Linux 4.9.93-linuxkit-aufs
84 verbose argv "/root/local/bin/node" "/root/local/bin/npm" "i" "-g" "oracledb"
85 verbose node v11.0.0-pre
86 verbose npm  v6.3.0
87 error code ELIFECYCLE
88 error errno 1
89 error oracledb@2.3.0 install: `node package/oracledbinstall.js`
89 error Exit status 1
90 error Failed at the oracledb@2.3.0 install script.
90 error This is probably not a problem with npm. There is likely additional logging output above.
91 verbose exit [ 1, true ]
```

**Comment by cjbj** [comment]
What's your question?

The first error looks like something that will block you:
```
stack Error: EACCES: permission denied,
```

Do you need to use `sudo` since you are installing into a system directory?

**Comment by hktalent** [comment]
@cjbj 

```
# set |grep oracle
LD_LIBRARY_PATH=/root/mytools/oracle_client_12_2_exp_imp/lib
ORACLE_HOME=/root/mytools/oracle_client_12_2_exp_imp
PATH=:/opt/mssql-tools/bin/:/usr/local/bin:/root/local/bin/:/usr/share/jython/bin:/root/local/bin:/usr/lib/jvm/java-10-openjdk-amd64/bin:/root/mytools/oracle_client_12_2_exp_imp/::/opt/mssql-tools/bin/:/usr/local/bin:/root/local/bin/:/usr/share/jython/bin:/root/local/bin:/usr/lib/jvm/java-10-openjdk-amd64/bin:/root/mytools/oracle_client_12_2_exp_imp/::/opt/mssql-tools/bin/:/usr/local/bin:/root/local/bin/:/usr/share/jython/bin:/root/local/bin:/usr/lib/jvm/java-10-openjdk-amd64/bin:/root/mytools/oracle_client_12_2_exp_imp/::/opt/mssql-tools/bin/:/usr/local/bin:/root/local/bin/:/usr/share/jython/bin:/root/local/bin:/usr/lib/jvm/java-10-openjdk-amd64/bin:/root/mytools/oracle_client_12_2_exp_imp/::/opt/mssql-tools/bin/:/usr/local/bin:/root/local/bin/:/usr/share/jython/bin:/root/local/bin:/usr/lib/jvm/java-10-openjdk-amd64/bin:/root/mytools/oracle_client_12_2_exp_imp/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/root/local/lib/node_modules/oracledb

# npm test

> oracledb@3.0.0-dev test /root/local/lib/node_modules/oracledb
> mocha --opts test/opts/mocha.opts

/root/local/lib/node_modules/oracledb/lib/oracledb.js:53
        throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
        ^

Error: NJS-045: cannot load the oracledb add-on binary for Node.js 11.0.0-pre (linux, x64)
Cannot find module /root/local/lib/node_modules/oracledb/build/Release/oracledb.node
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

    at Object.<anonymous> (/root/local/lib/node_modules/oracledb/lib/oracledb.js:53:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/local/lib/node_modules/oracledb/index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/local/lib/node_modules/oracledb/test/connection.js:30:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /root/local/lib/node_modules/oracledb/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/root/local/lib/node_modules/oracledb/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/root/local/lib/node_modules/oracledb/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/root/local/lib/node_modules/oracledb/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:260:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:584:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by cjbj** [comment]
https://github.com/oracle/node-oracledb/blob/master/package/package.json#L37 which executes https://github.com/oracle/node-oracledb/blob/master/package/oracledbinstall.js#L327-L350

Why does this fail for you?

**Comment by cjbj** [comment]
Did you reproduce this?

**Comment by cjbj** [comment]
Closing - no activity.

**Comment by cjbj** [comment]
A solution to the 'mkdir build' error when installing globally was proposed in https://stackoverflow.com/questions/52962510/mkdir-permission-error-while-importing-oracledb3-0-0-with-node10-9-0
```
npm install -g oracledb --unsafe-perm=true --allow-root
```
