### ISSUE TITLE
Getting npm verb stack Error: 405 Method Not Allowed: oracledb@latest

### ISSUE THREAD

**Issue by manoharraju2020** [oracle/node-oracledb#968]
1. What is your Node.js version? 64-bit ?  

Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js
Getting below error when i run version.js
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Softwares\nodeJS\APIProjects\version.js:26:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

2. What is your node-oracledb version?
where to check this version.

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
4. What error(s) you are seeing?
C:\Program Files\nodejs>npm install --verbose oracledb
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'oracledb' ]
npm info using npm@6.2.0
npm info using node@v10.9.0
npm verb npm-session 1b0c80ecaff86c3a
npm http fetch GET 405 https://registry.npmjs.org/oracledb 478ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 30146ms
npm verb stack Error: 405 Method Not Allowed: oracledb@latest
npm verb stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\n
ode_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
npm verb stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_
modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs
\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modul
es\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modu
les\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modu
les\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm verb stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\np
m\node_modules\bluebird\js\release\async.js:133:16)
npm verb stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\n
pm\node_modules\bluebird\js\release\async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program
Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at runCallback (timers.js:693:18)
npm verb stack     at tryOnImmediate (timers.js:664:5)
npm verb stack     at processImmediate (timers.js:646:5)
npm verb cwd C:\Program Files\nodejs
npm verb Windows_NT 6.1.7601
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "oracledb"
npm verb node v10.9.0
npm verb npm  v6.2.0
npm ERR! code E405
npm ERR! 405 Method Not Allowed: oracledb@latest
npm verb exit [ 1, true ]
npm timing npm Completed in 39776ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mb942712\AppData\Roaming\npm-cache\_logs\2018-08-24T14_42_
37_794Z-debug.log

5. What OS (and version) is Node.js executing on?
windows 7 Proffessional

6. What is your Oracle client (e.g. Instant Client) version?  64-bit
   How was it installed?  Installed long back using .exe file 
    Where is it installed? C:\oracle\ora11202

7. What is your Oracle Database version? 11.2

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
C:\Program Files\nodejs\;C:\oracle\ora11202\bin

9. What Oracle environment variables did you set?  How *exactly* did you set them?
Not set any Oracle environment variables other than above.

10. Do you have a small, single Node.js script that immediately runs to show us the problem?
other node.js programs are running fine  but not able to install node-oracledb on my laptop. 

Signed-off-by: Manohar Raju Biruduraju <manoharraju2020@gmail.com>

**Comment by cjbj** [comment]
Did you sort this out?

**Comment by manoharraju2020** [comment]
Hi 
I have resolved the issue by copying the node_modules\oracledb Binaries from my personal laptop which was installed. 

I initially tried this in my office laptop with in office closed/firewall network, due to which it couldn't access the npm registry and gave the above error. 

I am now able to work with oracledb using nodejs. Thanks.
